apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autobrr
  namespace: autobrr
spec:
  interval: 15m
  chart:
    spec:
      chart: autobrr
      version: 9.1.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: autobrr
  values:
    addons:
      vpn:
        env:
          DNS_ADDRESS:
            name: DNS_ADDRESS
            value: ${DNS_ADDRESS_0}
          VPN_ENDPOINT_IP:
            name: VPN_ENDPOINT_IP
            value: ${VPN_ENDPOINT_IP_0}
          VPN_ENDPOINT_PORT:
            name: VPN_ENDPOINT_PORT
            value: ${VPN_ENDPOINT_PORT_0}
          VPN_SERVICE_PROVIDER:
            name: VPN_SERVICE_PROVIDER
            value: custom
          VPN_TYPE:
            name: VPN_TYPE
            value: wireguard
          WIREGUARD_ADDRESSES:
            name: WIREGUARD_ADDRESSES
            value: ${WIREGUARD_ADDRESSES_0}
          WIREGUARD_PRIVATE_KEY:
            name: WIREGUARD_PRIVATE_KEY
            value: ${WIREGUARD_PRIVATE_KEY_0}
          WIREGUARD_PUBLIC_KEY:
            name: WIREGUARD_PUBLIC_KEY
            value: ${WIREGUARD_PUBLIC_KEY_0}
        excludedNetworks_IPv4:
          - ${EXCLUDED_IPV4_0}
        killSwitch: true
        type: gluetun
    autobrr:
      log_level: DEBUG
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - autobrr.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: autobrr.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      autobrr-config:
        enabled: true
        mountPath: /config/config.toml
        objectName: autobrr-config
        readOnly: true
        subPath: config.toml
        type: configmap
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      watchdir:
        enabled: true
        type: nfs
        mountPath: /watchdir
        path: ${DATASET_MEDIA}/temp/joal
        server: ${NFS_SERVER_0}
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 7474
            protocol: http
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  type: http
                readiness:
                  type: http
                startup:
                  type: tcp
        replicas: 1
        type: Deployment
