apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: archivebox
  namespace: archivebox
spec:
  interval: 15m
  chart:
    spec:
      chart: archivebox
      version: 3.0.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    config:
      admin_password: ${PASSWORD_ARCHIVEBOX}
      admin_username: ${USER_1}
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - archivebox.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: archivebox.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      data:
        enabled: true
        mountPath: /data
        volsync:
          - credentials: backblaze
            name: dat
            src:
              enabled: true
            type: restic
      config:
        enabled: true
        type: nfs
        mountPath: /config
        path: "${DATASET_APPS}/kubernetes/archivebox"
        server: ${NFS_SERVER_0}
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 9598
            protocol: http
            targetPort: 8000
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                ADMIN_PASSWORD: '{{ .Values.config.admin_password }}'
                ADMIN_USERNAME: '{{ .Values.config.admin_username }}'
                CHROME_USER_DATA_DIR:
                  name: CHROME_USER_DATA_DIR
                  value: /config/chrome_profile
                COOKIES_FILE:
                  name: COOKIES_FILE
                  value: /config/cookies.txt
                SAVE_ARCHIVE_DOT_ORG:
                  name: SAVE_ARCHIVE_DOT_ORG
                  value: "FALSE"
              probes:
                liveness:
                  path: /health/
                  type: http
        replicas: 1
        type: Deployment
