---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flare-bypasser
  namespace: flare-bypasser
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    image:
      repository: ghcr.io/yoori/flare-bypasser
      pullPolicy: IfNotPresent
      tag: latest@sha256:94783306a04be4f148028f645d83572e49a9277db160caad864c4f5d3d2f561f

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0

    service:
      main:
        ports:
          main:
            port: 20080
            targetPort: 8080

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                UNUSED: "false"
                SAVE_CHALLENGE_SCREENSHOTS: "true"

    persistence:
      config:
        enabled: true
        mountPath: /opt/flare_bypasser/var/