apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  interval: 15m
  chart:
    spec:
      chart: pgadmin
      version: 16.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - pga.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: pga.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /var/lib/pgadmin
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        fsGroup: 5050
        runAsGroup: 5050
        runAsNonRoot: true
        runAsUser: 5050
      pod:
        fsGroup: 5050
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10024
            targetPort: 80
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
                PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
              probes:
                liveness:
                  enabled: true
                  path: /misc/ping
                  type: http
                readiness:
                  enabled: true
                  path: /misc/ping
                  type: http
                startup:
                  enabled: true
                  path: /misc/ping
                  type: http
        replicas: 1
        type: Deployment
