apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kavita
  namespace: kavita
spec:
  interval: 15m
  chart:
    spec:
      chart: kavita
      version: 10.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - kavita.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: kavita.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /kavita/config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      manga:
        enabled: true
        mountPath: /manga
        volsync:
          - credentials: backblaze
            name: mag
            src:
              enabled: true
            type: restic
      tmp:
        enabled: false
      media:
        enabled: true
        type: nfs
        mountPath: /media
        path: ${DATASET_MEDIA}/library/books
        server: ${NFS_SERVER_0}
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10189
            targetPort: 5000
        type: ClusterIP
    workload:
      main:
        replicas: 1
        type: Deployment
