apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shlink-web-client
  namespace: shlink
spec:
  interval: 15m
  chart:
    spec:
      chart: shlink-web-client
      version: 11.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - shlink.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: shlink.${DOMAIN_0}

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SHLINK_SERVER_API_KEY: ${SHLINK_SERVER_API_KEY}
                SHLINK_SERVER_URL: https://shlink.${DOMAIN_0}