apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 26.4.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    log:
      level: info
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    cnpg:
      main:
        mode: recovery
        password: ${CNPG_PASSWORD_AUTHELIA}
        cluster:
          singleNode: true
        backups:
          enabled: true
          revision: "1"
          credentials: backblaze
        recovery:
          credentials: backblaze

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                AUTHELIA_THEME: grey
                AUTHELIA_SERVER_ASSET_PATH: /config/assets

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true

    domain: ${DOMAIN_0}
    default_redirection_url: https://auth.${DOMAIN_0}

    password_policy:
      zxcvbn:
        enabled: true
        min_score: 3

    authentication_backend:
      ldap:
        enabled: true
        implementation: custom
        url: ldap://lldap-ldap.lldap.svc.cluster.local:3890
        base_dn: dc=${USER_1},dc=${DOMAIN_TLD_0}
        additional_users_dn: ou=people
        users_filter: (&({username_attribute}={input})(objectClass=person))
        groups_filter: (member={dn})
        user: uid=${USER_0},ou=people,dc=${USER_1},dc=${DOMAIN_TLD_0}
        plain_password: ${LDAP_USER_PASS}
      file:
        enabled: false

    regulation:
      ban_time: 60m
      find_time: 60m
      max_retries: 10

    notifier:
      smtp:
        enabled: true
        host: ${SMTP_HOST_0}
        port: 587
        username: ${SMTP_USERNAME_0}
        plain_password: ${SMTP_PASSWORD_AUTHELIA}
        sender: ${SMTP_FROM_AUTHELIA}
        subject: '[Authelia] {title}'
        startup_check_address: ${SMTP_FROM_AUTHELIA}
      filesystem:
        enabled: false

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
            - auth.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
          # - hosts:
          #   - auth.${DOMAIN_1}
          #   clusterIssuer: domain-1-wildcard
        hosts:
          - host: auth.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
          # - host: auth.${DOMAIN_1}

    identity_providers:
      oidc:
        enabled: true
        clients:
          # NEXTCLOUD
          - id: ${OIDC_CLIENT_ID_NEXTCLOUD}
            secret: ${OIDC_SECRET_NEXTCLOUD}
            description: Freeman • Cloud
            public: false
            authorization_policy: two_factor
            consent_mode: implicit
            require_pkce: true
            pkce_challange_method: S256
            redirect_uris:
            - https://cloud.${DOMAIN_0}/apps/oidc_login/oidc
            scopes:
            - openid
            - profile
            - email
            - groups
            userinfo_signing_algorithm: none
            token_endpoint_auth_method: client_secret_basic

          # IMMICH
          - id: ${OIDC_CLIENT_ID_IMMICH}
            secret: ${OIDC_SECRET_IMMICH}
            description: Freeman • Photos
            public: false
            authorization_policy: two_factor
            consent_mode: implicit
            redirect_uris:
            - https://photos.${DOMAIN_0}/auth/login
            - https://photos.${DOMAIN_0}/user-settings
            - app.immich:///oauth-callback
            scopes:
            - openid
            - profile
            - email
            - groups
            userinfo_signing_algorithm: none

          # MEALIE
          - id: ${OIDC_CLIENT_ID_MEALIE}
            secret: ${OIDC_SECRET_MEALIE}
            description: Mealie
            public: false
            authorization_policy: two_factor
            consent_mode: implicit
            require_pkce: true
            pkce_challenge_method: S256
            redirect_uris:
            - https://mealie.${DOMAIN_0}/login
            scopes:
            - openid
            - email
            - profile
            - groups
            userinfo_signed_response_alg: none

          # VIKUNJA
          - id: ${OIDC_CLIENT_ID_VIKUNJA}
            secret: ${OIDC_SECRET_VIKUNJA}
            description: Freeman • Todo
            public: false
            authorization_policy: two_factor
            consent_mode: implicit
            redirect_uris:
            - https://todo.${DOMAIN_0}/auth/openid/authelia
            scopes:
            - openid
            - profile
            - email
            userinfo_signing_algorithm: none
            token_endpoint_auth_method: client_secret_basic

    access_control:
      rules:
        # GENERIC API
        - domain:
          - "*.${DOMAIN_0}"
          - "${DOMAIN_1}"
          - "*.${DOMAIN_1}"
          policy: bypass
          resources:
          - "^/api([/?].*)?$"
          - "^/api([/?].*)?$"
          - "^/identity.*$"
          - "^/triggers.*$"
          - "^/meshagents.*$"
          - "^/meshsettings.*$"
          - "^/agent.*$"
          - "^/control.*$"
          - "^/meshrelay.*$"
          - "^/wl.*$"

        # COMPANION API
        - domain: "companion.${DOMAIN_0}"
          policy: bypass
          networks:
          - "${EXCLUDED_IPV4_0}"
          resources:
          - "^/press([/?].*)?$"
          - "^/assets([/?].*)?$"
          - '^/socket\.io([/?].*)?$'

        # USER_99
        - domain:
          - "companion.${DOMAIN_0}"
          policy: two_factor
          resources:
          - "^/tablet([/?].*)?$"
          - "^/assets([/?].*)?$"
          - '^/socket\.io([/?].*)?$'
          subject: user:${USER_99}

        # USER_2
        - domain:
          - "split.${DOMAIN_0}"
          - "homebox.${DOMAIN_0}"
          - "mealie.${DOMAIN_0}"
          - "stash.${DOMAIN_0}"
          policy: two_factor
          subject: user:${USER_2}

        # USER GROUP
        - domain:
          - "auth.${DOMAIN_0}"
          - "cloud.${DOMAIN_0}"
          - "kavita.${DOMAIN_1}"
          - "plex.${DOMAIN_1}"
          - "search.${DOMAIN_0}"
          policy: two_factor
          subject: group:user

        # ADMIN GROUP
        - domain:
          - "*.${DOMAIN_0}"
          - "${DOMAIN_1}"
          - "*.${DOMAIN_1}"
          policy: two_factor
          subject: group:admin

    # session:
    #   cookies:
    #     - subdomain: 'auth'
    #       domain: '${DOMAIN_0}'
    #       default_redirection_url: 'https://${DOMAIN_0}'
    #     - subdomain: 'auth'
    #       domain: '${DOMAIN_1}'
    #       default_redirection_url: 'https://${DOMAIN_1}'