apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tubesync
  namespace: tubesync
spec:
  interval: 15m
  chart:
    spec:
      chart: tubesync
      version: 6.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - tubesync.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: tubesync.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      downloads:
        enabled: true
        mountPath: /downloads
        path: ${DATASET_MEDIA}/temp/downloads/ytdl
        server: ${NFS_SERVER_0}
        type: nfs
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 4848
            protocol: tcp
            targetPort: 4848
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DATABASE_CONNECTION: ""
                HTTP_PASS: ""
                HTTP_USER: ""
                TUBESYNC_DEBUG: "False"
                TUBESYNC_HOSTS: ""
                TUBESYNC_WORKERS: "2"
                http_PASS: ""
                http_USER: ""
        replicas: 1
        type: Deployment
