---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mergerfs
  namespace: mergerfs
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    image:
      repository: hvalev/mergerfs
      pullPolicy: IfNotPresent
      tag: 2.40.2.2@sha256:2fe32b1d95b3a80b9b39f85684e56b8562a1c33d8787cb54f9c2f0ae92e591f1

    securityContext:
      container:
        privileged: true
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
        capabilities:
          add:
            - SYS_ADMIN

    service:
      main:
        enabled: false

    persistence:
      merged:
        enabled: true
        type: pvc
        accessModes: ReadWriteMany
        mountPath: /merged
        mountPropagation: Bidirectional
        targetSelectAll: true
      media:
        enabled: true
        type: nfs
        mountPath: /disks/media
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}
      overseerr:
        enabled: true
        type: nfs
        mountPath: /disks/overseerr
        server: ${NFS_SERVER_0}
        path: ${DATASET_OVERSEERR}

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MERGERFS_PARAMS: "dropcacheonclose=false,category.create=mspmfs,cache.files=off"
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false