apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
  namespace: calibre
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre
      version: 15.2.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - calibre.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: calibre.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
      webserver:
        enabled: false
        targetSelector:
          webserver: webserver
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      media:
        enabled: true
        type: nfs
        mountPath: /media
        path: ${DATASET_MEDIA}/library/books
        server: ${NFS_SERVER_0}
      temp:
        enabled: true
        type: nfs
        mountPath: /temp
        path: ${DATASET_MEDIA}/temp/downloads/books
        server: ${NFS_SERVER_0}
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 8084
            protocol: http
            targetPort: 8080
        type: ClusterIP
      webserver:
        enabled: true
        ports:
          webserver:
            enabled: true
            port: 8081
            protocol: http
            targetPort: 8081
        type: LoadBalancer
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                CLI_ARGS: ""
                PASSWORD: ""
        replicas: 1
        type: Deployment
