apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: jupyter/base-notebook
          securityContext:
            runAsUser: 0 # Remplacez par l'UID approprié
          args:
            - jupyter
            - notebook
            - --ip=0.0.0.0
            - --allow-root # Nécessaire si l'UID est 0
            - --notebook-dir=/data
          workingDir: /data
          ports:
            - containerPort: 8888
          volumeMounts:
            - mountPath: /data
              name: files-volume
      volumes:
        - name: files-volume
          persistentVolumeClaim:
            claimName: vikunja-files

