---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: recyclarr
spec:
  interval: 15m
  chart:
    spec:
      chart: recyclarr
      version: 10.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true

    # addons:
    #   codeserver:
    #     enabled: true
    #     ingress:
    #       enabled: true
    #       integrations:
    #         traefik:
    #           enabled: true
    #           middlewares:
    #             - name: auth
    #               namespace: traefik
    #       tls:
    #         - hosts:
    #           - recyclarr.cs.${DOMAIN_0}
    #           clusterIssuer: domain-0-cs-wildcard
    #       hosts:
    #         - host: recyclarr.cs.${DOMAIN_0}