apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omegabrr
  namespace: omegabrr
spec:
  interval: 15m
  chart:
    spec:
      chart: custom-app
      version: 13.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    addons:
      codeserver:
        enabled: true
        service:
          loadBalancerIP: ""
          ports:
            codeserver:
              port: 36175
          type: LoadBalancer
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 7441
            protocol: http
            targetPort: 7441
        type: LoadBalancer
    workload:
      main:
        podSpec:
          containers:
            main:
              extraArgs:
                - --config=/config/config.yaml
        replicas: 1
        type: Deployment
