apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbitmanage
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbitmanage
      version: 10.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    image:
      repository: docker.io/bobokun/qbit_manage
      pullPolicy: IfNotPresent
      tag: v4.1.17@sha256:16b92b1eb60a6bbb7a1e69d0d58b6cc7fa2608d5f391732212977ea4a01f69db

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 5 * * *
      data:
        enabled: true
        type: nfs
        mountPath: /data
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}
      overseerr:
        enabled: true
        type: nfs
        mountPath: /overseerr
        server: ${NFS_SERVER_0}
        path: ${DATASET_OVERSEERR}/overseerr

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                QBT_SCHEDULE: 1440
                QBT_CONFIG: config*.yml

    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          integrations:
            traefik:
              enabled: true
              middlewares:
                - name: auth
                  namespace: traefik
          tls:
            - hosts:
              - qb.cs.${DOMAIN_0}
              clusterIssuer: domain-0-wildcard
          hosts:
            - host: qb.cs.${DOMAIN_0}