apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbitmanage
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbitmanage
      version: 10.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      data:
        enabled: true
        type: nfs
        mountPath: /data
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                QBT_CAT_UPDATE: false
                QBT_CROSS_SEED: false
                QBT_DRY_RUN: false
                QBT_LOG_LEVEL: INFO
                QBT_RECHECK: false
                QBT_REM_ORPHANED: false
                QBT_REM_UNREGISTERED: false
                QBT_RUN: false
                QBT_SCHEDULE: 1440
                QBT_SHARE_LIMITS: false
                QBT_SKIP_CLEANUP: false
                QBT_SKIP_QB_VERSION_CHECK: false
                QBT_TAG_NOHARDLINKS: false
                QBT_TAG_TRACKER_ERROR: false
                QBT_TAG_UPDATE: false
                QBT_WIDTH: 100    

    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          integrations:
            traefik:
              enabled: true
              middlewares:
                - name: auth
                  namespace: traefik
          tls:
            - hosts:
              - qbit.cs.${DOMAIN_0}
              clusterIssuer: domain-0-cs-wildcard
          hosts:
            - host: qbit.cs.${DOMAIN_0}