---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maintainerr-restart
  namespace: maintainerr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-overlay-helperr
  namespace: maintainerr
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["overlay-helperr-app-template"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-overlay-helperr-binding
  namespace: maintainerr
subjects:
  - kind: ServiceAccount
    name: maintainerr-restart
    namespace: maintainerr
roleRef:
  kind: Role
  name: restart-overlay-helperr
  apiGroup: rbac.authorization.k8s.io