apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rtmp-hls
  namespace: rtmp-hls
spec:
  interval: 15m
  chart:
    spec:
      chart: custom-app
      version: 13.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - rtmp.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: rtmp.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    securityContext:
      container:
        UMASK: "0022"
        privileged: false
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 10610
            protocol: http
            targetPort: 8080
          rtmp:
            enabled: true
            name: rtmp
            port: 1935
            protocol: tcp
            targetPort: 1935
        type: LoadBalancer
    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  enabled: true
                  path: /stats.html
                  type: http
                readiness:
                  enabled: true
                  path: /stats.html
                  type: http
                startup:
                  enabled: true
                  path: /stats.html
                  type: http
        replicas: 1
        type: Deployment
