---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rtmp-hls
  namespace: rtmp-hls
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    image:
      repository: alqutami/rtmp-hls
      pullPolicy: IfNotPresent
      tag: latest

    service:
      rtmp:
        enabled: true
        type: LoadBalancer
        ports:
          rtmp:
            enabled: true
            protocol: tcp
            port: 1935
            targetPort: 1935

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
            - rtmp.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: rtmp.${DOMAIN_0}

    persistence:
      dash:
        enabled: true
        mountPath: /mnt/dash
      hls:
        enabled: true
        mountPath: /mnt/hls
      nginx:
        enabled: true
        mountPath: /var/run/nginx

    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  type: tcp
                  port: 1935
                readiness:
                  type: tcp
                  port: 1935
                startup:
                  type: http
                  path: /stats.html