apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: radarr
spec:
  interval: 15m
  chart:
    spec:
      chart: radarr
      version: 22.2.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}
    
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
              - name: theme-radarr
                namespace: traefik
        tls:
          - hosts:
            - radarr.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: radarr.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix
    
    persistence:
      config:
        enabled: true
        targetSelector:
          main:
            main:
              mountPath: /config
          exportarr:
            exportarr:
              mountPath: /config
              readOnly: true
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      media:
        enabled: true
        type: nfs
        mountPath: /media
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}