apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection-io
  namespace: changedetection-io
spec:
  interval: 15m
  chart:
    spec:
      chart: changedetection-io
      version: 3.0.11
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - cdio.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: cdio.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      datastore:
        enabled: true
        mountPath: /datastore
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 5000
            protocol: http
            targetPort: 5000
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                BASE_URL: https://cdio.${DOMAIN_0}
                FETCH_WORKERS: 10
                HIDE_REFERER: true
                PLAYWRIGHT_DRIVER_URL:
                  name: PLAYWRIGHT_DRIVER_URL
                  value: ws://playwright-custom-app.ix-playwright.svc.cluster.local:3000
                USE_X_SETTINGS: true
        replicas: 1
        type: Deployment
