apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - actualserver/ks.yaml
  - changedetection/ks.yaml
  - companion/ks.yaml
  - dell-idrac-fan-controller/ks.yaml
  - duplicacy/ks.yaml
  - flatnotes/ks.yaml
  - gostream/ks.yaml
  - homebox/ks.yaml
  - homepage/ks.yaml
  - immich/ks.yaml
  - maloja/ks.yaml
  # - mealie/ks.yaml
  - multi-scrobbler/ks.yaml
  - nextcloud/ks.yaml
  - projectsend/ks.yaml
  - rtmp-hls/ks.yaml
  - sftpgo/ks.yaml
  - shlink
  # - snapdrop/ks.yaml
  - speedtest-tracker/ks.yaml
  - splitpro/ks.yaml
  - stirling-pdf/ks.yaml
  - thelounge/ks.yaml
  - vikunja/ks.yaml
  - whisper-asr-webservice/ks.yaml
  - kubernetes-dashboard/ks.yaml
