apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stash
  namespace: stash
spec:
  interval: 15m
  chart:
    spec:
      chart: stash
      version: 16.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    addons:
      codeserver:
        enabled: true
        service:
          loadBalancerIP: ""
          ports:
            codeserver:
              port: 37999
          type: LoadBalancer
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - stash.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: stash.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      blobs:
        enabled: true
        mountPath: /blobs
        volsync:
          - credentials: backblaze
            name: blb
            src:
              enabled: true
            type: restic
      cache:
        enabled: true
        mountPath: /cache
        volsync:
          - credentials: backblaze
            name: cch
            src:
              enabled: true
            type: restic
      config:
        enabled: true
        mountPath: /root/.stash
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      data:
        enabled: true
        mountPath: /data
        volsync:
          - credentials: backblaze
            name: dat
            src:
              enabled: true
            type: restic
      generated:
        enabled: true
        mountPath: /generated
        volsync:
          - credentials: backblaze
            name: str
            src:
              enabled: true
            type: restic
      metadata:
        enabled: true
        mountPath: /metadata
        volsync:
          - credentials: backblaze
            name: met
            src:
              enabled: true
            type: restic
      media:
        enabled: true
        type: nfs
        mountPath: /media
        path: ${DATASET_MEDIA}/library/porn
        server: ${NFS_SERVER_0}
    resources:
      limits:
        cpu: 72000m
        memory: 32Gi
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 9999
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                STASH_CACHE: /cache
                STASH_GENERATED: /generated
                STASH_METADATA: /metadata
                STASH_PORT: '{{ .Values.service.main.ports.main.port }}'
                STASH_STASH: /data
        replicas: 1
        type: Deployment
