apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoogle
  namespace: whoogle
spec:
  interval: 15m
  chart:
    spec:
      chart: whoogle
      version: 11.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - search.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: search.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10052
            targetPort: 5000
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                WHOOGLE_CONFIG_ALTS: false
                WHOOGLE_CONFIG_COUNTRY: Canada
                WHOOGLE_CONFIG_GET_ONLY: true
                WHOOGLE_CONFIG_NEW_TAB: true
                WHOOGLE_CONFIG_SAFE: true
                WHOOGLE_CONFIG_STYLE: ':root {--whoogle-dark-logo: #cdd6f4; --whoogle-dark-page-bg: #1e1e2e; --whoogle-dark-element-bg: #45475a; --whoogle-dark-text: #cdd6f4; --whoogle-dark-contrast-text: #bac2de; --whoogle-dark-secondary-text: #a6adc8; --whoogle-dark-result-bg: #313244; --whoogle-dark-result-title: #b4befe; --whoogle-dark-result-url: #f5e0dc; --whoogle-dark-result-visited: #eba0ac;} #whoogle-w {fill: #89b4fa;} #whoogle-h {fill: #f38ba8;} #whoogle-o-1 {fill: #f9e2af;} #whoogle-o-2 {fill: #89b4fa;} #whoogle-g {fill: #a6e3a1;} #whoogle-l {fill: #f38ba8;} #whoogle-e {fill: #f9e2af;}'
                WHOOGLE_CONFIG_THEME: dark
                WHOOGLE_CONFIG_TOR: false
                WHOOGLE_CONFIG_URL: https://search.${DOMAIN_0}
        replicas: 1
        type: Deployment
