apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: lldap
spec:
  interval: 15m
  chart:
    spec:
      chart: lldap
      version: 6.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    cnpg:
      main:
        backups:
          credentials: backblaze
          enabled: true
        cluster:
          instances: 2
          singleNode: true
        database: lldap
        enabled: true
        monitoring:
          disableDefaultQueries: false
          enablePodMonitor: true
        password: ${CNPG_PASSWORD_LLDAP}
        pgVersion: 16
        user: lldap
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - lldap.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: lldap.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      data:
        enabled: true
        mountPath: /data
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      ldap:
        enabled: true
        ports:
          ldap:
            enabled: true
            port: 3890
        type: LoadBalancer
      main:
        enabled: true
        ports:
          main:
            port: 17170
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              args:
                - run
              command:
                - /app/lldap
              env:
                LLDAP_HTTP_PORT: '{{ .Values.service.main.ports.main.port }}'
                LLDAP_HTTP_URL: https://lldap.${DOMAIN_0}
                LLDAP_JWT_SECRET:
                  - secretRef:
                    key: LLDAP_JWT_SECRET
                    name: secrets
                LLDAP_LDAP_BASE_DN: dc=${USER_10},dc=${DOMAIN_TLD_0}
                LLDAP_LDAP_PORT: '{{ .Values.service.ldap.ports.ldap.port }}'
                LLDAP_LDAP_USER_DN: ${USER_10}
                LLDAP_LDAP_USER_EMAIL: ${LDAP_USER_EMAIL}
                LLDAP_LDAP_USER_PASS: ${LDAP_USER_PASS}
                LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: false
                LLDAP_SMTP_OPTIONS__FROM: LLDAP Admin <sender@gmail.com>
                LLDAP_SMTP_OPTIONS__PASSWORD: ""
                LLDAP_SMTP_OPTIONS__PORT: 587
                LLDAP_SMTP_OPTIONS__REPLY_TO: Do not reply <noreply@localhost>
                LLDAP_SMTP_OPTIONS__SERVER: ""
                LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: STARTTLS
                LLDAP_SMTP_OPTIONS__USER: ""
                LLDAP_VERBOSE: false
                LLDAP_database_url:
                  secretKeyRef:
                    key: std
                    name: cnpg-main-urls
                LLDAP_key_file: /data/private_key
                smtp: false
        replicas: 1
        type: Deployment
