apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 15m
  chart:
    spec:
      chart: stirling-pdf
      version: 1.36.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    image:
      repository: nktnet/s-pdf
      pullPolicy: IfNotPresent
      tag: latest-fat

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - pdf.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: pdf.${DOMAIN_0}

    persistence:
      configs:
        type: emptyDir
      custom-files:
        type: emptyDir
      tessdata:
        type: emptyDir
      logs:
        type: emptyDir

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DOCKER_ENABLE_SECURITY: false
                SECURITY_ENABLE_LOGIN: false
                INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
                UI_APPNAME: Freeman • PDF
                UI_APPNAMENAVBAR: Freeman • PDF
                LANGS: fr-FR