apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 15m
  chart:
    spec:
      chart: custom-app
      version: 13.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - pdf.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: pdf.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    securityContext:
      container:
        UMASK: "0022"
        privileged: true
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 8080
            protocol: http
            targetPort: 8080
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DOCKER_ENABLE_SECURITY:
                  name: DOCKER_ENABLE_SECURITY
                  value: "false"
                SYSTEM_CUSTOMSTATICFILEPATH:
                  name: SYSTEM_CUSTOMSTATICFILEPATH
                  value: /customFiles
                SYSTEM_DEFAULTLOCALE:
                  name: SYSTEM_DEFAULTLOCALE
                  value: fr-FR
                SYSTEM_GOOGLEVISIBILITY:
                  name: SYSTEM_GOOGLEVISIBILITY
                  value: "false"
                UI_APPNAME:
                  name: UI_APPNAME
                  value: Freeman PDF
                UI_APPNAMENAVBAR:
                  name: UI_APPNAMENAVBAR
                  value: Freeman PDF
        replicas: 1
        type: Deployment
