apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soulseek
  namespace: soulseek
spec:
  interval: 15m
  chart:
    spec:
      chart: custom-app
      version: 13.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    addons:
      vpn:
        env:
          FIREWALL_VPN_INPUT_PORTS:
            name: FIREWALL_VPN_INPUT_PORTS
            value: ${FIREWALL_VPN_INPUT_PORTS_7}
          VPN_ENDPOINT_IP:
            name: VPN_ENDPOINT_IP
            value: ${VPN_ENDPOINT_IP_7}
          VPN_ENDPOINT_PORT:
            name: VPN_ENDPOINT_PORT
            value: ${VPN_ENDPOINT_PORT_7}
          VPN_SERVICE_PROVIDER:
            name: VPN_SERVICE_PROVIDER
            value: ${VPN_SERVICE_PROVIDER_0}
          VPN_TYPE:
            name: VPN_TYPE
            value: wireguard
          WIREGUARD_ADDRESSES:
            name: WIREGUARD_ADDRESSES
            value: ${WIREGUARD_ADDRESSES_7}
          WIREGUARD_PRIVATE_KEY:
            name: WIREGUARD_PRIVATE_KEY
            value: ${WIREGUARD_PRIVATE_KEY_7}
          WIREGUARD_PUBLIC_KEY:
            name: WIREGUARD_PUBLIC_KEY
            value: ${WIREGUARD_PUBLIC_KEY_7}
        excludedNetworks_IPv4:
          - ${EXCLUDED_IPV4_0}
        killSwitch: true
        type: gluetun
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - soulseek.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: soulseek.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      downloads:
        enabled: true
        type: nfs
        mountPath: /media/downloads
        path: ${DATASET_MEDIA}/temp/downloads/soulseek
        server: ${NFS_SERVER_0}
      shared:
        enabled: true
        type: nfs
        mountPath: /media/shared
        path: ${DATASET_MEDIA}/temp/downloads/music
        server: ${NFS_SERVER_0}
    securityContext:
      container:
        UMASK: "0022"
        privileged: false
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 26080
            protocol: http
            targetPort: 6080
        type: ClusterIP
    workload:
      main:
        replicas: 1
        type: Deployment
