apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  interval: 15m
  chart:
    spec:
      chart: speedtest-tracker
      version: 6.3.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    cnpg:
      main:
        mode: recovery
        password: ${CNPG_PASSWORD_STT}
        cluster:
          singleNode: true
        backups:
          enabled: true
          revision: "2"
          credentials: backblaze
        recovery:
          credentials: backblaze

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
            - speedtest.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: speedtest.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                APP_URL: https://speedtest.${DOMAIN_0}