apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  interval: 15m
  chart:
    spec:
      chart: speedtest-tracker
      version: 2.1.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    cnpg:
      main:
        backups:
          credentials: backblaze
          enabled: true
        cluster:
          instances: 1
          singleNode: true
        database: speedtest-tracker
        enabled: true
        monitoring:
          disableDefaultQueries: false
          enablePodMonitor: true
        password: ${CNPG_PASSWORD_STTRACKER}
        pgVersion: 16
        user: speedtest-tracker
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - speedtest.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: speedtest.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
    redis:
      enabled: true
      redisUsername: default
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 9004
            targetPort: 80
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                APP_KEY:
                  secretKeyRef:
                    key: APP_KEY
                    name: speedtest-tracker-secrets
                APP_NAME: Speedtest Tracker
                APP_URL: https://speedtest.${DOMAIN_0}
                CACHE_DRIVER: redis
                DB_CONNECTION: pgsql
                DB_DATABASE: '{{ .Values.cnpg.main.database }}'
                DB_HOST:
                  secretKeyRef:
                    key: host
                    name: cnpg-main-urls
                DB_PASSWORD:
                  secretKeyRef:
                    key: password
                    name: cnpg-main-user
                DB_PORT: "5432"
                DB_USERNAME: '{{ .Values.cnpg.main.user }}'
                MAIL_ENCRYPTION: SSL
                MAIL_FROM_ADDRESS: ""
                MAIL_FROM_NAME: Speedtest Tracker
                MAIL_MAILER: smtp
                MAIL_PASSWORD: ""
                MAIL_PORT: 465
                MAIL_USERNAME: ""
                PUBLIC_DASHBOARD: false
                REDIS_URL:
                  secretKeyRef:
                    expandObjectName: false
                    key: url
                    name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                TELEGRAM_BOT_TOKEN: ""
                mail: false
              probes:
                liveness:
                  enabled: true
                  path: /api/healthcheck
                  type: http
                readiness:
                  enabled: true
                  path: /api/healthcheck
                  type: http
                startup:
                  enabled: true
                  path: /api/healthcheck
                  type: http
              securityContext:
                capabilities:
                  add:
                    - SYS_CHROOT
                    - KILL
        replicas: 1
        type: Deployment