---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-maintainerr-overlay-helperr
  namespace: maintainerr
spec:
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: maintainerr-restart
          restartPolicy: Never
          containers:
            - name: restart-maintainerr-overlay-helperr
              image: bitnami/kubectl:latest
              command:
                - "/bin/sh"
                - "-c"
                - "kubectl rollout restart deployment maintainerr-overlay-helperr -n maintainerr"