---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dell-idrac-fan-controller
  namespace: dell-idrac-fan-controller
spec:
  interval: 15m
  chart:
    spec:
      chart: dell-idrac-fan-controller
      version: 7.3.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_IDRAC}
        ports:
          main:
            enabled: true
            port: 80

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                IDRAC_HOST: "${IDRAC_HOST}"
                IDRAC_USERNAME: "${IDRAC_USERNAME}"
                IDRAC_PASSWORD: "${IDRAC_PASSWORD}"
                FAN_SPEED: 70
                CPU_TEMPERATURE_THRESHOLD: 79
                CHECK_INTERVAL: 60
                DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE: true