apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: taxhacker
  namespace: taxhacker
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    cnpg:
      main:
        enabled: true
        cluster:
          singleNode: true
        mode: recovery
        database: taxhacker
        user: taxhacker
        password: ${CNPG_PASSWORD_TAXHACKER}
        backups:
          enabled: true
          revision: "2"
          credentials: backblaze
        recovery:
          revision: "1"
          credentials: backblaze

    image:
      repository: ghcr.io/vas3k/taxhacker
      pullPolicy: Always #IfNotPresent
      tag: latest@sha256:d3f835984949ea16d2da42d3bcfcf2e3d5e2a2a8610c9b17ff6e7bdcb807c478

    service:
      main:
        ports:
          main:
            port: 7331

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - taxhacker.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: taxhacker.${DOMAIN_0}

    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /app/data
        targetSelectAll: true
        volsync:
          - name: dat
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: false
              trigger:
                schedule: 0 3 * * *

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                NODE_ENV: production
                SELF_HOSTED_MODE: true
                UPLOAD_PATH: /app/data/uploads
                DATABASE_URL: postgresql://taxhacker:${CNPG_PASSWORD_TAXHACKER}@taxhacker-app-template-cnpg-main-rw:5432/taxhacker
                OPENAI_API_KEY: ${TAXHACKER_OPENAI_API_KEY}