apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: vikunja
spec:
  interval: 15m
  chart:
    spec:
      chart: vikunja
      version: 16.0.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    cnpg:
      main:
        mode: recovery
        password: ${CNPG_PASSWORD_VIKUNJA}
        cluster:
          singleNode: true
        backups:
          enabled: true
          revision: "5"
          credentials: backblaze
        recovery:
          revision: "4"
          credentials: backblaze

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
            - todo.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: todo.${DOMAIN_0}

    persistence:
      files:
        volsync:
          - name: dat
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *

    vikunja:
      service:
        motd: ""
        frontendurl: https://todo.${DOMAIN_0}
        enableregistration: false
        enabletotp: false
        enableemailreminders: false

      mailer:
        enabled: true
        host: ${SMTP_HOST_0}
        port: 587
        username: "${SMTP_USERNAME_0}"
        password: ${SMTP_PASSWORD_VIKUNJA}
        fromemail: ${SMTP_FROM_VIKUNJA}

      defaultsettings:
        timezone: America/Montreal
        avatar_provider: upload
        language: "fr-CA"
        overdue_tasks_reminders_enabled: false
      backgrounds:
        enabled: false

      auth:
        local:
          enabled: true
        openid:
          enabled: true
          redirecturl: https://todo.${DOMAIN_0}/auth/openid/
          providers:
          - name: Authelia
            authurl: https://auth.${DOMAIN_0}
            logouturl: https://todo.${DOMAIN_0}
            clientid: ${OIDC_CLIENT_ID_VIKUNJA}
            clientsecret: ${OIDC_CLIENT_SECRET_VIKUNJA}

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                VIKUNJA_SERVICE_CUSTOMLOGOURL: https://freeman.art/vikunja.svg