apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PP1GYfOA3Vf+T7OW6p88mPSIhZp3xFNznCaFm7RiaE03gYpHIVzeIGc276cM/XXbHOS1z4atiuAL0FvsKR6t4j381NvAm8O+yrKfPj967KK2YIVWZRLfeZV2uumP3Khzo4OJFZfmPmxuWR9vFhTXaRh974F9+SsLEzpy70UauELfv7BJFldKSNMLjx0i2KMS3CQmzdUilrBebbDhkt1GyicCFe9MRtsFE6DLPmukyLnrGoogTlSDzVM8LGqdNJFg5oNRicJgPp9CKEoGSgP3+ToFRb4QAR2Kct27x/KEnDJOFhqDEb6tuQYMCujQCwCUCr9XCsN/uu8PqUmNY2+fBQTwkKZDIgZ8auxO/Ol4LtHnNzJiaunSzYE7+HhzSwyW,iv:fz3Jq6m7JSGVpEMtsLCsj4SPqgyEks6hQDLmkG7Kfl8=,tag:pM0ny9e4K43xsZbmgx6OSg==,type:str]
    identity.pub: ENC[AES256_GCM,data:XM+thkOSAOOzD66j4nvACDZtxRczKLR3ay39xY47pVTI15yvhFmx83gkkFnIMwgQzr24dgQdz29XErUzdEwCMimBkcUIx2Cm6eAmCmPC5PhMjrzoOE+mIQ8RPmlHtk13xv5uoDqVunRVHsfC/y2AfkWPvgc9YWfhCOf0z+ApLYwDDkFVfWXNCYb+ZKWFarb4ts31elUScdaZZx36evRD1O1OtZubVACAyPk4cB0tsgRjNNBACZG1eSrBV+4nuqa4MBxqCPJARctUaTqTWg==,iv:nRLFj9+qj5LLTzgHGlFEUX4cEXdGQqSefIlWLUBXwes=,tag:i8HTc63yeGnEai5QC23FWg==,type:str]
    known_hosts: ENC[AES256_GCM,data:R4yUO8wKX3sGaBiCWwHhO8cyE68xfmIkjlJbqX4VzyFC552kAhVA6Y6M4AZ/ta5615qgcZK/F/Hptjkmtb2f54Zy+Big9TBIX/4ox6Eg2hkwzRijL4zMdohL42GGVsbjRACk195eSTwPsok7rITGwQO2xWwmSSuhVeXsi8B96z9CG3jSjso6Xd/dMjDrH/+8Pqk4o9KKZgQhaZEkkhylzAF6MJUF2FA8y0l+,iv:pB38uLFYANBOMq6pypOmL6hQnyJNczOyEdR1eJTjVN4=,tag:pcQ+oBc65KlS1UtAFFAuIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UjFDY3FsNGdBb2o2ZDVE
            czliM3JTcjIrZVZZaW82TUIwUlIydWVQc2trClloQ0FKOWZMU2Z5dDZzMU9lMjlP
            QzJ6N1JVb2ZJcm9IWndRN29hVWh1RGsKLS0tIHZuTmNmd2hBbGRhc1pWbnA2YXZT
            QmlLMmhRcmtPRWVIbTVaUnkzb2ZXN0EKPLVitodo38QQX10t0VM6ShytbtwnK0VG
            fBMd0HCtx0FHhGS9Mbep/0Kxh7dlmCqth+2C1Cf5kuwkxt8LmnB3WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T02:32:58Z"
    mac: ENC[AES256_GCM,data:4VLbUu1NG1HUhe8AAUIP2DtFhUdzl1uKgZ5JmQEVaKgFFZXGUNsajkqVGnHeinJ0LlnRJYgDHYZzRhnlIz91EsSjD30kMUa6iw53AKr/uV3NFJCvBODNU5cVK+yp4AZ8iE50q88KXGmpetEffEisy3zqV3137Hme4yBDYwII9jw=,iv:tVIbAFUQp7uKOmCxh2kTmMDVJCJsGnyr8cK8ZnOn8lM=,tag:O9gWoxFeLqLiRoJ1jYdALQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
