apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:t8kD3jARRoj+2s5eq+X/Fb3sPJHd+fqnBtlKQMFaayRDTp6E+hxorrZMYWXC2e9VUFgvBf0wbvl6fw9EPUD/+p97Re7GhE8CGJiSSWxEXoieHj+FiJr9ZO6JZVZRhAetVOzBfviKDWmCOQVQ9J/NHbIV8zC57HSklDjEJ2g2tsPVSBdBvh6zJUBwWlYvRJNqxxbvN7SBKrlTPL3PaHgYQ2Rhyf1vXkFF+ThzZRDnhMtvofzzrN6Eq59xrM0KGDzWmAR1zgBZQV6ZAjG2Dc4g9qOvlNxcblER0ABCEoc+/8z8pinQqJHU8uHhCF7k4ztJug0yzuME09LpHG+LrE7cbWAyQuxB8FwllySUDqkbZmgj8eSaG3BV+PDaQo7sDlQ3,iv:vcw8eMEtJQrOTtcDVpQnhCgSA1LHIbQQ/xp7yFUNaSc=,tag:Ya2HrZkfmvWbAFx/QDuPhQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:IUx6sJSmvml+UJsWwpXWS2GqHJkD5GE7s0SxdXu0NEPv4kngsbnd8OCan8gphUzGKOSP6pT58zaIr7bmHW+6UvARat2Uaq6cxnPPPAfblBNGiRDckza8K7sLRWZOBeDwjy8UoxjxubRePe8SmxBq3PVJ1+eAptklDmBG2zqVud6Oe2tGyfRJbzCBbp5KT0IolEsD9xCHP3FIPQudjie/PwEGLmywnsqfRiUMThMiuM5iST+EtwgrH+szMIHRns1cx1NPQ/ZFHIK9dJjzpQ==,iv:4cblFseDfSg04fnDXS8XS3NFC7ojuB3fMR3H/OhC3Wg=,tag:amFK9VW5HI3Jb4nVFbqLRQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:02GZQSvDzE+R1TQkAq+fG0YbPF1/ZYZIyOVu8Bs6xzqr5OtFTmYRM0zjo3SdjrmJoZRfS0o92NajQ/+Nm7gteyQeDw7OwD7fuNArU36Ii22nvU+bfXTjCVhezBQ7r73aW1znMmDz8aYZ826IdGuayt2x2l/7dzmhSaqKlV7eVUMU/gC0Mqe5yfjAdyQCeUJb3AoJ/kleBeKMre8Hlbl+lLSDT8SUoJACeHfm,iv:nqiDh7xmLczq5ThpGffiUgQwuh/ho18BnK/Z7q0NzVA=,tag:wcFdyniZqNmFDIhmYdI0wA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdS82ZlU1NklGbnhwZlJ5
            ZDg5eTgwQkNvelVoVkVTRjQvVDUxUVpUZjBFClg1TVkyUFpwL3hsODBPZDFQYmZB
            QjJ2RmlRWGtYNDBRU2NqbC9INXp5TXcKLS0tIC83U2RWTC8wVGRZVytvaEY5b3Iv
            SWIxeS82czgySHloVmVHbkpqb2doSzgKp6buBN6vSKXWl6NXXMl26sn+hdMcyxR9
            YGGI+ADfX1H0zbD3+2M2eLhWn857wl8gnO2HbeRy6RlEGijWNqANsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T00:46:57Z"
    mac: ENC[AES256_GCM,data:7Oinsj5qxD4mmT5nrvXMU/M+AIj1+EAdhN0SrFL/0aN94sSYA7JTrhzpENe2YyXgdo/ic7gIjUbWpjzOvpMKCcGTTyRlhDduUxGYwr2doDMKAIKZE8jKrKe5xO1qVcCYIHAZKvUljp/2WYiQ57GVgFGz2vbJV9q5hUpFsGMzeNw=,iv:RgdGuydhas+pQQ+JFxpo4/u2+dzJRy2OzTDcw/T0X8Q=,tag:8k1dNJuYwaF7i0brKv4lng==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
