apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ax4iiT39wugXUD2aK+36YxGM6ZtEXmoH4PZEP8wESbKQNQps4a0OBfq1tdct3VQcAQ/l/kjDQyorR/0FoadRaJpjIoFYNUEXhA2ta7uCMO//pS3GLRtDseqZbaPH7H8ru5AxT5dzo2+zW67A6M0TH9VHguCe0T5rC4ympsT1emn6XonvXlIeP4P+4TAXlBZSVo8soRvmZP1gTa3VRinlGXHY3bMaeRFj0BmHzGxbm+JG2nsdOZnCmx1scgjfKKFGpEsJNPdPwjkRQHYC1qkRia8LB2qau5ayBLwQtygA8Jy9rhSkgMDOeEdBgdduAHjNn5Mya4cpDbJs4ReEQX3VePLHZzux1r41Hu1wUWYlaFiF8/1QMvyYWFFc8Cr7pbd3,iv:HlSt9j7s+cIrZEIyIlCnqBAcRlTigb4OCYolCS4X5B8=,tag:RyOfqTPjuBQPXkuWrSZNGg==,type:str]
    identity.pub: ENC[AES256_GCM,data:xuZfNnEPqr2z/IRX6cOQKJiwT/A8zKWmgBx/BsYv7RJHEd6dc6oPBSCoLwHef6NGFj3en7cpupTAS6+zwemGZPPI38daxG764408bl4o/IRlbQBjpK6jdRLKt5fl47fGy8KTtE8WsPZSW4J3K4fGVV89FpCDjp+VK3zJhSgdhhFCF1TmczMKFu7AXSG0hRNuwE2dCUfhAn8h4nybmS+LwkJKH/xZpgVociCmSk02OlrUYZzpPAuRqbmtBCZyj7mbd/3QW5eGiZ5qRothDg==,iv:zrHDl9/zYMlpYOMgHPngC1lHfqQy36gxHlRcQ7qoegg=,tag:MWzNuCKHjNUhDf90AQ7tuQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:s7UTYa8ry90kMkwBG6wEbu128p68uYMpgk/DawgNhcc7PhzhlaT4K4X7+RPANT/Qs7T9w/aT6Qbhk5HS1Q+kTBY1dZ4RLqNbTTtL7aVH4rpXz1wRu3T5ydnzTCiRWRiblniK6PDyIiV4KkonW0u6t+fOWFu0WanGeXYbC8h7+RxUepTRm7bySxKcD+RR+QAR1oVC9wJdZPaCTuFMXEGFtbZemQ9TIiDgVjgp,iv:ZStmRl4iPlgTBzgO4cLYx+PNJ6WTufioADABVAHq/PU=,tag:TscnUol/VNllMjD2iwmuMQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVUxGSkFHdjhsOGs0MERR
            MktNU0NDL08zTHVpYVVzZkxXRkZkcVZvS3dNCjVOK3NBNVJUenZYUExYbWxFVVNH
            UmV4R3AveGhybmNZbjRZOWdtVVZ5RTgKLS0tIDIzWmhvRXpFdkR0R0tyUFQ5Qjhp
            V0ptUE1rL0JWS21KcmZtaXZDUzhUQkUK7JYd3ChcKUgCaK6lq0BSdTJuccJt5dUm
            d+c7f2FO5+MMz8td5fP8rm3/sNvGNfTiYIWIpd3AJwX35YGbROpOYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:28:05Z"
    mac: ENC[AES256_GCM,data:y+xD7/DArQnHWxivdtTVgFtbag0IjxXL7jVSDwsh2DiWJ6CwIB3xT9Ozl150HobFa+OjwIJD0McUmlaK+kcyYtqd1JBoMmpuSD/yeRb7RCGLMV5NXJYdf7+p+pgavXxeZ90ycrWsiA5+1acmoR0/p78cCd6QMmtAnx5pvVDPGPw=,iv:roxG0J+1CpoxlasXe+MIJ0XZ1g8fep7FzPsSC1L0rro=,tag:v9ewh8g3DylnSUpmfMBFZw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
