apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RXQWgZqmRC9cPvQh6Q16CN1IwNV2zTIbyVlBZ8yDvDQJfdk+vHZNETL+4Aqv18fBpjBrDuI60tXr+jas2deqjuibCix+QCZcnB+43jLglv4qCeBG4DODO3d/eB6dLQyeX7Vg60YZoajYxFaz7qJ7oHdZAHv7agEIniDNbL1+YNL0hRyv+Shog+175Qa7zXMQUXIXUJP1GS9kA0gcMOzh5xVYtgJN4QxR//AJq2j39P7E5rmW+r3DAnySFvztUjUzQblJlFJlLEJy1utn3TGsFA1qnizKPa0mnRSm7LLJqUdD3WUxHiObeSs5rnyDGKxyxIFcZaggSdmn0D3NJkK/6h05/pGMVhlivFgxPyQmvbPm+hxd7VPSWyuSid0h2DP7,iv:0qimcSYsewffn2BoZCw21x8BtzZ8T8Rnbgyz/Xo4DDA=,tag:PatfSEGNx3cLRFQbLNpSog==,type:str]
    identity.pub: ENC[AES256_GCM,data:n/bK+R6JdZUV1jOI1rKYc5az7bNP59VkvVKjI2eX/ZZJlnaOKDcK6/D+uvoJdapzhw0bhY5BEsV/7X4gUZz4kKm0emHgFTWZPnBWr+4k4RqLtekxRyZaNshKhHi+xKC0vQ0kWZSyUWJ0vO4l2en18qGjJDa5MMln69LD3KlHgXEE+vvVw45Af4v6bWb2B8rPFF32+xcBZH+aGUgvYUPOzIinQBVf1ZYzSDfd7EO/6OrDyVT8M2tZ3oykpfpcHy38lw1rmiE8djdjPO+U1Q==,iv:ViUprTGkyumRZK8ihjGPRyjlJGthtLCPEeV6dO5OR2A=,tag:W4bshxtee2B9o9gK30F77A==,type:str]
    known_hosts: ENC[AES256_GCM,data:njK6kJ3UAyRDHlErWHK66Byhr/09nAwxCo0cc1j/hwisEEzV+va6zAKaGOFwmFej9VBNihWgD/X2JjVb4/kUXi/+LKfSsxnDG4ib9VAgeZ84GLsrd87jKZ1womTOKPeUpwo9F/huoAA1VLwVVbE9g1o2B7QAvEbrSLiTtI81m1luo66DxhW1KZrTzk/Uio3P0iJK5ZTxdfWgWXxZNMAYFabClxHu3HL5mhcR,iv:MQCss9PcQGEocr0mXFr53QERgsPMSEHVpIIzAln+lTI=,tag:b+ZDhuv/OEwpBhm/3z1wNA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaC9NN1ZJNzNkZmQ1WGN1
            RVJzNGhuUURnZE5IYmVIckNIdFpIRGFCLzJRCnNqWGxicEJDOE9SLzhHSDEvWmJn
            VDR0KzEyWDhLUmhrblZnMDdjVmcyb00KLS0tIDhSYy9NbnpoMzY2WmtrMnJ3czRY
            N3J3ZWRmMHl6bzNwNWFLVTdBc1ZERjQKyifUmzisurHr+4BAoCw/qaFMc9VcADAd
            apc02vwEiOqzLYfUtRe2z8C1hfpnRC7WUzLN+glcjVcnNiyw8dI20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-10T14:21:19Z"
    mac: ENC[AES256_GCM,data:ggARjylDjtI5n7ksvugGm69eRp7JfEwEwMD7cI1P0+KE/ngA0Uu6ALSReEgcbq9PJCVeMNXLTmRdKRg5iLO+l3iB8DKcXkD9HhI/jIFgakrY3TP2JyKo6NSD8MMZh2e4NHqgbev0+V3J/VeUjo46Vr2+Lv35qUHyzPir58rPmro=,iv:teLyVtZi+vLy7s4duQG7f11VKqWrZEOplh/Mrare+0g=,tag:X6rCe1CgQ7C/+Za2WCDqAg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
