apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ni05AcKsA06HFTgWzVVZGxiC/2zGLve2jwIbphvNchakU0dioYyWPypqiklG6GcxYVOxVViZHy5CLLv/BBxaCnQvOjXUIdQHxjNXQB7Dd05eMJtgHuqEACPSI1ZDcU4ULShBIag3OfTmQy+/IyK18NSXtY6UK96AHpcVb6UPRhXD9VgsWh+SVhEwA9wpOD2vTZpQZSRxypBDHFKrG+VPX82gMJTueleFucw5pUYD64cIdtUpqqtRwe2RHOlvquUeQA+zQskbNPV8BJIURHUQUOy78bekf42ECk0RwpxZZCweMKmqDzN5k0Hex/27jKYTeumNdgiTKBBzwG9L5W9wbsVql2/WMWLp7cgJHkiD1V3rLGabPBpXcGQOa/uRA7lr,iv:4S1wZ5nlq4YWWIupQLCObT8kNKc4SxHyspyI69bYddI=,tag:SlZ5f+nM/z8iLkPaApNjHQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Lny3eA8ygpfYcBe47nfHHSO5Tq/sy3ky7mRAgGJ6rTLLvP9myvqpbxr1qFaodAp0HYRLy5lci1ZyafKeTKKwxgC7oQf6BfT+KFZP4tnEZlsgCLwThxgqHqELHFVFgb5aQR1hfOQeSoh3Cu/S5SqBUeh2JPcLyzLUQCHma7zBY/6dU2DY4u4nABqNcRVYmGPWD6UXazIUjfyGeg1Ygtnsdcow9quJYN7Jjv2DjdjnRBXp+u0NNvUldhesTy2cUXfEfGok6cBG6i4/k5o2Ug==,iv:dAUd6hq+KOQBpvGXPlrb7KJmb2LfcvmBStU8DTXrpps=,tag:PGB7jUNPSOQLpLU+kp1B7g==,type:str]
    known_hosts: ENC[AES256_GCM,data:b2rOa1qkjMMsMgjOyl3NP2F9uxRhoPAjNncFH4ZU7mkTnWZMVoWUb7whn40RSurF6Jps+/+F8A187/ylcako5mQEN0hGiq2WKxL9N57OlB8CYUGQFUoV99QLPsZmqeYEpSHqfHis0cLZ1KRI8cJtPjbBeyHgWY9gkAORxiVCvZN6i/CbMAGgZnUZYAxCPCFR4cSpjAlrw/2tFsRSAIWSQnXUPBDl4ye+CBRA,iv:xYcW8lQXnLxSHAXnFZZ3pdlJZZUWmeBA2DjlLrqFC8k=,tag:YH1o+rFipeJtEIL+a/jVsQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR2tocFhyb0QxYko5cGtR
            bWp6S2NJelBERUZNb0JIQmtOUWJKaGkrcFQ4CjQwcU4xM2hWKzhHN00yQktXVUJ3
            a2YycVdiL1NZTFd2VXFYQmJmdzhXL2cKLS0tIFh6UURiN2VaOXNqc3pOQlU3eEIy
            OWliVjRvTGtvS1JXRTB2bGxVc1Evc1EKYgQElemZ7/BRRt0iA3zk+NZrcijqCai+
            xFSY3A3rN92ObavJKzkf88Lb7TcN7je4w3u6xapUgYonhLH74IpGDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T02:12:07Z"
    mac: ENC[AES256_GCM,data:sC88F5jKlkSbPSH6Jvn1GrpAy7KyQ+HbcVr1a9fAZs+VnZaB4NWVnqGcONZJ+BcxPTCnK2s0ugcFxBt81HPgUooAt6dInWV32lO4StmPTt9RDJZDiYh+DEFnJt5dug16Wm1daZzUwlShd+HUBw8jizutfNl5y09Ia95ZZtPTtP0=,iv:vQj7fAAvoRhMn+kyLZfSvmvLb8DCjoJ3ZV6X1bH0xkw=,tag:F90r12y4qmK11Hx3JLoU0g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
