apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OntfSzbtKSoRaqnejQUpyNj5xY1PiQ1sdIXon/evXRbeZxOHFMiZRoqtvlaRdjUphO99yemcwpGcV4c8vRw8J49qPc483+BXegqOjZ4QAntxFp3hJHQmL/fyLaGVp+Sov9EnadltTKpNlAhAm8FQorH28T8Yek4onMaJ8g32AbIvxUpWga7uE9qWbDPE2Uyzg2EYSvYQ21nBn3GL4w43uS3ZBfRVsd7YiQH9++i/BgT/mPmFL39Bzkw/PNFFDFoXUORjdEKe+dsr4tFIilSTiKaVH4a++S8tT4JTCtfiRPzbDYGEZ5gQupyUoRt6jQ3mrG4m6O0I/rBjlkl+L9cJ2f+PBnASEvPuppT3xf3TCaX6JcSV/bC7zRZznyFzNcTH,iv:MfFnbuYYszNFCnrUL99k0+H6REiC9d8FZaEmGtTPZ1g=,tag:Msn6mbQXgQrcrn6qnjuWZw==,type:str]
    identity.pub: ENC[AES256_GCM,data:LPTtkRruZYascaru1R6ogv1fuowJb38eNgdSotWPsKKwOtI2KXlCL5RB0eYNQ6YubfW7o+L3o952WRVDJhEP5aGGkkUeJivk+up5ilrrpKbpyaNFQsvNpiZQc840cAhOuVyuABscu5VM6dUlUoszXVeKP8WYmYseCfKmZzShrJ1taqJSet8uG5dUU6EZxMprdLxmdVWrXVvwptYopSq03gLRs3LT7tpuqFBkCrPkYgLM+5I3fhdjhQLZ5mOBQGDzfN1Tvs8jlQEidsIRaA==,iv:mxVFABP+8izzOVa4YLlQQMxt4fqStsTQgwUiMS05dJ4=,tag:/2JjA83oNaO+V2Pn2VH5/w==,type:str]
    known_hosts: ENC[AES256_GCM,data:PiEwXrgQ9vWYhpm7p9aWe9lZ06P5hrmtaqs3olh6lnLGg6Fk3x9mZWuKqLvkKiGQKQly0G1jaNXVPgQLGxbndPX8WlAG9cTbKq4CH+Psk6IHcX9JrrMN02DVKf8Xz9QyHssIO+fe/qNyiag3hMrxU0qViBHVOBjkKpd+Wbw74woUB8ydI/ITNnbNdse9oCjM5lS/+cZ35G6JSo+2g8ARv6phyY/XH404010h,iv:272mPySUbGZlJybQksTUq7/9FUTDtwxvICH9c1wjd4g=,tag:H4uFbB1l1P2TZHXKN4hqtw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQWVZQmVsMGl4MzM4eDk1
            K1g2NjNMcUtTb3RhM3hLMzg5dE1CMXpuckhRCkdmU1VKYWljT01CSndhOEJuMDRt
            UXFYRXM3d2s0bE40YlV2UzVQSzlDNFUKLS0tIGlTTGdVYWZ5c1BuMFR1T3doUGNt
            bzB1MTdyM25GS1RVVzdsYTJSaXhHMXMKmCmSamgVPqekOso+gEJpR5bOxKa3dmIS
            zgspNeZxFwJd2UrXHocRoXkAB7tTtjHTJbEMLf5a+5rvGGIuasfhbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T18:22:27Z"
    mac: ENC[AES256_GCM,data:oESAYXANN5TZRnEZ4yut1e4ZGeR73wnwDFaoHU++rTpmaQuIgLgttLfxQJIGmoffDFbZYx5keMSsDlhD++XeUqHyPIg/JZJwkXtKXBP67HPvaMW7cG7M9ykIcA5EwPeb4y9ZmNDOd7UWvvQHSb8IwXhathncwOrZWV4HJg238vw=,iv:1j9CyPCuZcyAN5prM1UPLZjNgk/Yrb/UC9Go0WGmtp8=,tag:Vb7ps+5BrrV8SsRXmpgeaw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
