apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:K/1PSKjg/h9IwMQFCf3s3w7bKF5XdajjS99VvIGhwBXHcnhrGMrFW3tgyrzJDcCGVmv9qZDLdpaTWWcnmrgvDWIHMT8a579XdZFKq/rnvMhQ34BG1CWfXzjssQNgqt3ijfv2mVRJ55rk+jMEob+YBzisv05GiBeK4RRskXTvNjYHhlqBb46rJw9/UXL/R9WMNulGHuvhLsZwvZHil7/2yRDC7cLShN6+tl0yO4gW0VYSQ8tNZcXLyQx8+13lyol+xOVZF+FbPrDA10pJRSDXo6Kdwj/u66VqYuuxvlHPIi/srQXcrLd+vs0gFu5kUmm5LcvKG8f2WKpQQFY+g/l76cao/LB+Qq7+Dl0nmuS4mxErk8S3M/KOHezipFsAQ6tL,iv:HZTMvyAysJ+VKD6+Ds/uzEIargUckNFQ9BMOHILN+/8=,tag:OPrkgQdtpv5Sjqb/ZiBdOA==,type:str]
    identity.pub: ENC[AES256_GCM,data:RC+D72nmkn/3vsos7/tmVLXoh1bbUZre028lxuc6ktwzDqxwCphIB5sZFU4+ir8BS16U6jGituzU7ib3cKHE9JyHFSjdamjk27PJDqpHYLIfxC5NpMhYMVaH063XraSJxAn1l/KeOGKcgo0IRrKwdtMg8ZnShri8mvODXNQbQ4o5reKVNvcs0ph3ZoaKiKOWNP/SHQ68n5Izc2bycVNZ6uMrKCmtLqWgZOrM97ExWGulyQSUHfS7ai0BZTBc2wslfhxq3oKI1gQ1w7wwng==,iv:vaZqPEFQWoqitJ0IYQVsW6/LCZ4qYynw+FwlaLPn0/A=,tag:7IzDScQGkm03idTBgPqR0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:gNDNNC4D+sYT0tlJ6UHVcxKpoHrXdJ/Gkc6X4XkPGTa7CKZer36auD94vIILcuoKH1vxBR/sqfuGs2GNWOOqdvoL9BbSTML1s+TEuplApKYq+bxAX7GmD2eroWxwYHW8+of9XpG4XcDsvCSuK8jdOxBqcW+LxOqBmkr7c2wJBKbdSgh/BZXCzal0FshKsR+3otcnamDf1my3u/t5eAb8zYZZzohPUgJYVUc+,iv:4iYFs4U2KLnUjK7S0q37CkAhft5wtN6DzRQgXd0HX/E=,tag:YAhl2qHXYGxY4CmwdQev0Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZytyZDl3dE5heUZRUzNB
            eHBCYmNUZWdxVlRiU05qSFIwRHBkL1FkMXhvClNWRFZBT3NCY2JEWHNDenJhY0Vm
            YUc1N0VpY09pekhFQXV5UjhMZHg2ZkEKLS0tIFdMT2VKZGFZcG83VGpHNi9ISkwr
            Mit0THlZbjdVTzd6eEFkeitEUjlMclEKaesoBu+s+Myo35sKhNpTP5vZvgWrl49N
            KCygJKa6AlJsZD2ztSRbhnCJUvwrD3IcI9S7w3RyN1EI7AeXUlk2oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:15:53Z"
    mac: ENC[AES256_GCM,data:/6zFJT+FPg+pN+0rBiQdADDf3yYVIi/6a9CuJ3WGvKIbKc5QCGfh0pZbM1e5T0Q58RTkMR2rA7yveu8vCe8eJowiEzTjJtBziQuOUlrnr0tUvwefKbaUlebfatyDnp1ke94KgeO8/QLyjL1AdN0n0c7fUbyCzcuzz2YHzr7ZyY4=,iv:S6GXDt5Hjusas6Dm5A5b9xm54P7KrnXyuNrjf8AI4mo=,tag:/Pnfhf79n/xrfiPX8mAV7A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
