apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cIoXUKYkvBZ4YdzEYxK/yqkGGiRYlRdm86OCsGS6sKKEb+IjwtAVREKik9O3qj6OMjdLZe9l0joI6BOU57hiCTDJ8sO+Shlkix39jgVe7Yrp1NTEpQgAYMyK9Ieu8ENQoIQvDcyMXWJ+ybSb6kc6WJtVqPc0l0haYIjmmvZXDPSgO3NrCvdswUw7UjoxMvhXvkOGlcka7zd2InAAlImRejV5v2UoTe7tec8RHmlaAt9HpkUHrYHzFPZn5OElRI6qlAilrgK0swheR1wVFpMEUwby+FOmvHBRe/ar4BRo+6QF2TPBzYt5surGaXgBz6Zj2hekqPxZn0rXAkZfnIjeXxJSRp1XYYJKzoKUDbdDJkgDtdIwwQmt4qwCe7eh7sOD,iv:Hy8k1Z95IUU25BrGF9sgrgoDmaBM8hnhNdS6ZiNVpKs=,tag:GwyXTf3YggwFd/os358Vsw==,type:str]
    identity.pub: ENC[AES256_GCM,data:iyOSRXhueoIU6VYfjVQHedI6cQW2obp3lbvJ4PX86xGJynXANfNEQcbWezrca3PuhzrkStK6Y5cdSs3HtuwBxrRkhNdiRva90XqRws1nUH+jdjN5qPPXYsNlvR9cjpJj8r7ORPX0xJBRdBqhfT842lo2X1sJm0qTbBewTp0fdlskI8Jal3me88QDX5md0/e0q2rE0j2UgbgASIUhQbSHDtlqCJDtJnF6SnkABcpUxnhycdz0YZmZSiGt1tooqAO/CF3a1IL7Jp+P8ompJA==,iv:WMN4KRvDI8vqIdDCpn5Oz0RdXS4DoI/n7Zn6snIoU+Q=,tag:XFxeoJFOzZmOw80jolbVzQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:WvbHGFGHY2CVTQeFPw7YmpZOUncdcW3w1Zd6hLAfOdOp8gP75Owu8TufVhtc9IoLu+HhWVrZefwWE7K/roRYa0ywHjBndtsRqhnlDxVrPltqjRfQNaFoQK8xrmOhv7Npj5HEdI5iFI6YW+bKUbY8DVWr3TEp7qZffSPP8npLTm4gwww/jNUBHA+xGblDKp+Ewa9McgSuFjVuEYUv+bBVn6vEkM2WgvDwXWy1,iv:90oFTiWxVIcoUZXs9nmobPv/UFwh0FSuwsMVq+mH50w=,tag:fxNlyyoR2hFI9/3puh9ozg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2azhYRlV3L2QrTysyLzla
            WXNwUzQyNHZNZkdZWVhCRk42MkN5cXBnUHkwClFyakhsTG9jOWNWR2JzNmZvbXlI
            UzZybXpkT2M1aVlveWo5SkdqeXo0YjQKLS0tIFA5RWNzaWV5SnJYbDYrV1poT1Fw
            YkNmTTJEdjFsSE9id1dQSjNsMGxkbWcKvqNlMnwYr3lvmBkA10rAAoDC63vhQ007
            dmx1R3G/FHaXWiKLmb0ZktUv2AiODq4ESVeAlpKKwl6ebYJuWX3tyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T02:30:33Z"
    mac: ENC[AES256_GCM,data:RloYBIXmi9c2XVEG0ue0r+5aA48Jl2K8rG2srSXxBTBE3o2Crv3zo9lfvekR2XGi592DLmjNqTSKJwsMjAqO9aXJFxNJ3J8yZ0H9foeOaCDz+vZetxe3oiiKkocQVkp9aQSnq8Xq5kpuVT8gTT/FX6zVFgmpFTZ98sSYfL7hn5c=,iv:7lA9piF7tHyXB/BMRNaVKHPu4faFM0YJwtZ1+C5p4QI=,tag:t933y88DVhPk7OBKQc8eeA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
