apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kSMMGqLQoEw48nTDdw+DVxRyb3JXmc5U8yeq8py5t9wglGilGM7CIbYbU40ODcV7IMcutsJcFBsz/+hTHQsG8slNyzKP2ou/p2pcEI9smr+l85cUs2MhiPAJ73xUrOxBKD6y3ATxGNH/ccqTUp2zH1Da99Lwn/osNUlKkN+U1LhqKh+imT+yauBOnOLZyFIbd9sgq1U1G6VRWLXJKBhhnTWPySuGH+6FybkV0KaaF1kl4L1izphb+qGt8o4yMxrmdkcA1mr99cr0grqpNYeYzjvO0N55HkUycNg2P7YXO7GlnIznVkw+KlMsv6e7sZZ8elr0OpElqCsx7hL9wHTDPvF3rho2GIg9HP/geV0uYjeDkgoHzCW1rJXBclAfYyfh,iv:1LRACo5LoU6VlFMMnSNhN6yvdRi6DV7sijSgTDAO0/0=,tag:4soAXpNmI9CQ1lvKiWns7Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:Bb8T0CYGJKqlTyKtaeDS6QPmUjH5TqUUo7Wa4+VrrgjL0lqlev30k/xmqB1Nh1X2A7fHOVoFcUGCf5SnTzUnUriyOkJJjpdgM+qqsTD+luvHiuL751lqu6Xg+FYjW+TKocHDzH8G48AZG8FjlpU+bSnviu31NZ9ushow859q+1AiJMEFIOwGmd+VLGS9oqL0I6v4gEhkc9qZsRKwVN0mxoGxyr6vDZ4RWUfJ4lUVTzg2n2sH+9IfbdN6hbewJStxo4xW6CyOsknGvCIqwQ==,iv:m02WkfB4Lz0vZ8hKUhLmvyqQWiJgGnflclkjhDwIh74=,tag:UveFcO/zkqAmdDXmHU6Y+Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:BCVAll8A5NrOzeIKY8v7mTXbVOyeOaY9LaPhR5/TOnTztHp+/hSaPNTBrrwdEg8RpdeGouincehzbdyrwVMRxDSEQYMcBu2v6oi5R/w4N58oMuiy6kPK0pzgDDIZTu/iJuIyZOzFSgFDZSKhTNucDbxf3rzXspOZFV6Di49jKNPggqzL60al+stSaJGQLh40QefWX8QfCLQaKPZF6EiPLqdMyeHwjLSF3QuN,iv:838NZle0aDF8EPl0wlhaFBQZsh7o2VmUCM+CFmWYD2Y=,tag:nsJmggjH0u5sfYfvkjvdUQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU2tEVnY3OG9QZyt6YXlX
            TUttV1F1YVBZME1xT1kvdjJBY3M0bnZKTGxRCkFlT0ExYVAyanIvS0VpVGhNWXpj
            Qzd2YUd4czBRQ0ZyMTJ4bHZ2Y1NhbXMKLS0tIGxOaWNzcFJscHh0UWoyVXZneGgx
            QnFDTkxVQ3BEbFQ3S05VZWZ2cDlKZlkKUAuPzEApkeqLxdguWqs2XiNcwdsLUs/4
            qQyLq3My62hZ6sMX/aOASuZEcjLMZ2a8pxxt8iBDYnxZr/X+BFuLmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T02:41:25Z"
    mac: ENC[AES256_GCM,data:IxJ7QVbo06DT4i1OlU4qOvRDtS6/8hOr4xq1PBDxf3bp+EEPFlkKUPPHLMuSe+8cMiem9KIAvlrluQFWLD/iqRdW6pR1fEm3ksS0AsqgPCyVCPqQyNSWRt+idmriOEwgx2BUdKL9Xklk9Z4aX/CJi3QybemhLs0UY/Y++oqFOv0=,iv:5KCBURIZxAu/E2RmIZ6yODSQjKs0L+ZoLt0m/fRy5gk=,tag:UsKNjjl72WYTzIdG7WBG4w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
