apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XbIZU1sq6gS2TEQxUAFCv1dWczd+DieF3jNtlWAVkFZRXyMG5ZgyGej129TXXNta7lWZ0uQdMyLtzb9MV+wEeYAO1fD1PJf/LKbNabABnZyMaFK2CpT+P07X1buxntnEw6boinj08R64BtASnu8+YXPhrD/PoiPzl+M2TIObg2nuOA+uF2oYIY1Cs1k7kjNlTzBfD6QO8CRQO3Ogepuw0SGHa5xHit00tO7csVV5XTffbtgrnTvw6H0MvqgbOwR8pSRRKpHpQD3HMK9GMIwNXcuuZhmhueXq5SQi65k8FAh5AfVbsD9XDBfykEoCWa22LvCrb5z5zaUH1Ryq9AMnenBOu8B0UBn3jYdvwxCwUp6s6+7x1Z4Z0ljvGFE2V1y5,iv:PelyVAcS/QKb6oeq/9Kd4I4Y1Eq6kCM11QYcRKUEP/w=,tag:wkklK1ppWePxKhMZOJ4fow==,type:str]
    identity.pub: ENC[AES256_GCM,data:GlpLhtF0vmsR+dpGVutcoTQpqt4QhGlovpqVNwO8KFxkyuMtRhYubnRMRjgHxyIld+Th1ayWrsVWozOH5emUd+pdeRHOmtKPGBNIZbRQ8ATEVXGcOjn44zs1D1ZupfvtRg1rqOgMLlz5xVu2aki5aObF2sxGH8cU6OqFfLD/B0CEP0BHc2dPG6AoDbwmTc8bMPhZ2AGs5oe16FTXYYJQy6T5/NjCTIgiQ3rw0BomcR6Ooaplwa+FGt6PYm3hQXT6bil20hH8UCnW21JVQQ==,iv:gyONaZmrTf8Jws2o8l6Hf7G4P762vamyi0aFs/DCoZU=,tag:hbzic7zDY3KMn6wLVII4WQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:zE8kYWdeBpgocH/GXD/hANmvQKOLDaSZppQCleYIjO4KGcvnckz2g3g1hrbcqA3hx/V+CUzTX3sSfgTlie89vozYQta8zmRI/uUuo6xfR8ZVVGLxZQobgoEJstkaEUfzz9YwNu9vtFNQzPG7IQmg/nr1Qa3rerKrp5xsWEvTsF0ruIDPGx45Lon6c5urN1U2gn1AmbxvW0lqNQYf2h8Wk/2s1NjDntLZyKSn,iv:WtvfQUQG7XBVnOqOzccWCDn84gMj4UGKAYWf1sb1UCQ=,tag:7nIlMVSKSvmdoJcKFZCNcA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM09XMXJBMmEzZlpTOWlv
            NGxzaHBnVk9idGFOUjlwbHRQa2U4dVpCQUJVCllsK3M1SlFWNHRVdnhCSXpmUWFZ
            NkZpU3Q4MnlrdkpZeE9jRlhCbDZHaFEKLS0tIGtORTFTdi91YkFySUVjc21PSzlk
            bU9IN2Q0SmR1U0JyWjgwWmlYSTBmWjAK3n8rJN3ikxoGabS2S7krxULPoUmy08IE
            bSYKDCAsN4yq/T2yxtVUSgkuls3baCxyjVdGDqWqBLZNchKDLoeaTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T21:51:58Z"
    mac: ENC[AES256_GCM,data:r+FMHRqKy1itvYtAt7Ip+lbuyKeOrHE2MBdS8Ubg5qGsU0Icd5kG/1dqxzxIqA56xftC52bPbBl9ZX2IAgwk9uaPDwdw0dbK+6B0D1+YaJ2D39brq08qHeV+GVPZ9WBju+vQM+JVxKg2mSABWSeHAm2S56fRnWJBNmw0tGIHZbA=,iv:0aHQjlGn/xletZPgKGcBx7gVtWWn2KBuFQ7vSvxXUEY=,tag:9U97W88E07l7Bopt1v+YvA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
