apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1g7ma9stpWWA2PE0CybdXCcRearBckloUguJPhl/Bm4CK4luSyE2KDSDE6meo67PohEmtqeUrrAlWw+WCe8qWVZTfB320t0viUgJm02q1PBDM0cF0YjbDunWl8uv+yhKhHFuhp0uTUDOi6KkPs+VoYU3DyiJdijYDBRiFONL9a5GWnvwChdcYY+U9fi6NO0EJ9skwQlyVLAgSJxiJRv2Xj5p0puWFkLoSXPQHaeWyPSYkVPWHGU3ZIiu0iID79n6AichziCZBpoGVtFW3F6JTbquriOQZE6jJgf7+4mVKBXB9WgoTIng65SbwXIuvJ8jghLeN9yNl1cZ1Qcb+o5KabtWvMB4MImFT+1eJiRIGd+osanDCOKdU4T+1ofGH4+A,iv:L2+Y07MQJgmI8EhjVWL/oikisvUlgD/IWbOsxAaUHPA=,tag:EGjdg5juKFppHd9U+qH2tQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ld3O3Y4DmTeL4vvCl5Q1H5vbTgca3T7pm5Lq9H4KniGVfFlHC5PRjw6pTtwShy3ZmDqpXPzxJr7pL6uXAXkkZJJdGq3CwJWAYtGcxCKi9HTm/xyK440/qW7St9glkkFTgtKni2s6jIFMwtzAuruzdrmd8ZOXFl8W3uh/DSEPYniG6NbnizIrVWV/6Kb8HUkZHr1V4/bwYXH0iy9cg9RUvakQXMYcQQWwEAotZxEVc0QcwOvaNOF+7AlzgzWyOsD74MtpNT9/lQAmNIWrhw==,iv:CzygWWAl9GLftm07TTBqCZBCHLPOuwbNIoY2/4iiVAk=,tag:i5u6CvBTtUErYOf11/2HHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:gP8s5xUfmf7wI/yg99tR025CrentxID9B48+CBx0D+9wCnDoZjkMm4Y2LPa1aO70zH95jdAcx7bV4aFXvhUOn7b5idgI0X+OYc5jqQbAkKkv3GUQ9T3oNGZ2PpEGvJs+0rGhy8LMSts8Y/oge/XzkDZ2DNgdd284NZm3fn/vEfYOG+w6OZC0OMNT0+iKN11CVhP+TI7OQuG+HmcS2WhzodATr8Bbm7u0E+Qa,iv:FrjnMdkZ36cdGmIxvOm8W+/6mQbLahpuiDN+QgccTJ4=,tag:j4skhx6C3Fefdv3wmXxo2g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZVJmZEFGVURpWGlqRlpa
            ZkE5RXZFQWttZzJ6KzNKQTcxNjVyTVFNbkYwCmFZOXdmZHduVmRSM3Y3SVNqOWh6
            eHlvWnVPeHN6VkNPbGpwUGtRd2RmMVUKLS0tIEVZanpPMGtzVXk3aDlaUmY1Unp3
            eFNDL1ltMWN6SnovS1pxb1JUVi9vTDQKbKAQwIDg4aQGSDTl53u/bmPPjkglJw6z
            b3vYTTt8nBs2vyafsUCIb7Cogyf4ejJSVOlE9kFDNCr+Zf4/M1UhSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T22:11:35Z"
    mac: ENC[AES256_GCM,data:2XkZGoNbLM+ZY8KJ+vqQpDcrLAx/mjEBYPkYqUPNd5WJzePpvYiPUSy0WUTG3xR8ukpQFp3QqC8vheOlXO9AzCOMYrafhPA5HK6lwJLfRNSTOPhiYJ32ZGHmL0JmAm0wpv+cuxIoTp2WQ0HnG3YFR0msrVcwElcY3veLXRMfoLo=,iv:AZlu+61iuEPeq7UPqkAfthjS3JiNT5gz3RlSA+jhGx0=,tag:3yM9qavTV2GkzDUjh/DCWw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
