apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Xc0ZHJ5lJTVZhV+dL+Pm3tNLFp5vYIKFAVSuV/IP7/w4L6tZpQ0uGbwIlqpbkK/ZIBbtUgpRua5r5la4q7SG/chmWuB20RBYvwMd7tUrk96RmvfrNjKH9r96B+T2SNhgKEoro5ceB4/dHBGXhCBX2vaPslKVt1Fq/260vdxHy4eLRkV7VCIUl1jMZsD+funux9UTz/xXA+soGnovefRCpc5fCvPn28WW+yLRMUoWO7EvgvKOlzxmzmZzxvpsJxdpDfaofO9ibI7oyQlIttupuwIEKIIVxBkkJvgFNC2kgfGw6a9iPSVofyJpOWe93z1hKLaIWFW6deQOi6t75aTg/EczBwuQMhP/H5lxVY0OCPyQH/f+b0uU5qLIFjx/5nhI,iv:qYZQihy/K12aKzvFZ+WYxYU2KS+uGr3u90DpvCBlVM4=,tag:wt8KGESA/9/NZj816DSHTg==,type:str]
    identity.pub: ENC[AES256_GCM,data:DC+mEXrJfYq2r0Lt6SNWbMH4cIYLZ3HpplAP97tpi8eOozSeH7xtnpX/fnUmm+RfFKDRR4ZenSFTT6s7Xy3vFF3WTe5ZhY/Gs6VUEm1u0sX7iWi5X7b9C/540b0o45vljnX3SpGvrGFO5Z1vRIHzdeAumgM3Tbwh19cYcLWbB96vGoKTlUghW8Ob+sssTnh/adD07xIQOJ8wEjcjnf5cpBUqIhnMVeqjpQ4qFx3/H0tfcOiovazUI/IBnxqPZJpVCAv78EMMRwbBM4kvpg==,iv:/C4mfQZejBALm+y67y/3ZRdDv9nTHeqgHlsKVVq4Mtc=,tag:MpMX3mqfKqKaxskfN0meiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:zT5wAP8HJuV+iuQHFJWAveirgzWzU1XXj79kXWx9iyVTzWIFYFq75cxTVp01EyNdrFXILM+L71jZZrihfEsxwx9OOS3OGniJJl35bhHnDbUz7jInIJZhPxvN7xMrOExaLOHksDSHkz7BAO42GdeMCzn0JU45ge2wjUZTrOuTpBqrdhsxG7LMGTIWqwez3IItRd68E0hRoJwu52pOmvC+FgLZTCe1GWrffgCv,iv:EBNfD/wwIggbl3vJj2Ew0uRkg7ePw5Fk7rPGvQgvOo8=,tag:XQNnCrvAfgSS+ZYRv82PYw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbkFZOGF2UWpqL3RHU2Zj
            TytCMEJocGZwQmJsR3lRTUprR2NZMmcwUEYwCnJBQlBlaHF2aENWcWpXd21LVm5z
            S3NhZHJIazI5YmNzNVpKOTVBTVk4Mk0KLS0tIG43R1JVY3pZZzJQVzNzWjdLVGNo
            ZmM4Z2paRFRzS0ZUaDg3ZndqRU5saVEKHVb80O5ah7T8v2S88XY0cSDVB9go0S0o
            KUKsYm6tLagQASCIeR+0oCy61SSVt+1IksCYIcrPuqZWEEtTTYIXWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T19:30:09Z"
    mac: ENC[AES256_GCM,data:jeBAA++xC35jpOOu33M2XRcsMYh47lZyZC+22yhNqxaQEKK8sHoD9RLbASkf1zEQCoewWKN+8AqNHezeQ8JZf+BDYEeFDjY+hrjirvpFNYq0eAn43Je6J/UbH+uk2HhhawPkYtn2So7xUagdcp9/DG/x2mGzbeU+1LB/0vv2S/0=,iv:7Pj4Bpskn/kzQIjGfy7voPDM0mzGBbUjondr/I3YZpw=,tag:V0D5PQd+0OR4YFYKEtf1EA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
