apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8e2OHUW0fS09UTKnqGjkSDugY7obgS7ZZ4/Vbc4WC0iul7yj/Pe0kQ+uLilJs1YK43yDM6Use3mTs2uoWU5keSAZju0pvirziAW8JATe1ZE/E8bk5kmXpYpn9Ai0H/vqziqCigBHorKfIMkMOujV15ZVwM6Kd99qQwPDTL0w6Io2x8AMYSJBMma7rIja9iDx0pQaJOATXEB1XhBGkLHWa/ChHTz+Z5oSgbceerGp0KpR0j33UhMo07+YqYcDUO19VREcx3ScihjFSSeSyprkcCuRpvy4Zo2oRPN2FM3wpyz5+02MUW4WXlFOLddHVdrLzD9JgVuxToGBkMuIdqj16/aa4cQxOvXHgdUfoqlafDD6z49J90aZPzAKjMrLFKP6,iv:euKVryifoTPeIgBCDfbIArnDMJXL0Ivi4WTGliGz71A=,tag:894crnbJiFaAAaTeh73Gbw==,type:str]
    identity.pub: ENC[AES256_GCM,data:w/7QinsyVi8nXPCJ8AOs6YFZh8FGCSivJVjA8avtJfXRKXW4o4vRF59FVRH32JUM9mJjLXGl2IZQDFZHel9t2P8PzKoj+4wV7Z8f3tcWqCfNKTp/mRCysD+JpCeG8JvGPebMQL7+4OS22IzhBx1fwAdY7tK7ERP0fEeJHEtTkpplKE6j4bz+HVJYfsk8DfO2YqQh7tJj2K2b7V+TTQtQLXoB9PtsswyM92mH5Ow3TrI7wiCrJNGLcKEcLgubfm7b3YP/hjguzCKvDTtEgw==,iv:euujOdIk/d9KDyyhe7fVDHRAZv5v+SjTWExTx0y6pUk=,tag:gzbHqWKP4eDcFgIaydzDVw==,type:str]
    known_hosts: ENC[AES256_GCM,data:a/InpcymL3k3YUz3d/fWqcMWDPi8XcTbxwUMFZ4VYkQBEFiuiISDWdZP+2qfjqZLQlbmi3HBLHl9AxRrjUbLfCli1gS+YvbXoXSFMvSEQ1ptvLMnyeQI2VkKeVnNbgvycOYFCZJ/kJ4JvNdFcma4GJ8DiHi841LZBqkB38FE0IiOBrw8xxHikyGCaMbpD8zrt984J6K4Qmt8IyEMq0Zx4mNXZnwblWHOFrim,iv:GTAoP/sUCHcXZ8OHFwDlxvPviwPnmiy4DFGUEttVr/8=,tag:uuRxnpfw7993uePDiFoSww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbEFHQVFzYXBPcFBzaENk
            SHBtbS9jdXJvb0xFNjc4WmUrbFhHanFPNzFBClhlZGkzR3k0Z3dXZmxHWVMrRFZw
            SFh0NG5TdXNYeTNwWEJzYlVwVUEwNVkKLS0tIGZEWG5kNXhHYno0T1htZFRFTjNh
            aXJsTm00RkhGRGEza0pnbjJUMkpUUVkKwEPn57ADI0B/djN5VgW2u8cjtIsFeEIy
            cM96xBzkvscVekXkDfdEBDTgWxyavd7zVRdFNweNY3nOm8IBpHRSYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:27:10Z"
    mac: ENC[AES256_GCM,data:XnpHW+L79Tw5Bf9WZxlG3HtthEtGb1XVhaXtSIioYSkBujFtOi+1fHBSPzzd4MRXRi8hpQkekUbCY9BzLHIxc3431NWLfB8dp4K8VAXaLca7oGOpTvMBQ/3m9OjKemhGo/xjRBVzNkz/UEilLr/Gx85pehXb9ZTDqbIkH6F4c0M=,iv:VwBa2QG6xJezDH6i3wwqBKxkSKVq8RBtg9SSDEJ9w/A=,tag:hnyvGlWo5SX8V4UYrYvdww==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
