apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uDmO607VWhKT1LpZsPNzqyfPJzkrV+yhWjDPUU5AiSZmyZGcYsWix9oUXN4QuxaNdg92xXWDP24a5lW1J+/4bF8KhbYdq0R/qG0vRcK2nRrF0V5ZA5TjnlKKNEyYt1k2gjGXDrvIgACSCLi9tht1ipcej7CpWp0NcM5bNCXAwrKZ+retWo/Ox5HC93WGhSqiuwvnDOi2W+9n3DAZbmigqLZ6GYc6nepBo8I+7xfI9/K1Zjs6/UdeN3Au8agvENeeoQQhXfvXDtFI8cUYBjg+YJLA5U03aRNh++FvdLCE/V8wAbqHEkir3Amjiw9ab5HeeEsYjBNFXp8JDWI8by/ocGzcQD3E5Oo5teYs/4990Et1s24hdym+2WwSq7FUUlU7,iv:tDYA8F6g7Ov3n8TqAR2wajcbUVs+0U2eU4WcAkrKXvI=,tag:oe5QW//+PRyZ/plZZD/+EA==,type:str]
    identity.pub: ENC[AES256_GCM,data:XFlyU1GylBTVp21qWe4FmtYyGKwqHwMQhVLaJgmaKgRH4Yx9/Eg87qyIAJq533iy9QNUnZJzsnN19oy4rpNGh6cIXBIFgRDLxRqbIdLp3SflJMzWEaOwYLLRYBaHex7QdeScxaVKSUcD07dLvJWbjqMdZ3hRrcFlhFLmwn3WA8UQiuVeEVA7j6MGSA6V3eDEFkl+74mE3ep7+qfAZWpt2TjHY9jypDJySbqeaNJfN3pZ2hQPLUOGhEMAacZb2FXG5QONNJI2eFNeasy7kw==,iv:vGhu+uAQf3X7CW8OUhPqEfkIM/8QGRYJaGqHU5oLByc=,tag:oJaCZkXEkl6eE++KQVK9GQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:zx5gKQlS60Q78nkILaBr3ERBypo+rrkJkdD20eLaKwtUibNbwLVAatf6uXtM6Fwez06FLTQ3AXEfIRTOkzeBG7EGH6nCE2ax7Fy+/DEWPjew+uYHv8NfqgBDTczn/0z6PapyKypfTedpNgxcTYJwAUdMk/NIto14u95mXeo8rIOpWRmmOTtsFjqGc4kxcPEUyAF/S6Utj8xFKBU7NGGP0v2gGmR/Y0CxEElU,iv:6T8X9Ax5VpCrKMR7c7TxmVIs7TwqZ7tScXS+KihdFdM=,tag:Wjmqf7wui984M02uiJXmyw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbVkvK2Z5MHpselJQU1dv
            OUlJRlZmS0tzU0pNdWNHQUlYNW12OW5mSmpFClgyYVhjUWZJMEdlMWtCbWlJTGFh
            V0FEZnltNGpqZHVFUHJDRGFOUHB3bE0KLS0tIEM1VlpQVVFlZGE2QjgybVRkcWxx
            dnJiSklQTjBZVjZ1a3RZRjNHYlpWcjAKyycfVkpiitKRVJSJ4C9YE/iolNWOEU9u
            wgTRkxKaGha+o/F23Ycbo4gRMzqh/AI6zn5b1xAYlw6poI1f0N4+cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-08T02:17:31Z"
    mac: ENC[AES256_GCM,data:/zlSDwl5dFTdphPtQ6Df1iniLNb7OijMOtQz1J3QvPCqtCGL4yB8bSV17/pxJGfVxZHFhHr20MTTtjID9nQ50b8jBiG6i6leoNXJttBGBD0vFq7tqajVRzVqzYSDkW7fz5+2dmYUehj8sBPH/a4wNtlcDry6wLgZk2UBxUMAMm4=,iv:wwvXBN0HtjN/Vtt6/aquzrPy1fs9NDuFv4ueJ1JIimU=,tag:wo5hM5HpPTSnouXTfu6Wfg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
