apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:M0yfPQjTc68TqOWpzHiyz2bvpvz1Bwg2KFPjDbEju9jl1UXp2ekh0dtft/gUmf5jonHkrS7qiLlTZdmYkXaJoocrAxEWdgmC1+4PnUzQcON0ReTp1SlYvmzSs9lDSIYVdOv+w1+AIlqb56N6JlOw93QbWQhDhqqAxgoa7ZPqeBjwGVIsVsKTBjdoqjd0K6pvaZK0SJcjJR/1Y1YkpBQ68adfK1ew3Vr6GJJ+tf/b2Ed7gWCi1C5b1vd2mRQzAVpGEVYxI7suBhMu95snZOp5MVatPtJTh7b7UmgtTRF0rtBHkX32EFs2ttG69atxN5Ihni95qx9j93iyANTuNcOXrwc2s/K4CKqG3G/hIyFw6y/AYBDresPkrhF0XZUdeyzc,iv:eeFCkbw70wZAuAckiU/2umArFpOrziWkwMmKBt1N+zU=,tag:u8HMsSNQja6DmQfybFCPrw==,type:str]
    identity.pub: ENC[AES256_GCM,data:gQFPwwprEpLz0jY2vZdaJsnaLZZjBe0b+H0+O11iYdFbcog0oqlWItef9xYCF2A7KMGbFf1BVyrkVcVb36mwWtskDjkD+sqyxpatfFVy2OYxggeLqwYCMPBcurI48zbKhKiMhWMeIKUzFN7JBd19D4JvoR9irEd7wny7bdU3ljZTIkMbWoM16dMllIcXuwiyqFqtLUQLOT21ubYMwBwYgBL2rXtC1nPJ7NMtMjCB22l+5oSoJA3HyJByLM/Jrt9hkHSlqIqpD33FPU7F7g==,iv:OISgrP4F+Xw9D2ATNLs/Aw2lrFk8RjU0otNnfqrIW0Y=,tag:MLYXr2WHHZOxjhAJre8k1Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:0h2B7WSpDyM03VN3hnXsDXkl62iuzst1UVhZYrKozXwEhmR+L5hVYhOsYKRhXtykLgQKvgFwnin+UTNJB9JIgJ7TDHdKJIAQsmevuxjBDVoDkas31cyqNgJ3oz+BPLZWKGP7NMOtWikyDAD2M51nhI1lOM46YDnzewxNiW1nVbjeepMy8vDmn2GG3hKgcIhfb7CRav6JqWwKY5oxxUix55CJEazhciUIcYQR,iv:CoF1hMemSE0CWROkVKxkCnyYqcJSS6Fk0arti8GKlFI=,tag:vr3kP96CvzLdid6iSLY5ZQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ21PTlczWW52OUpUNzYr
            WlZsd1VoM05vOW9Da2lBcnZ4RlBURFlDUndnCnQ2SVlkSHgyRFRVbXhQZytHUktG
            U1hKNGJ2NFNVY1ZwRFU4QmdOeEJHenMKLS0tIGhVYUxxNWlWTHZsREFITHorL2Zj
            TTZMQUdxZmVKY1NaMi9MVjgzTkdZeU0KzJ787nihJ8gJ1JixKbfnMIYWPneLNf1I
            Q/EEwc4FF54SpCVcwK/vgDjHmW9m+taAvdW4Olhl0hJpDpFAT6vKKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T23:00:44Z"
    mac: ENC[AES256_GCM,data:w3nKMZ1GeyvyoIk6hE8yuqd8JYn3inA3qg1BTQSsjn31Timwdu0v/SrkTfO+DXwwqUQnXtpB19u5aViABBrxB1zu1gxqNlA7rptp7ntVyeJUGnZZ7dvHP0Z6zuIJeHTgf0xLOF0VZBsiroBcOUrGpbJfnWaN58Bwdb2gHLtieQU=,iv:XX8W2QbuVTNI89QmZigl0F+nIdFq++P1mIPdhIWC8KY=,tag:NFg1MaoD5DXPoV2yz2kwKA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
