apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lav9hrtWaae0XSDND9pySNh8+kD6q2IEEProiu7ieUBmNSBfBkZyoan5ey8sWZyyZzdaBQ8DHUFdpMs553JybN0E+JHcaqsbbvjw7DET1SucYD15Dz8RWV9q6eTZY4xpEascoPyndPuL0kwu82LBvFSzcbm7vnoi1JtSGa2wJpCaZ3F2cy1JPKFPzoOjHCpyNJ8dCbUm9b1HdIKDzOfDqbaOFxVh8ZIU+UWZkX9L24yI2a0NA/kD5nInsX8eREy4rUBLuFXFbAtj14t5pHVklYt5qN1Ji0uDhr8JhhhtQeVkjPkZ8DzCHLGYym0m6Jl8lIvltyX7NfopPF0wdan+NByT9g4bcLL75+pfkPquY7L3Pv5vlP1oD02Sai/5nX+h,iv:iZB5EPs1k3NQHjKCbNqYS2R9lzjnxT23szG4ruUXBSg=,tag:whVLT1jDEXGmbkMGrbTwtg==,type:str]
    identity.pub: ENC[AES256_GCM,data:fpkHUPb2Vm5YKfL27rMv+0oDc1/285A4qrWpHihGOFX0RjEp0zjnF8kEz2Bl4aEy8HJ1y/C0HVLa5mJkbfwCnh7bI26VoCP1fnh3hzExGtFDM5XiGzNdGV318QqTxkPjsJVOXDgp8qeOsZa4SZ+bO8jadsYcqNu+6Ub9hF+/4y3ukokoPLngQ05jT0bEj95hWpqP00B3FkvVZm5asEOdUzE9R2pfe2T2l7+XtHn9dJX/JdK7QJ6jKDRtcvYRPJnKnSa54uPUPqHb77cn2w==,iv:koKqhOLyP1O2i81cIx/GdBGli70cyOjyJTVODUpzMqE=,tag:1Z7VnhyVPUnTSM44ZRrijg==,type:str]
    known_hosts: ENC[AES256_GCM,data:5ptoCQv2q+Lf3kyO4/6o7CGfRs5C+WXgHmjZ2+mT25Y/WJG7xym5KboSEA/lvTd+iRHMLJ26+8ejRhSd6S/vkPLAq2Ev5JM5QLO/1vOC4r7sR0gM0XbuZ3e1d6QFNb3CxJHP5DvrJBun1yolRSiyb8/TE+t5fqWaLipSknYTXuDoPPMr+qyavQP3iNFf5Si1/c11wE4CUr5Y7EQVUSDZ1nWhzC0t7mVTf5Dj,iv:Xsxo23qt52Jf1ak5F71/gi3nyF4No0HFVUv9Dd93b2c=,tag:38QU74me6Z/gKbzWOeNgXw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U3dQYVltL21DZy9sa2xY
            Qmx6RjMvbHNxVVhpZHY4K2grUVMvSm45djJzCm9XcnYzMFFyanNmc1M1UFFjcHBj
            ckc3YzRIYW04eXZsQThTdzg2RUVYWm8KLS0tIDBTR0pTUWVFTEdhZjhIRm9FMFpU
            c2JJVTBudS9aNjNTcVVlNTlMekhSeGsKmPsPJPnhDAKhhL/EJ51mIJadWddQS5zi
            3ffGmN0BLfT3pt0+RmJsPtnLfQDcUPiCJ2SkyVJdqB9/tNjV5S3R9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T02:15:01Z"
    mac: ENC[AES256_GCM,data:p+v9pC5pbGTCpKXVAhl9ynyO6VD5rgV4iUgUr4XVV3oLST13p4EzS/TNdYMs14E9gcg4mOH9Cmpt1rH2htqnzzG1tXb/oMR7fYJPbcjSh+jZ30500rQzvIymMy6OzPfnB57h316Ii/gUh5Rzafj8OyRE/opAEARwyhy2B65XVSM=,iv:JEd7xqJ+uxr+5JJFmJ6+u0vPNCJb7rG3uJkddqXXqDo=,tag:nXdMTmmhPxcak4wdLmBudw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
