apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dT0vmNaebv6nUprWSWYe6gpCxfOnWfam/05SBVOnb+fF21SvNNoUDIX/CAJUH/lQ6j0EH8A2WTvHMaqC5YICe4fsTAZF6nJT7ikOgcjpJQ6hOuCJahHhyF5ulv0uAaDVTbWG4fz5Wlr/Eg3YnXKmwwRMHvQXFRm6QF0Sf1wAzZFb/4qhai3yUZdVKADcFjYvZS4FXaAaispcVBvoN/fQfbF5vSVPihO8VC8caTydnqqmykuUgRXcq9Qef/aDBKjPW5yn9qKxVtPkGyoAhOucWKFFDS2iljXEuSPE3c41VTR9ENcln3ntC6Z6l8FwpgrKQo6wbFyvAQgrWHp9YtuPyfy0sv/AwvXu6sLQw8EMABuPt/tE8UIml9nPdyb1JiP0,iv:8AK9WlC0IJLxG4MIHpB+CBs5PWnkzGDphFDbG0ZqsCY=,tag:BQIV88piHj1UuGJ/yiIYog==,type:str]
    identity.pub: ENC[AES256_GCM,data:laAt2O3EAp0cLjoe41768GaYx15s4PJfAFvyAaB7Q3jDMLX0h8hinUAWxD7UxBZdcOw5kskrWE4x0lyRURM/Kyc3JCUa9blnb1f09ZHDpkjix3713z6dB+zw/fzhZGvIRho/WwbYoGTBHJT9KQuN7ve0u2BQtuqHFVZKLElcaVfonZi7iR/s3+FZ4DKZJ/GGvGYlq/3zbvDtHBu5GmNYAlGPrmt4apry4jjAU9cWRCFAGqWbDqIuBDNy6B8DYMNUuIIXBGzR/bqiMi3JSQ==,iv:3CN+SqKaN8k+jNG9Y2ZFEHIuaFpQQfsNP2aTa5JPpdM=,tag:MJ77sTiFgcKlEM78HyIUkA==,type:str]
    known_hosts: ENC[AES256_GCM,data:snvSS1VrWcvZMMQJyIouKSOPxYI1FAHGJDrQ8PMBEbayt0fBAJhiWqU9rdH3QKYajg8FUZ6yGsXikVQR47H4m2NLthib0o219r7fqIkf1fi1Grqr7o5PA+qsrYjZZIglUFdKvkgkQ5bGiD5vf4AYq8KlhTRVdJO7EFVL5y0bIXG3fNp39veu/tEaTb07r4uiOMSDYN4k96Sz7yPbfJ0hyBN5ZhTGbo4tPkNN,iv:Y+4QXVCku1c9291JkBaXdpXUxTIJVKAKgfZyz0nSR+w=,tag:vZkJR3pJ4agYFNQmxItblw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aHZKaG53S0FlbXNFVzRu
            QlJQZlhNdlNCcmo5eWJNeHBlMFhXaHFiMHhJCmFsQWsxZ0RJMlJneUEzQkVTZXJz
            L1dtOW9ZM1J1UXl1eVUvbXFMaC93L3MKLS0tIG9MdFE1OHF6VnMxR285ZTFBcmx6
            Z0Z1S3Jka000MytqbzlmVk9JZjZWVkEKykoqyCzNkPTrXhkVn5bpL358wPRWRQi4
            Ynr5uWkBKRWM+aGLIfHj1buTGSDGugtzwZ1s9yvdN0ZcS2HYmYqgpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T21:02:36Z"
    mac: ENC[AES256_GCM,data:YV5VXkv0GRmPNnSQ1ks907QIR4ERIWUrqVbb7AI6S1tGgBu0WT9k41snT1IH3SNRjP+lrGRmTrujcDNw+W87s++Cv6Ezl6IdpOxMQBEKm541n3uB92AG4naqd50+1Bp00mDtUjQSijqSjfMqcIuv6apgVT5fe+Su8NziZCSySr4=,iv:B/mVw0vFBQTOhI9hWLG3K11nJG1TbLM2jAqgnT3n5R8=,tag:FXWBIYM/F5PKc9g9N0EjRQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
