apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tLKCL/u0TXcOwBIcFp5J0xeEg3YtFqw7FdP935+tjeHduPmEG1cxHO/EXIDBTdcQeGx86ddnVSr4wLcXVjT8K9/eIIAqF63btvcuXB7KH3qddupeaimGSgaSo+9hzNu6zxF6cn2tnmfkQx83eXUMhFI6k4X8wPUKnrqIk90uQSUhu8ycuI25EnIVhyBqsM5mWYgBbFUCSdyG3lsfi2gKVdYvsc7eCcr0XcaAhic3W6j0vIE27GV+qq/lXx2vyFn3Yl8tLFA3VnpFQHnGEwoYnlp3SMVUZsDEzHHctNqgRcsQtqMg2QBJxtcTkR9C8vsChedpwMlbDhf1ur1aACu/Sv18GmTxBmPmKUMf6Ygx2by/LjRkA9ctS8fSsBK7CrJo,iv:qvfXa7BBCCJtVTp4/CO0ugiYTfQSIJdr87VGBx6LOq8=,tag:cy5/k3nLqoVc6NfzlI86FA==,type:str]
    identity.pub: ENC[AES256_GCM,data:5JCEJ5vMyyIvQEwIdNHnrIbFc7X0x4hxHr6+gIpjZNzy23/0GCjJhTT6eCD+y2tQQxK/1w7oEmKpEqSW5vxCcRpCCXGfoQ0pMniuurPBNTLR0zpG6sLZmrbI0e0nJ/zJKoYEGQ3BWnBm6AeqE4KROElxJvVUW6VTTsBcU1f1DAX02MrQ5Q+eBAWD3GA6GYLXDy+50yCPC5NUN06ATi77av6gXHJNw75j28ikr0bhHqTLILFN7CVGaF6+Qba8FVvB7FFUxX6Syrtte+/j4w==,iv:VeMG6WTSxZBS9DlLTVNVH8rTybpuhLkrwr02lV4isPo=,tag:z3b06Ldda9Pd+3Nnr/b92Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ns85ICavw6Jq0QCFlI2IpEHk3387CP0IUeGYoPNifhmwjeoMmnigCcvRGExkVVUk7PHkxZyWDRfSXvA0rTJfqSeTITNA1gyMIHE+ztGibneprRth8RHsiFz2qgzVhUBnADPMTzSizGFKu0AoSYqrK79OuqAR3YLE/oA6dSz3urJaaWJouOba+iUFxRYYAxrALM+32MaoeMzP/6MayzyHj7tCmSoVtb7rLx30,iv:RKtXbFevhvFPTHOWdIGMun3rbqDuAhwQ276J0NuDgoE=,tag:khCnzIb+CgZgGgJ8Cfat8Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTm0rQnlLdC82QjRSdkxm
            eUZJUWMyRW5yeVkvak5yUkxQNXdUcC9JL0NzCm1CNnJZQ3FFeHpGRjBwNHNHajBC
            TzBUUmZzZ0ZvcHBOKzNwODN2dWJGQWcKLS0tIHVoUXM4eFdDSmw4VE1pUUVEMUZ3
            ZzVzY2MyR0hMSWlhTWJRUUg0OU1EcW8KpP52bBF/GpvE5wa2v9sGVUh/WlyUajK+
            H74yVH3iMna5u4fjiWPO44Kown1t5gfkAeOMYxwxWB/OYpDaAo2hLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T11:38:52Z"
    mac: ENC[AES256_GCM,data:zEpQuwtH4cSqM/O0Pq7QMNkD5SrPPoPVcNLszM4b+BES1+0lUAybjiU8ABAI5zMy51Iaan7zD0HU6LqmLpqob4HwxsU7/8JQgwGnthWo5Vkyc1VUOKq6n2UyzDlw8BL3BnNryN9SqYfJi5CHoxyFEGec3YRKQ60nfFhzRx7abvw=,iv:YtXLtkFKb83A3B3VnJ3RACWBI4iU2oE17/3BQrQ4ORM=,tag:liGfO8JJJtSZgoLRVX0hUw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
