apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iKhl8LF5jR1Q2Vrg8mXmSYIx/YPeuC2+TY5rjilFhFzzLynqugSovPNyVAC88LuTQ/aOckMmP9oJndFiNWLCT03cHCMFtVHGSHBedZWvr+Yy4SA3Nwjbh7MaH2xaIr5NZuMrws9yg5+z0PkywGGfWTb8K/70muYlf5QQ7y6Mg44jOKjHAMjC6m5nTogOPnacLRaEd96iy2qwjcJDQJuWm1IaF7sEveRgq2NAHb8lHtK70R7RkBTJMwq8TmXyvASiYa6b40hNvJHz0Qfb20iZiM5CqQLE6clifsheO71de+mbA/k7SxpzC7ngj3kAlzwAwQB++ZUIJAXAwBs9mZH24qYNHRI4VAYboBWmvihCZ1Hb3wyR11UggLt3qu59DNS9,iv:wjjHIouc/yY4HjoEecuDfH/n9gRzCaRs3Z2cqoBedfM=,tag:7KH2RpUZhHvxTeyp7jq3kA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NZJDycYNXsPQPGdEd0RMkdIA0xRu8NMsfMUOfR1bLAFXkHsDGm4DnJzEMsibEq1jEAYCEYQ3lNB5TBXktLFWQzbewaIkI9l/kYz4Lb429rSz9iUYwJtCFNuHxm/9v1EhR8LurhEcaN3Plr2HwbLSak1Ig2Qj5VfpnvWwTOAFWtqVo6BqASctArPSUouBtgCHWe//8caF5NHPHdxXYhtZD9FJ9BHq6mR1A1w5bbMu/N5ajNT5o4B1ICt84S5IOuRzmLfA2+g4APpQ6wPOIQ==,iv:C/FFBlVZUhc1ikX0INRkgpXT6ieE6KUzAPZAU7eCSbM=,tag:qXNll6RCSWVGEKfa55IDhg==,type:str]
    known_hosts: ENC[AES256_GCM,data:vUypacxO6eZVwen4LJYBgppxGcyMJAyzIKgcDbbScFGziKEBOpVvp+msKqRSpHavDfRxoxzxOT9ANnhOwtxr7a6LV0SaOtEJROlLJe3xMBx7wZ0YmqzqEcrm4NdlHHMNMX6qltRKJwSEOH8VDRABAiwYSbL8ytcp9h5sm6wYV1HD98nZp5k8W9Ow4lNTw9I6dPvMLupqGJgppKgBGiOdUMlNNXfwOFCg0oxS,iv:BlN/WSJYzyGh8pQyiFyaMecqzrBq5FbGSP1H3GXDhuM=,tag:HwHhtFHTXmBpxr/04xTJCg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bUtMeEJSVmZiTEkvOFlZ
            c3czSlhOUXhHZS9OcStmUmZTeXBKNjgvNndrCkk2UXBBdTJYSXdBVFNxZndlamlG
            WGxiVldmUkpHVTQyMy9GTGt1OWErTjQKLS0tIFdxRHZOUVFyZ2V0NDYwRVdDeGYy
            TjByRWEzM29sdU5kd0xGRmRxcitRVmMKNJago3AfxdyDPw7ZhjHVt/aFBoxt//8F
            E1firKT3k0ErFOsYI5Lp/Ark9lYBJUC4sezYWcBRMDhMOqlBOIwg/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T00:14:36Z"
    mac: ENC[AES256_GCM,data:Vs0utByekvSnz8Mm6hP+Cw0GM5TLl4MwtIOY46a20ImENske+gophS7FY6++ayFmf536VHWsZY/qcpuDru0HMAKtRVirqR7MTswqa9I7wk2ShxBE413UwmFyLFh2zhAxBDEQfDmopRfaCZB4INaRQ79XX6laQD1Fmrqry+a7jEU=,iv:2vdxm46Y0IFxHEsrNOeem5yPybSp0PBH3UaMIQcj/y0=,tag:a17eJtR3Vf5xvhfyWZvBBQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
