apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lkhk3MYEnuYZLBd0yaEPIg+XS+W33f2xW2HBTIt1HDTY78ZFf/Ba0gFcf3Z25wN2qJjzLoaMYwT+f7MBd4Aw2tZA6oAL+NILe0cVWssQGRzjlVFPKeh9jU255AkMBwWDnM8uTWmeQILVBtqBWEG9AomHnk45D7zwz9nUpS9iIvGJ3Jl7Cf/2AgNc2XZmv38jGlbO4RiBOB+GFdobuUBJofDnCz8NVvDQZNZEg/Igpxd0EkdoZr3jj5yC35KEmCJzthBMxRZpoXWT4JB9YP2EYR9G474yj0aC3nSam2VkBTBP3gZubSPLUh45njbRF6T24fRr1f4U2PrD46EKMyYGr+A8eNNNHYpKm2ViglbLdxqFtjDWHJcPtt2vjSqeY5+p,iv:DiPHmtHgwjZTksQ4Nur96nk92zwE0KzBEK6xPyGzKcM=,tag:lX+ZtjJc28xXgz8OAQkiQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:/zm1bydQXTNDGY5Q26QKMi0n8HbIDoarPttonV0zkHgSJy0cd2w8FYYCs6oCnJ2JbuKQOZ7L4wF0LpOZ9Kvceg75xeC9UX9Jk0UyhzfPxiPjuxrz/NIXcCDMC/70BjNus6RjSe/K0/G4p/v9lD+mxIQQTlLkWx4RWUrqQTgAD+iAA9aGszvMpsAhqAR7KB5lhixJswleXXd+Bfn/mnn+qZNRkWkLyi8iOsyTOXuRqSxXRVnqlt2Ggsmg8j1CyXbUpGii7k1snmueWxyuNA==,iv:fICbYfCya28RCAiWXZ3SyEpHCJPHXdbX9huKXTJCA9c=,tag:2qNka8hEqZYDVLJtlBCJ3Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:iXnF8w5m/e2n3k8aJ1PQO8opnmKLFcqebC5WGGUlj9hHRIpGJDheGA2Gnkh01dpbugV6DtpIVzmpIcTs9dJMSqThNmPILU9nZITEJryvwIbRHY+R4yKJ/rojUsbpsDhBBDYlDQapFcruBebhXqN3USsyspNW5iDXPMUmBNX4xw+L1bARXRwKZINDy4QVBxPVbmXd5g03dSiz9UZG4BO3P5CBxMW0ujZggtb1,iv:WxF+BPrlmBc4xJ/k6rhrDG9eDqRO0wTZoeFyosKYpu8=,tag:Smh45vHAl0aUGyUTxy/lEQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RmV5UFVoTHpmVklyb1lt
            eWdPaTVJYktyY2tlR2dCaU13WW5UbWNoOENVCklWSU1TUUJKL0lGa1FuK3QyemhP
            VVpIOTV0aDV2MEV4SjBsWmxTNFR2RHcKLS0tIGNUeDY3a2dWZ044OGpDOGRkL1NZ
            MkdKaGFvZmRwSmhnMWQwVWlMR3VBUUUKGty14bg3/lZNNyYjLAWLUmps9EJT8Vbp
            z0ebRFgftqszqyp5h7kA1SJ+KksrW6hDbhAU/UtutyYV8CmADoHDnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T22:31:13Z"
    mac: ENC[AES256_GCM,data:7U4h9oHWzVcnxEOgTGxelQ+LB8gH8hoGUGlRxFXrxRxuSKoj0S52ofnajqV8Bzr+neoYtsqWAGKx0SXSuebsspn1S2oSUTIVVqMXXa3pC0tMA5c3ILNuO2rQFCet4DerCkVUqIoT0DZOsBICbNHKrnRUPRlU/xzTJod/53nzfys=,iv:R8UtQ4i4DV3dkap+Zjm8fCCgkKJkT/U0qLir1BOIgxs=,tag:W8LWKH4VMw1lFT4wELyD+Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
