apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:D6jf0kczR2RDkDtxNa72b5cHif3A0bpeXeQ7Kugz9Wu0aqHvR+CXkNNTvbJyxHgRGnJeWaFY+k5aUgMfbmZTssfNOeUa9/t3WVSvnSAJL34XCQaWFx9V3e94EF7SnLO/bRU1Vq4uwQrZCwJ7PN+btD6mCSXVjpvfNtlDw6rxx+PjJkV1/2jTwHgjygVLSfCPtMWCitC23ckf61oOS9H3UAu15cE3IFWipZII2JwwupZtdociHRpHisel3hVu+Dz4C1ulNnhdwc3yBC8d37skHmldxfSSz0uTv3C8h0tQY5vM1nfHzqMlYnfv7r48y1lnsKXeLy4piNaOtv79JuSAsS3R9LG+Tf9kGutDySvyO+hmCl9qmQD6kuPGFYQd9s99,iv:Zze3I5HJpmAhlLtvhT5sGzFf14sEof6bRB5uSQBWh2M=,tag:0HLldQnjR2xvbWnqUdzCJg==,type:str]
    identity.pub: ENC[AES256_GCM,data:UC3H/LSvVaIcespKCUUHDqjIdQBR1KO2gea1VRtjg1814hfL3Zid9bezdI7auX2vr135LDTcVlefkHmi6/s1h1CUEfCU4OTK/8eIsMW3yJ1qGMD7jeSmObHKcaLiaegkkXhw9RF5zXbn6KPe3KEDGMOlAZoOAqAnz3gvP6EZMTaUBWxqsJzBumhnmuqj1nXI3gPsJ4r/botZkcSURQg2AJrs3PEYwuscX7edDwhQHYRmykgBjCu/C2EVhZmHc+Ej8/pkYdEUNCgUAP1i7w==,iv:Fz9+GLDK8u65hxbnLex6T0IimcQ215qegGhb+slAseU=,tag:jajiJ9IiY45aAx+HzsspVQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:mkyhYOWJKyMFVtFLV60+INVWjkojFBPpNcQcW67NbstYNITJrvGCcGi73DVRv3nr364upHBDZOZfppFxzxAZinprfhVdAhIAdGBbCQEAUDQLTCrlYHpzJ5hhwbGniYo4os8GE5YdiYH+RVGTlOif9vsQ+xIPhA3nxxg1MTD6s4Y+4ydZL9JmWUFYlC0dwMOdrF08A8FHw7Io42K3dTITZjmBeevmbnfAYRg3,iv:n6oAjWdVfn++rKFKpNCE+bQsCXbebP1H4BP9xX3YCWk=,tag:dS6+xDAA6z7UR2XcWnehWA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SXBOSmJXZE44bjVHRWNO
            S0dzL1ZHSXZFYklSQlEwcjZmNWhjU08vVVFjCkdYMDZIK2lNcnlWcjN4eHNUWDBH
            SVZ6OEc3ZFFxRmlNN2NPK05kMzVpSlEKLS0tIDJIWFhDMGhLZnV1amhhT0VzUE9C
            bncxTkRwTDBxa2ZQSlM4SnlzQnppbEkKN1tjfACTCQeKlK4NbgoFUJBmJh6GgSFY
            Z5FoRCQhQ1oTU2zPAS0LM2HjBaDvKyjTRcmYxQ1BU7brsnGm1Y3g+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T23:46:54Z"
    mac: ENC[AES256_GCM,data:/HXir4hz2NUBI5AmuJCHV7KwFWbWzafbkdcpnp8+wzfr01WRRZZGCBLgLI2GjFCQvBzOQ82GWJ/qlRXdVyggOB9qaO/1K22Ekb2CUtDsyYRElnM0vBlUCypchjjkL8aW+5z5bO58zywWRuQ7zashg6YwHUk+5YA7FAlrHcn+Bdw=,iv:NL1CVPdHdZ6yKg9xGDwsAm7H8/PXvZFNLGnaxG89DS4=,tag:9inUw4/C1zh3vZkkQygh0Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
