apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IrCo9htiu2gyFQWaETYAyUEWCvOnR4nk1SdvARIQ4VMJoMGs+Q7LrN/jUJytTyJ9p+11aqISMJA8k31vsyiNW1P0ZDKiCTY018qS74zpPDrKdKTn12ZMkPJGK6G7QHs/X5zx3+OMKe29S8cvqznTo+ZNeYfLJ4XNvK/5ZBZCJnnv7Che8mc0F1CDuEQWYASe2Mln+vzGpIzeSAUf2YCUX9Uxw64MoyPT+TuYqEAmnwgnaaBQhjOnKEb0F8T2Hbv5NO92pLUKylzGsjWp4JmqF5DyjCSb0nBOJAwbEoR5b7UQXAIt2xAdg0QIeACwsXTwMoVuoOflvSy9XnHokFI4g50YGxkGbHOsp3gI47AsT5nmvj8BbJYJHM0M9h6920xf,iv:WJhlNM/CgywLsqulcGtDiInw8LOcwN9AcbkuyOFdKLg=,tag:uBGDDjWtdVnPPbMrTEDx/w==,type:str]
    identity.pub: ENC[AES256_GCM,data:BZBIODEPgovq18aGDIyMF9733SYf7Cs2XxSRsqQeX34IFJjoCKiFthOh1qG8mCCJidzyLJ4O97aBgYx3bcjSRjxNJwyAqwEf9W4H3DZBtWZK5RYIRqn+3u5jFkDroGHOmfSreDFM1i7oSu367IwpDmdzstOVwfgzvRinLjiYMclDwKQzqLx9eP5uYWyz81g/7JPM07j4S8B00ghCHJjkDbMRblU8VaufokfXAtuxuYt0IxBthTVz/sgG3SDfiise5GMeiZnpnVdLK3/vrQ==,iv:7uFG+LP3SFnNMR7zfnsx2oZvQ6eG13lQCo/1oxYBl+s=,tag:CRP6Fp3s6gWhoqb7uXIUBw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Vx+LGj3DS7y0o+3m+xcq5uJQcu6xb91umGR881dPig/20z8jDsHxnjo3cvDAIX3+9hWYmeKSZoYw/5TwFV4stot3ZJMP5Kxr+25yqWZf5z+CoIh5yovlnv2jyb1PUtJfz9x6UMgeiZqUyuQBf0prnOm/Ww8aOS9FPZ2dTWZc6QNmz35eexZTEzk4SdBRbTJIZDbRu+j5hJl3zjiAjrFywb5Tl/zUeNOlEmqV,iv:CK4tIs7i6UhzHcIsIJ8EmeCyN1WtoGWSitYuPXETecE=,tag:F2B6863Yc4b/tZvTOsu6Ig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QnNPYVd5NDdoODVPU0Vu
            WmpsVXc5ckpWRUQxRTdjMEUyTFVIQ2plcmxRCnhONUxFM2RKalp4azdyb09MNHhi
            Y3daajRaVUhKdjJvKzhQT2txV3ZtaWMKLS0tIGdtUkRCY1p0bjRqZ3UyQ1BPdWJE
            Uk54MW1LSDdZNDF2Nm9rYWtzS21aMGcK6l2L3h2H4/t9FazMHhLz/3Tceolpbc5v
            8j85DduLFLiR6hw+oWdsXMCLMt4UCD7xHfbhuV3/8aNK6CxKBl13IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-07T18:15:11Z"
    mac: ENC[AES256_GCM,data:WPMY0EOI3Da65oCctFQ9+5XyYGxEWBHtlT51HNGlWnwx4VnaCVgh5nQGHaW8l24LPTy0WResrKb47LyZ1a64otQIoBeY+yxiarHUnxzjbNTipf7FbJw6N0SkIxthQScoT+8gsiuri3TySrTPISaJ16YWy3f0n+mk0SMVD5nZe6k=,iv:bI4GKln35zPJWHwhttMaT/w8okFYjVH/WLiVwjqu50g=,tag:hzqOb73Yg9qCdGH5mdBWkQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
