apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HVzeryjGSavk7XR5wefl5c/AI1JT0fyJ3NKpcksA09QC/nfJmRSodojg9M0PVdnczygfVGwsy+ksjT6m0yU8z9oZw/NNU9GARIF8qLUSQ1H709svpcPLs16KLPHR/HV9gpmT/gZkcbB9JjrEYFwEeoMDQ2eNwomFX1SXVRWy4wWADc31Mww27Qg1M3eHWRLRayx0E7YZHFBMlFmdvARkgSNRDp6fC7NX3iVkf4UVr6OcCL5z3DNoBJNrP0XrQCU6swCHmJm55LowWlEXpwCiQxug5cCA/sTDrbjoWRuGq6/UyoNz0Tje5IJKRTDZe38yGBSvANQHCBG1HQ9Z8AGoqcFdqT8irCRvNpjWHFNHq9lj7EyqJVZtHtedavMsvYa6,iv:QcWXU+NsoLE4LMXkvwn/t3iNbViyjWlHnlg/s9KdM6U=,tag:cKdv26ZSTRpGgPFUDETDYQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:xaC6pZ40jYgrEVVZI/5/KhU8zCzAIg2Ung9srsndmc5jNRPZwL9avUTJYcB7fMVfaVL8mqAl3lk3Kzkq8mEjJTjnIgKfWFzrYsjckyd9bGJL8HRM8SjDpfonSEsVDk8eQwDL8dtM8AL348fUG8zH3JU7+1nI5JBKp9Jg5DDTYtjKmDfyM+84Va3v2rIplkDeoIxf0tmQDfYB4q4pRGq7AAZlWgwauMdClwn2nQa6l4rFXcbvyO670BZikaex+m796Hx1uAiNVGgXJxw+IA==,iv:3r3o1Wiv8LIpdX92s6+IyUUUAh69V8gnhYPLs72ybio=,tag:NJXhoTqRp8nqwk02Xd1UvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:WJha9IovZZF2NNM+fL5XoVUuAtSjfRGaccBqZI8YohjAqJl0n3Ve8blSDZMSAmJyTD5O4KvnaRk+jrNdxWNKj4TGzyrrwNrK/C3mHzZXpVQ4JHyjFWE7+wQyFIUVaZlDemmECfPjaJzZN3Pg6oh0ywkTEvExIsxvivoBl83fKTsxLJCzbubcNuaI1qjGHow0Ao38694mUbIcIjptDhWZ2gLjJvOuxd1oWsp4,iv:XApvRin0SGwbFRfxJc44NjMyxmtnqnCrkrzimeCrqsE=,tag:10P+66uX/h4NG/rnfNNs/A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTjR6MmtaRjZNQWhGTWlj
            ekcrcCtSTkljMVBKN0lPaEJGTWlWVFI3SUhJClQzajZWVVMzVXdKYkJDTVlnZUpP
            M3V3UTdUMXpLK0xGUjFzRUtxOHhzdTQKLS0tIG9OUithZXhEeG5mdXBUQVpSZk9u
            OHJzOEQ0bDhUY1BmWlhUSGdjMU9XQkkKEnWYjk8/vxVRtVEfwlSF4zJHsllQ7+da
            Ybse5IyWc3Wr8fBYRlD+a7+inTVsM8Lp7VYNF+vGt0J9yNbA3A2KeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T23:06:13Z"
    mac: ENC[AES256_GCM,data:YbZBJK1iMMyv3f8WbF8xvEeMyDvsQ49LKv3CtovS5tIG/AfKt2W/Zk00hu/iOdrtErqX5KA7vtz97dOnBDQ8ITRAMX6dfCgEUJuNCtX4K5S67KTfgWBbA/qgeXBoOCgFbfEcBbUC11isCYRG02M5hH9KhQYxz7SuXRb6oPjcdUM=,iv:Hx1ZI45JQovBlSgXn2BrrUGfaZAYfVfl7q3GSzXaBy0=,tag:LNA2fq3uH7yCrRiNTlQk+A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
