apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fYrvZiBj0K1zR42986Bv8g5WVN+ek1M6G2utRd8niciAfNxf56+tAjoqFLuCdS3F7qQepe2TxC856zRQsqkZjzllYAfQ2F6YDlc3B8DHNa4d4uNPOsp46qjAVB4eopPIIMUK1r27R8LVIBjV4UgzIj5AWl1PSYnMeAdgKenQ6it0s724n1UBQsGuiTjPz6spM1ny6cJaGjYkySuZGlgLIcaV2Rx5nrDwIsewg/eZu+IkO2DbSf//AvNsQG8yt/DN1RWOt22YEKeXK+ysFOaIF6USmpJKPe3wpDTxcY3pic2xLYAK48h2ubq2g8IjzPy+cS4m0YEPphigtzfHEQrzfpDXXbK3SL1tHPS7+99vJUarna+rTwSuZXpbxmmVKmua,iv:uTukB4TIrWEuo9gkJNq3T5pXvHd9Ehjmeli1W+t6GOE=,tag:Bv7YiJlvTMTLCyfm3S+edQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:8v6uS6URHDP5pak5LM18GJ9vM8lW1flrXDB5QCI1jXp9Ps8s3Ph92DxGIBCEAb9vHj0IRHyoOstkQpPIoxGYiU8dXpjfBNCYzB8chw+I+AWWPw6Aw9VNIS5IUE5h8ZFx/iNNa2eZZ4ZwKz9PlreVWg2fyjd8Vk9cqnJR5/uCj9w55ZeeiR2P62Asn1Z6WKFWEQ+bbaPbK1aPNy30jUCQR8c1w3opDkDVNMuC6EyW4qPbzSsODqxguTpBQ/HSe/rkCJerf4RLc4Sl7ZH+Mw==,iv:Fhx9qvDeb3UMCl6JW4qywBYJaAb9jqDWQvfitSUFfPE=,tag:u3bjkoy32+eVZl3tPiDmqQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:M/1agMnu5LDE3Hm1wYIynyBE4320rBpMwlHewDdc4LHrfr2qqx9oLAz8XJ3R38bKtFi9qGtEcvMdt71t8LPIryVZzLVf97qqozZwcQ/+/M4rKdw5kKBJuQvs4+GGgTZkx7VnG5w6/NR0HdRptPHSTTvx24kbsZP4IYFjXm5TzZFOOYXzOToEuGqUvxN1oRExwAo4KFmt6sim/CZgF6Gg6SIeaaPstEeTfCOV,iv:iwG1DRpGH2K7krDxG1KR/JcD5y2OHCz60uvFWcZLalQ=,tag:cXGKL3BRypcR+BhW/SGMFQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YjBIM0tUTURWemkxdGRh
            d3gyczJuNnZleDdvZm4rdmFqWENSSzhiYzNrCjZFYVg5MlNyYmhQei85QTFFY2FX
            WEZUYk5INjlLWktUYVhMZ0VMVjBaY0EKLS0tIElqMTN2R3lnU2l6Z0VUaFVnUGxY
            cTdkTUdYMkd3OUVnelkxeStNZFBlNE0K3GyCfAWvW5ZFrD88NC009rpc46z6/i8w
            unZSeoysCQsJTE5FQKthco/t+yWfoxFIEQ5x8JZU8sTeoPYNEN86qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T00:49:54Z"
    mac: ENC[AES256_GCM,data:oOPHMv/auaiuegTihWzsWMqk2NtGnMKlfoYv/mWUraWJiAANdlP/PcJT4fU5Nl7TM4TdJl1BGUU5WyY9Liqy7/hloq8zezOrcN3hXk3qG1DN+sdk65lTV+jZUXSjwB98NUOLIp5J0tuixiqxkZvvc8c0tPbaGNgmJWI6UKpeqmA=,iv:LfA7ddWeD12Cc5GH3EOtV0p1sfU0GvNuI9cxFJn8nR0=,tag:3joov9NWXVbitSnZs2g92w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
