apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:X/kg2ugCvN5qO7asSKnOHujhkkDMh6ckiRyEFIg37/hDL7u27OImOHxX6TN5BjCWNbzW4eYliSx82pVs1C+zU395bIqaINeb4cbdTLOCqprHUqamZm1ImXln73RPqm/p9x1zupkX0kTtTEigkfyvJtp5586lecP6l6bhzwapbEWbSCg9Q2FmoHklAegvUI3Hw23SeSyopVf2OioN0i2zCH21ZFEEDcbXAD0Ub7bcPGjeFkEc+okqAYsySlp9yCeqkg6oYXW/Bm5K8K6HKq8fSn6vUclDQKbCB1T6qtFEiUAI0Tg1WdHi2D+Ks2Jau3AMaQYOQWD79fim8Cs2AlglA6ED70SsZm8yu9cyAJdKsX1VHp4E/KqAzANCZK3hI12L,iv:aI2Rn1Y3QoYN6DsO8z6QXOld5uIw1uRDLlBkBhfmWeY=,tag:fA2Lijuy/hSQ0ODt7vQuxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Q5jWI9DAXAvMxmQwOYS4261FyMw2T4xhwoxqxRZs8mgsIQ/xBu+CdJmHK1srHGnwwHPyVQPkLqWZGQc1EHmwNiIBXFgXgOvRY4nvmth3DhmwcquEVlg10hCTZgEW3zQR7thSu8ojhlmWE5us8YU4YQx+/8uzuqTuZrsBwAH5lcNWMDP6SRQcOSUAaNF+gUcPFDYPYznPkOWdUAAaO3u6wr5kAGsxVoPbvysyh9r4GFm1Ad3jXP+YOGrq40WwzI/r20aVY7tIaeat7oyEag==,iv:THBtBsWmgu4wqa+b+R2dqf2BKmKMaTjcE3bONf2VUnE=,tag:BrTBClhB71A32EbJzverIQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:FYKZGHKA2S6Hbh60QhIfzE1MB4E1dHzHazyrn0ySumzb1qE9a2UrlWrQURieh6QIxRRRtyDmKyyPhaA74DW7wnRBt/kQqGgJsnYN6p8psBbGJAxBobMZKTCzhcZuBrtr3y/WlCDyKDmY8vvcuJMwnlRfMc3ZDi5FOY6upq1+4eMmPSc9RBaPlbE/KnNfpnfPrpB2MSQxIqkBO1QFGQauTwk/KT8vm8XvMxbk,iv:UxD2bffLccpUAfFvwSGhsobagLsni2NZ2qeK80eiMx8=,tag:o75na28nT4+j8ix1FCnAFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M21jTDI4MnlBd3hQU2E4
            T0RNUjJCenZHNE1ZVEFhSHB2L3N6SGxjMWhzCmV1QWY0SVVqYmdmSlpFUjc0RXZX
            OUtHRmlwTE4rMkNJb1NSMFViSEkrMWcKLS0tIG9vdFp2UWhvQ0lNcFFCazJJNUhy
            YTZrWWRzR3BYbDd3b0lmeWRaaDNid0UKiwuCicmHfH1nNgwrk2r8wJQnKkBTSV3u
            eJDfhfg34WFERFe6ZjqStzSLYVXUc6cq9rHOMNurwgOoRtIKRb+Lpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T18:18:46Z"
    mac: ENC[AES256_GCM,data:ouBMs+1X7VxQ1cucOHp6rNdwDiUeJLhFuGYXGM4qmk3PtJcEQDzW0CofibOG6MOOg8CWWezt7nWzQNFt+UIDSfp3PV1tnkSSrVIo7iJ2fNe30VrvvJ3AoXPM4FYlhAOoNjYFza6di7FEtLDZszgnQY86/hXp/sr+9BuCvZaCOYg=,iv:IBJFn7X9LP7xnxKWXPKScEqAMDM6l9gASiCVS2j0xOo=,tag:vr0XeHjfDjTq7P2Ajc9ZxA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
