apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:P8ho+a3N8EoZg8TQG1HAJcXBH7OI4LcFwU6LAaqOKA6D56jntB5dFNCzO/8q19bnEfZ8G34dHmVZ/o6h83wFxrWqZ12xLhbjS0fnbIhi34JYmjmI9gGEo4qc6CLGD2uOt/x1gV0/vrB1ObwXtFmkSnFpio8PrGMqdIx1H0KL2OpUOX9JXBDsiCjmg1OP+f+JnKwH+f/lf2vF6FmRQ+VrUxvYw6Gnm4IyZhl9qBhqCX0rQ+IaDQ/uiw40FtUXJ5a48NKebNSpYBC/KPWkWGwqJ5GTKKjJH5nCOrmcLa8vboNu8WPK88lmWhbY4iIFDOu0ie/rRRRzEaDyQoN3jQSWsbvhsx2KvzKg6wZIc0Cr9o0RnWeX2MxPOJqs2j69yKqB,iv:tx1OMKP4O15oyeMdyU3BX9EER17dxgaXEshlh2v5qPI=,tag:Js+UsURzEJX9CKnGZ9IdJw==,type:str]
    identity.pub: ENC[AES256_GCM,data:++bQX7s6e66ggqSyzNCxBAvqaGrAR6mjvzz0apK6DYdqVT3756cQ9l5YJKfm6lL+v7dVSg5nCnyIQDJtWDpAOdI/Vn+35stInk4ZuqJ9uOuceECqnt/qznqj5bdDrgOpKUhEj/+ctiCgO7dSJsGjUtNkn5d4gVZamxvNku++/qL3zsBJNmLm9fhDRIZOjPuk0JqmtSAOCDvSvvr0PUAYEuCb5LITeXNzCBtmeMTSPzPqKLX1TbPerjRXpmWaDI7/2EGymqxVcDeK3qpbbQ==,iv:FuK0qTtWyf+fUUJSnm+B1I9Q+MAB/leshRTPRHWiTm4=,tag:6Z7yqHrwZeHrjc8aIwV1hw==,type:str]
    known_hosts: ENC[AES256_GCM,data:H+33jb/J8rielJbZaSKQzJqr/M0wZliqKgTTAIl4WenGPp3m4YLJdFMWQaqf/3pmHuqv6UrWH0GMSMbkZT+U8AMKaRT7lbclc3dQo5FYXFkfh3rzjHNpZv7V6iwgLqhnNiMTd/3L1v7dhOpNclQZtW1OHF8U8ZXbhjyKq2TJ5+kypk/3NRYI2JrxU7ygM+FiMApRO3mhQR23ail1MvBj8qRYD8N/ZGcLbV9K,iv:R2t1MpFqHc8bMqkm2roIDF/zaLAumB0iSekLI4fBuP8=,tag:Mck2aCupBuNPlOJ31wbiVQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWk53Rzl6VTVSL3EzYTZX
            SDdFN05HUGE3cUd2eG9YaFZlb21XVSs1TXpNCnZjSGp1SmdvUWR2bXhabjgveDIr
            dEZSMWZlOXZBNVoxK1g0VE5jL3NTVkkKLS0tIHBqYzFMem9IeXlXR0dNR25aeGlP
            Ylo4V2pWSVRzL3Q4VXJsWEozeXAyV2MKzqp3r1POFgLaq+NeoFnNPHo7hSyBuzf3
            YFI8DnVpg/WnZw4f/C/REds9SdbnrW6QT5ke7f1YR+39axh+kKn3gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T03:02:05Z"
    mac: ENC[AES256_GCM,data:vE4CCfDSuoCGskXMJSnE1Nk3J1G1p3a272RvRLBGVSWkctilS4CzPhsywqu/pB2FkTsTzv6sxysG2XlKsShUD60ZxhHrLBmvm7QfBWGU0yJnc/UAUyLoA9Si+2glu68OWFpJLD6WdnoPIDUXgJGZ0+rHBiYEMahPukqJMrHkeQo=,iv:nZ91h3ptTPKhrvUr9I9fLBW4C6Ce4lBKLAn78j22yB8=,tag:NFziW4i/LVamXvqzAO+mqw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
