apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wYOaSEelRHLGUduUtKw6/VLszPIeLy6UvNKVv39vXnINUy75a04U2s4SmtBcAxh33mEQaN9i/qbmq6SpN+/fo4MKNMcIBlhtxmhLeA8twqO/nB4yH8lGojVx6T6oKh/6hWyA/tUC5w9d8fUnoARDLRTTyx2/sLCVNiFoudWyIro81Lg+wPEHeumTIX2fP/zxe5+Y7JaicdV6HVtWknHWL77kTQI4QnS3Zkci4XDZU+SzE8ug4FpIE2D9y9BZFEm6rN7poX2DQuavWlj6vY/eD5Ma1A44eNDQVJ+ar90xdvE6BnKosaoWSDky38PO+GqxUwosEz6/TafG3j3OL0KR2krPs9APbrKRIqC1QiJZA7HSzGad+yHz4Y/gJx5s4Nxq,iv:I2MSzGpWmIcpUZOu9/zVCyoNLBe6JApDb/T82ZEFN0o=,tag:e7nx2VNq7ObKoqSg9BKxVQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:t9JzY/G4P49UIxyLqVo25FLl7stCIxTmZTBdS+CLnSDOn3l32iFuG1D0EQCbZMAwKiuaprCX/hTOANwrnPBxmWZF62qb1/T734nN+PTwAUukCVABtNqdkTPtwKG2d6ks/2NVpvzlAeMvpKMkCf9a2lMpvIW8Tv4xkbg8YZr8JmO2rVGG0+RsHAvJexOBZVVg/Sf1+hYL+kf2nnifeL9sAwzQe83JknUOPEGolk2fSjAvFhe7hIZBM17/yqZLz4VtmD8Mltx2HYhepKvOOA==,iv:RCSfvWbSSh4lAmDGz0wmBNkNEqBA+A3NaW1ER0JHC0g=,tag:er29XFWlCCVUxV+TiZw2AQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:KSvYUR9a691CIM4L3/WzcDKuGZLkuHO5/C2kqhByu56WZJZ7oRJ5tnl7Mtc0titZrh/HxmnShgDmIO29XdXYjeUyhFPyhlI+gwE4+7awFfTiKG/4mgQBMQwzE5MPugpZPWGxWsyVXR3TIVk4wJmmnTKqwK/I9tVgeJQPSFYrdkeyCqAm+wN/vtSARDPuOop6B/rUj7ZRs5yQZJ0YER2p03CzodPHDRLs5hSs,iv:udWA3ShctBqhTPi/wgH0nqoAZPMD5kwktTbfTAXiFWw=,tag:0yvDCNcY6eKKH90q7uiv8Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ042VFNFRmNFZ2NHWGly
            dmNsdTJEaDVqNVVwQkx6V0Nzdy93SVpaaWtrCi9RY1k5TGh4MndNYzFiMmZGRE9p
            VzJLbnZKMG56cGg2b1VkZVRUbkE4TVUKLS0tIEM1b2YzREd0Ykd4U04vdlUvZ3Nl
            YmdkV2xZR29NZEEySWJrU2VvaXp3VE0KnnK4M/OBWL3d22OrmC2GIV7PPyfihA0A
            Aezr+OSvuAjSyuyAv7h5DiPoq9Jb8eWZnbAdfBfm8Ros2YEvt0Ab5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T23:19:06Z"
    mac: ENC[AES256_GCM,data:Q+0RZo0aY34knCJeNE9c/swFai8zsWRCHyf+8SKJBCzIoACyy4pdlEMo8Q3qAHksmEAnlepZSUcpD/pU9PnkVoXI5UiBVwya9eMUpMB6DbagIR+JqZALdkQXoWGy2/lomlD3ImG8zQFj+rggPTDxirNEyd6QMfCiqwv7NDujfNg=,iv:j719CT7P3Q6DLDl6h/dkxbbK/zbr8WGtZWTHEHrL124=,tag:JokINSMUiBP+eOeIVHDxcA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
