apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IIxwPaGQ+NI5VX3IhPAUVnS7C6lYLslMVTCsa+lUAkpA5MSYg0wFBYpkoscITJOyFyErx6TqHIlwAwdlVhUE/1ITZFR8r7Dre3SCPQxXhJDOdnn0+2g0fnJNfa1jSa7jEDFdfGPGD3KaVW9MHj10vKTPZdLBnWizvr6DcpwZ/FbxWKms2jormFQiSeWYGxYfqA1XMsL9PuSFr2dZLodxzX/hebuMQsmUX5xmWePXOd096rDIc2AMhn8JqKKr5e3GCc+LCG1Sfb8wE/Mb7OCoqwwd+Iea5RlK+/6i7g/MxqUw7oChzepgRyXfFrzjvB2NsrRp/h0sfzk1I/5jIrsG5C9l5aTZlkEhY0xa8FVuapB5t7Bemd66iMYfXC8tFLHv,iv:vWBzLfshpy30xlLonOM1KwaOFpxNhzMh1b3YnCmqQwY=,tag:pAiZ01SSlllCT7GbIsHxUw==,type:str]
    identity.pub: ENC[AES256_GCM,data:RZtza7rgI2lmzA250k1BHLzAyJtiGFAdeH1IAyMWf8TOG432ByKnyJRH9RdxpzTh1nZQmif9IqBt0C1k5dpBjvLDD6JdreBiTbmbYYZrM6AnjvB52US40xQxlXLSAknBey+uin4c/4C1gcM6LDI4IVe1M9xmL1P0qVFBtujCdRPAY334blqCXo7GMwIioGHbgUkJwUpqVooEbr639TzRqzD3PdyNAqkt7sCE1qn5P1ou0dBNrk+HUtyTzKPzbO9jN/nKhSrhcVhAQ+3Chg==,iv:rVJaSbilq9Ljmr9JKTlD3mEb6UdNMnPPmWsJk7lgE1U=,tag:5vq18WOkBb5AvYHcX8Fcxg==,type:str]
    known_hosts: ENC[AES256_GCM,data:kOYyrAuGGRkhUgolpjgfnaV8G+SGhV6wxpTrt0z1fPpKr24a39C2SjmczAQi41TjWfwqJGwa4olsMtPjHL2NKRkiZcPKA9gzA0N8l0aAiJp724WMlkNh/mzEyh8NBFMd1OciVbyUQw5D/yo8pOgJuFZpROldpUSwK6+dDURvoI0uMWJRtGaDT/pmrk8dvR1xPIllEnn25hJmbFsXYaFcsBi65gW9XuPg+ON5,iv:oEq1IcVmL04XOqCdJuH/F3DOnkB9ooAKvulkzifLDZU=,tag:1FpPt0sxSXvC8hs2hAJY9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVzNBMU5NSU5oKzVmeHU5
            bmJEKzJTRVd2UFNJdmRzYlgrMlNGQ3pFRVJrCnZ3bGR4L0N4c2N3d1BPTWtNS1Q1
            UC85WklBVEQvQU00Q3VqS3JYS2JlOHcKLS0tIGx0QTdYemRBODVNNVN3ZnpMWlVN
            bEhYT2RwYnl0b2ZRZHl6UnlQZGVtMGMKfhMJrPgnkKr63Cy8nJaIx3X8m+GreQom
            9sVroz69gosOw1v9IEY8hCLLwpXJcv0i6yUfgnsKYqNIJbk2NFk8nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T02:07:24Z"
    mac: ENC[AES256_GCM,data:RJXidKDQpf58hOTi7GZ/MF31Q+9FUTQuZ3GNznef9TCxSrkZ4tuq4QbLC7ABBlTEFpr36frcLA6R9qTONfWm0Tx+WgriVpxheLdUOBkiem67R0hhxkHqHUkDUI+0l0MikICRfFoQULuYXr3GrC3Hh80f8165Dw4MOlJS4dF7cu4=,iv:F5xroe1CgULQskyxWWdi/IqnYpBaYr6sQPYQSht7Zlc=,tag:i3rCYuXhCZtB2WClpnnujA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
