apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6fO9HJwkE6YvwEG8Eje9KlzrbrMF6shyH9sASYUW8VbyM/4MAsoNuWqy3fNPbOiB5RDhsueVbIIIiUy1mzebmEUrvYLewZxQjDKLfPMH3h0KXIvTImp0yXCGkh+3kfOm7n8/ATvoQ9TZrdtYAfkUZwaf157P3cqKNEi/DZrXV5D0MCVgP8w3NknupCWjezeMYDVFfLYTX3JGhqLHn39lmFfE1UzYUQ7/x+7i5en9coJuuXMbHiy1EiW2kSeceeUTHqK6s7qihdWQjsad4kX5a/yarcEQuG95y/3cZHLVXGKyDA5VzeN7CQ9+k1aPTSrK3NgBcmtwpI/GXDMDiB3zRh1hHssTqPSpqMrSnl7whS1kNhwxoyz9WaulFPMnzTxh,iv:YxpFkG1FSFytLgCf263/xsDG2XaY7DE/FMppA1JNSn8=,tag:y+bEvh+UJl9l2oYOYymQ7w==,type:str]
    identity.pub: ENC[AES256_GCM,data:2BbA+9xaU7jMJwxpwbRKLPvDge40SkZtSy6FHG32togFVk81SbyjoUSZ6+4dHa1sq6ekT9FchmjK3oiJpdE/b6oWnF8yNqJ3j9gzQ7XaS/xDgTn1gJcVWCRhHwGHsoZqbfJDxYdOUUf73QxlUkk0UKvjepORnPVUDF2mx5QCPSolJHJ4GE1UbDqSnq1Ytgy3ORQzd34m0Es0XV5pSP+CP33yumFVGIr7W4lnOXV7hw5G2tFO9f/N7sCHGIXnTSWsUaNpCW+QMNX5Z4DLmw==,iv:W59UWFBnRm7kVkP0PBjMupantsEEFsJCukNrKTSV00k=,tag:RAn6pfq1RBmXvcYdv1Uxog==,type:str]
    known_hosts: ENC[AES256_GCM,data:aMbEGjbMe1PorPrn96/XpIaGvrwazZVyDOulSM45Nh3fUBn5qrWx7cMFPofCFfyqaJ43V6ZqGx8eKIHa3Ch40dz/tGb2bAgUxgXY24bGx9LhXQnq0AIGuX0CCck5soT0sI5GhqGLh3yqY9SaFGxU41ovK0N6FElWOiyEtCJSR6qcKyteq7GrD91mcSJUvncahn68SXbsKYf4gcNVi5L71/FtTr27oYILM2Mp,iv:kWU6WjKPp1qNMkTZzwNguCT1sC3eP4Wx2Mlh8UjBdw4=,tag:sG4w1+2XUOr40Rp0pl1aSw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOWxERzlZSWFVR1ZyZGFH
            SVZtSVltQkgyR0hlVzZ4cGVGNGpOd3AxY0N3CjlpQzlLNWhFOUlpODNVU0NLZTRy
            TTlNMnNBRExvMlZtVzBzUlkrMTJPQzAKLS0tIG8vVkNCS3poMzd3VjROZkFpQWI0
            VzVoNE54Y3JwcTdUc2ZsZDgvNUJhV2MKBIHU+nWg6tTWXfx+r3yKcbVujVq91H5g
            VUCKr+hDr77bcXp4h7Kx8qSrmmMTtekR0KwT/WOGrGTv5fUHE3IiYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T18:35:32Z"
    mac: ENC[AES256_GCM,data:HuZ3sdszAS59cfMnS0fzIh6TCLOVifTSSFYXbgdp2IDUM2htK0tgKX2VS9yHAXKEWkpBtwC4gf9l/uscWVpcsQScRZwmVOAXD36qqHXatquBslteTQshL/mMG5YkGp9SvhRq49BNki9b6x0jRYKOuhSElbm/anqJSWwtP2/C8+s=,iv:OUIDXo8bzpaYnjH0upD29/hT/q5ma6nstevD7hrC6EM=,tag:wXWf5VDi4p1OAmrYcI23fw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
