apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Nu+XEvNjR18Hmy9aDAsRB8sT2h7uMghpgaiqu3fnPl4nYEVa/7EnxRuRaAckBBfSe0qk0cLh+N/oMoBpdmharlicRsctKbeTgQhMWUxws2PCksWfOR20ymw4mzrZfLje9ORRz6cnhpieUTnhDV8lIHm+LTT0y6B7gB1GGQNpB89pRp2I44W5iQrljZLlUcnVQo/jB5VsFOnt1q9YxmHb4udj+4DHbXJcI0XpxdWhv2N284E0S9/gIIA026sM9yQ42cBnKVwzA/8MsFS0NYYvHSEL5HCIX2hDjfZv9NqZSC6038h7erWN45QHd6s0HpZxP9gwyYrGaJmFTV7miGWrGxAfNBxijGJPGzYkEi4UagI50BS6WzbXITHnhQid9Boc,iv:miJs8Bz+7LvF76LpBXSmBfNalvNTKjTjt23ko2BBPDA=,tag:6i5Jh1POJwf+7XegoVuvKg==,type:str]
    identity.pub: ENC[AES256_GCM,data:2w2zWrDCqZ64/OZp1EmhYl2LIr1H2+UDz8X3aC9iSJmpXeikqJHM7fwGds8wr9H0Oh7n6b9f6HRbQnHwgRT/a7BAL7z9Gy6vubQlO/1zP0TV80knLS49o1xsw6+nIJeUuVrW2UEj/6eNw1YkcwVqHFK3emXxkFZEXffEdttZ5lJAhpPEAvRkjuUyGnv3yuTocfAHbpazpqgDN7mQ3Qv5h3cWeUtN6vFiJp/Yj75WBbI/f6ECwnuloul1RZX1Cx3/371xEGNxoRWegv2GTA==,iv:CwjWUaXqO/Sh5QZ1EphKZRoBSDv1NGvY5V9wBn7KMAc=,tag:XxDUX9XTW9meLzs7S92yFA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ctKUpnNIRs7Ry6OMrmfIfmqzpJmBYD9B48fB6DxjSZf+/uKSGVblFTbGNegcm/fBUHNnMf4wuNXzZ6kwbTz2Hr0xZBWFaVEqMdrXlNfMvzEPZUyBnSd3HhdY7R3j8vHj2sa13mPu8xRUw7dI3ppHFLhoMQnSpx2Q6tyb2Sk1634uzDiZxBoEdnJTzMrKri6UOBO9Bai8wTt7oUYTcJKHhv0HFFZ/MSQtlvc1,iv:OR8tUT0I4hfQvg02aXpAm2XgTOD1a/dA6kSAQyIvTuU=,tag:2UBAnNsnTiB8CITg8Vj8Sw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Mm4xM1NCT0dvY2JvVndw
            WHh6enFhUTVKNUltY1NrUWJ2ZE53RkVlQjBNCkxkL3Y4U01DaVU4V0U0NStLK0Rn
            c0ozTkxhN01JcG9Zd3VIOExHU2M5MGMKLS0tIDRxV3F3RExKYnFrVUFrQmpxNmkv
            WWRxZjJvZTNWWWpWOXk4Q0x6b0JNWkUKEje+H/FOeCxvXF9b0OtomIdUl9Y1VUE4
            zuJjbGOD42hodyePQh1ZxFIr/BFJv+SxCi8Q3WUlEihPiTKhdpZxFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T00:22:59Z"
    mac: ENC[AES256_GCM,data:0ICGFu3rTrGgibwxavqEr6pzPJD0BZ4bQXxenIPTKx9IAHMv0V2ts9C1FyXMZOB2DdZrM9PthPWxLqSkt6yEcIB2NmCBcUTM10KnUOQeHG6O5oeESNPTviIke4y75FLDzvYkS1AXlQra58ED4ICoSWhphrlIstMM8L57kyMO8d0=,iv:BdOPFmyvyhfmnsc5LTXoh4REwTDXKEJkX4cVpYcVXjU=,tag:EabiAJ2JuhDi5Ci+n3qoXw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
