apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IPE1thcPGcaSzJwYnZKHqhCDHgWkp8WMAK2SF4ya4y4d3awDASMKVgmyNiWgwla0N38ojQ//GJiB8Ba2k9zcydfvETF0xlq3OwaI7p+VLKfi8B7ixJ9S8QzBzhBCPp6rgdPMVbOQUk6tBGe6LpbElegtWPGBsJNtiUAgDr7LXJbFFkZF/vaJAGo43JyrSQ7WGWdJuwZgR7GeAk/teB4ClmogD/sHJmNyeOYVNHFRyQ6zFbR6CDd1rSei5z0ZR3Wb/5+EDNGU6L+p4RlEr0l0cQ31uw2+VLFQGSi7XMYz8f4i7zHKGkl6OZc7W6wrHiHr93gWTbLsj7uuk4sNRPbsaoJaYYtrg9vx8wbwiy90V23hqUIhJyENXUUXOsUBkuxo,iv:Gr4ylmPrdjTo+gZN+nmA88cQbOECC+YZz2tFb6X2sjo=,tag:21T3HNdKbZSySfAgiHL4mg==,type:str]
    identity.pub: ENC[AES256_GCM,data:tA8F8PWrV3dZjzLUOoEKhxYm5l36gZisfO9B+KO6f61R6aShV3XUfcfXS2zeS3l02LUSd6G7fKLrAo4EImS+w6hYTr9mR1bKWDKyVLgKd6LJQb27XwZ1cjOJdC+6Tyto2OieqabP/+sA5iHeMO0/E5oPAAZbWP9C13dwxTpjFDe4i4KTbGdAyjIeocZ+8IDroim4iGJGCnetIY6cQs5aULpRSqAEhl9NPowPfsAzq8tecthf3OuFJ0nwflVq3WbPLcK9b/gJ0wur+D7WlQ==,iv:L9Zc7OqZeZ5rvieT2bHraX+ei5+a6lFYXgG+vX2prN4=,tag:iZOEfWp4q+L/5/eak8MSrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8SIXK0tb1jSpDwhncjivrTn01baBnq9rnBfKzCvIUl68yKWAH81zOCBNeV9XSyZtwExiVKtviOKioymZ2ZiUPagJiCXd5Hy+VxjyoZ17WTzKN9YtT4zZgYdSx3G0JG9/S6rBxboh5ENdKdATHaV5F7ghvNen2O4t2AvIlioSSrLaBSFOtHT2rS4XmuZMmgYswAr57dOnYju/rDblQFyJG5l8XybuUtzXwSGQ,iv:RPGkduNLT2Q3Ab/mHsZRXzO54CtXejzeeI2/lC54daE=,tag:Dz5eMTZyQeadWVLZp8mUSA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RXpWelBCbFdhN1EyVFVQ
            MzkwRXM1NFg5dmwrUnRtL2pQRWtNckk0VG5vCmEvS0p4NVEyaXpubVVhUTMraWgx
            elBnWTdnUk52Y1ExbDVsaEhYTFBkZEkKLS0tIDhEUVdKQUoxcVhPS1RjeWJQbEN1
            MjlhTmJDRnU5ODhKMFI5MzNuWUlaNU0K+P+lAvYzsPuWzd+xU8VD46aIGmDRvBjl
            XV+1kRQ97atQ8OKPgBwgLz2ywmlI5FVRR9v5fKkfCOMJ6Ctx8q9+4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T17:38:03Z"
    mac: ENC[AES256_GCM,data:0J4yLg8Rje1gE/LWrNhK4cmjWxhbD2K6GbPG6OAecEq36n5uLvZxHC2t4KG9mJHHJ76ErmiO8yidYn1X3YTPVVhEysejVzJ6bYsQpxMqKyvm14DDHR/pVIlhWCpDVaSzpgoHnuzsCBNdvK0Abc0vdq63UM0m1Pry89nZf6/Qnyg=,iv:DaybeJqfTP0AsNbFJAHyG3HaurSlBKXlDKK7KV4qm8c=,tag:SgozU3+NN3XxywTOP8dS3w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
