apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gUJY1c5wZQDEVBu/gHkTPfXtpiNQf8bF2mqTZi2B68iPKIbrKX5nBJBTFGevRH0XZJO/vqWAy7TBEWalSGl7kY0PIbdXjAl/VsDrZ2Zn/loXpqT90Wp+Z8Jke8rrmBzGzCa1NBepWi8AeHBycJfzfjvTCv21O52jC2usXkH8ASEkIYW9l2LP/FLciQfWouz5drZoqB2h4hGYvABnk+xzo1kqN42+wmEjgMKiB9VZZjtLQucGXn4ZpKaHkZ1+jDIpbbM17EMNa/2bUI12rjSOBnxO+l6b8DSkn6cXz74ZCD8wuMLxLcDwYWFQrzn2yppLGrPMso08x7i+x8LVuEsygEY5hwBOwFjJrj7ZFQSF1uXqKEcl2he1Ya0UkWdMtO9i,iv:2McjjL708qjejqCQJFoLZWnr2FPzM8ZSOIdnPbITdAs=,tag:UQc0BFDqSnewztaDxcByvw==,type:str]
    identity.pub: ENC[AES256_GCM,data:8R0ydWzNmkhx4KgL7FCWxY8dv0JnPYA81hZus557T6yIfqLR8YP/ditzozMUDn4tGO8g4lt5jx0CYmJHxpFqxEDSRaSNMeyTQX9xF5bSPowmxujTBtq51tjHtLTl+sS4vAqPLDI0sTeSnHn8FBn2wNXHxvjD4YP2wQ7mclt/GpIFCM/C+p709ZkHpCfQ6tr2QYxxaHR5ieITQz95osfG7lPl5rC6eCCAvCZ/Sg0HHPJJ9kXSSw9yB5zjP1+7yu7rfogO/0U0XrfkmEGHJg==,iv:8dnoO9wqYEdlNjbQqhwi3bJolWd9/rTxDw+E4MwWbD8=,tag:EMfWMwAdgJb5Zag1s09DTg==,type:str]
    known_hosts: ENC[AES256_GCM,data:4iKCvnAf3AbkQ0uxD5h1LAoiR1yHniqupb8kNpIReFmZOJ6yGK1Vr0OFFAoBDmUwakKMdpfldnEW7bf2FCKViuVsB4BoAfJdl4UH4B3maEqvUTk7CehB9AsJ0panWj3vxjNArq9SDWNDlXH0Xwqza5teBupbiARjoGD7KleKoNdme3L0Xp1BxcE1SESgTrrhlnnFg49vynPz6g3g3RfHKaHw8B37hihmWQa2,iv:XREq5Fm8nkOXiRacQ560Pgyq0DN8lwYZb/kEcxTwcrA=,tag:mZ6TmnNKWcwElZ+PpH+PzQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNExheUQ3eUpGd1Jtd2xH
            WHNFRFh4eDhUc2dDWWpuL1pBK2RVc2tjTXlFCmcydUJrRklwREZtdzd1N0NiQlNz
            cklwWFQ2UmpBemZLem9zcmVsYmtQUUEKLS0tIDFGYWhEWFE1eDRieTRiNXBxWGtt
            cklKNWZFSWM0VjJJWHNWd01XY1FEcEEKwusRRTdwan0C6aEXzbl6EajUSbjcSaUO
            et7RaIupEX2/ktxDCTFDCGjTbwgXsnWo5zxVczZtgZZoNHICaybKdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:31:29Z"
    mac: ENC[AES256_GCM,data:pHAXgvHhxvhGED+/EXmkaiEoRA9kVvCUur3nHLkGZIs4B377RgylFl2WCVNjWEVQvHsBs1vtdPEzKS6YcX4UP7iLzl4VQI2DASFz2p5qTPna4UKzvKOh/TCnlhL+gSm28I2BIKvbS5BreqIyIg+VxFrD9uvpaf88IGAYD9xi4Rc=,iv:leNL5U62+BdeDHnkdm76NUHMI7tOUQWhVJpOpvQRMLc=,tag:hhmJ1oqw2p8NN6iILZOKqg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
