apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wVDJMq7Q5Gj+s2gurIT15US80ei1GypYHH4JeXvLIBTOizjsJ6UDNqqC0Q9KqXTUn26dSmSE5btUEn+oPgoM+fLAJ1Uk4KqHmw/z6Efqgx18X2GwiSYpDFm+cGErfIVQ+MHgGVB1zuhP22jXIOZa4EHb/5timZNjIDLQWbsJq7JwIYlm0m3QA3CeAi2ZdOLZM1pzz1kgGN2vWHg/4HTLbN05kJ9/g9n71XBZWgE/+rhKkAGJeVuAdL40Z9zQbfoWfGrE3LWTg2l4d62FwXMRbdysQV6bpZrJAqUhOPoci8ot6wSpUG4T8/H/UntI3PQABVjGE8UuNCNoOaGWW30ZLj4Q8yDZ035Iarj/4AfLT4r8dNFOQCPOymAKf0vQ2Jd4,iv:+rX77Dbd40gGFriNRZYwcFVkNuqj01fFBwPYO34xabc=,tag:foGLouXV7HpLNkl0vRWPTA==,type:str]
    identity.pub: ENC[AES256_GCM,data:cqUS4jmfA0aOkEqTEmfElnknJP1VOYPz1X5A4ctCKuviIAxrKK0h5H8f/9xp1WNcDDVVka7jKyTbVllGU1u8pcJIdnhJTMrW4AbVlriFiW2ke76cfu70FxmxKI8fOE6Oi73T2EKEKlWNeb0aq0rMEdPNeYn0Pls7Tgw3PBpAk13EzUxgEODmV9P7rM898YOB+GbLA74nVdM05a7rNVzZFVVgS6WfxQfTz3fwaW0RLa1MpZ+57iXy1SsE4MFB0irQJkSsHormjcjfS7WbAw==,iv:LJ7b5R4mNTM0bidVa+RnDfcc97qenUhm0hh4Qz17rwA=,tag:NIQZzGNTkEC3/wmv/RV7lA==,type:str]
    known_hosts: ENC[AES256_GCM,data:nLTxPhTgZEdiA6hOf2SgAaeTbJYTdxd8Yf6HUy+T35wDDaFlwICYgLEfg5z0X+huRYZ5tDM85SxWjhwKLXnsriJuhu1kw8FdPLt7nD8f+N0O5wohIcyDb8KzMb1CUu8wHLPmQO1CcvVVo8En5imOdPXpROfcamoWhfTRVWoVveN7Fd2eMXTinyrJJ7rbUksCK9WO8BrRLJLvAYy4qNle7XI2gWXjV7EwyxCl,iv:URPADtvoC8sFLPJQroWwD61umecrc+eBZ2act3V5D2U=,tag:jpV1pZ7cEkqhxSDYhY4qBw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbElSaE5SMTFETE5TNFNV
            MEk1R0VNWC8zZ0c0NWhWckRqRG41WDE1S2dVCmhqbUp6ZmFvbGJtSFUvU3dtb2I0
            ME1vMkxUMWswcmgyOFUxZWplaXV3ZU0KLS0tIHFmNVh2bmhvZENNQytQU2QwTkIw
            Q1M4emxTNTdTNENCTlRxRVgvV24wT1UKzIopfApvaOlKdQePoSAj4an49xY3bQKn
            yRkr8502eLae5mOwYI8LqBppYIU4HWTVbvfPGwP9yI6hT4U9SzWgcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T05:41:32Z"
    mac: ENC[AES256_GCM,data:Ajzsyl1pTnNFacA+K7lY4pXjxKCPzUaBfa/RtixrVDIxS9YwqsarzbiQGcZPyzRZzMwZAk0O6FiHyHulLd/M/ZV8oGkPqF+Hqy1Xb+I2Mirm4bn3GhJ83FAPMIIDwEGVUaA3Tnjr8DlWnVVboS3Girg+YphnbDu7Dpv16u5UW7g=,iv:XdyjHFovU03EUuSb5OhOJBAaLbagfqUTl9mGqNeeVZE=,tag:liEm0k8LjXUxIn8kV5t5VA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
