apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ie+Y6brVr98vfzypYrVE6vVGBgSnxRtHWYN+UUc+MG+vziDIkXQsDuAiRsTXFjql43+ttxquf2uUysI9RsXu06LGsMhhvQbsuLu4GKUWNXiKS9sGIH1OLXix9KhYfSOL8jBsJh7jREVxpsYFjmsquTi2xCyHG1e76keviyj0RRrIFTvDrHkLb/4goZIe7yykfsgNoJt55xcJx0roFi3seZzIdVGKMtvQJrYm5T0UXLaWTOXDO9uZF43p4dvcHZKd1lsAG5Wg4LjinZ1IDebeS6+nhBmiJeOXiwq3jPgcYxm+l7EUecdBoMT1PWRgx+6Bbf0kXMggpMq9ZLF5Uz24Yc7TnpHnvtx8PGomJrnzMY/xnDzgjNgbAC2HGPSbAZwV,iv:1XXmDKQMDalH7AA+cDw3MSKerJ6QhG7HFnDC0M12hDg=,tag:bMAa9RUz9DYoYDukyzIJmA==,type:str]
    identity.pub: ENC[AES256_GCM,data:vvz4Hve3qvP1LBndDHqjqPxuoxio3hGXqfOBcCfWjIR/PPjMB58SfIwX80Bb/7aEOrStbp0mlJlbK0Zse7n600pMtStn4rx9LEQdX1YEs2Gi2yv14Yvh5WhpMF4yAEsUcotEggI3pE+eG8ofoZoOAYlABk4MPWgU4IoUo1ODqIXhxUqby85CUW5hDyetAdPnG5O9VOCSPy1I96pfHgAdtnoR0rxMs8pcFvK+oZJ2LcvXoizm23UxcBkwN8DXNiMpaBt4O/eScBrEv8wk6A==,iv:wuytf4eCnvIPRBukXhtR4rl9T1371C7qPOrOcA1JKg0=,tag:2rpM3AR74ZcbcSPUa2A5bg==,type:str]
    known_hosts: ENC[AES256_GCM,data:TkTt1qRqI9LfCEUdshksu13K700lIEauwFxwNYDQkLRrhu3FhH5iYP9p3godeH+FysqIE/Xjn7Gn+wfIbQfBSTPnUA76UNZ/EOx3kTI8RX+LOJndqoLXu1pgzUHlFetElXGAfonUoRsIholgaAi6tsikWViCwmjLS2tPqt6sPOHZT0yL0lPw1G/X5BZ4REr+R/x6tMy157QxmDH4fj9myR62ZjGSNdMygs4H,iv:6r1kPHZuDGkXqVRXPLGFigZiISwUjenVCm5kT2waUwA=,tag:NKtWyIrS7bymSR+EUiavig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmuu0hp70v9576e7rmmf97dl8k8527yykjwtr95py65yc9p0pcvqmu9038
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdkpYMkdlR05QWG1OeUlv
            ZGVUTTlPQURaQ1hSTEJTaGl2NFV4US9CUnpJCitNYkh1anFsYmpEQ1FQY3pVNFNk
            TlFHc1ZKdElSYnRHays4NzFEaVRzcDAKLS0tIDVYVWtaeGFFaHdySzBnM2trOGFj
            cDRiU0tFRU93NVdNcHFZdUNpU09OZW8KXrn+fyoESUVuiOcIFG695JKWTXGQQ0MT
            viB1XWCHbJ6cmAciBJzGb/2WPuyVOy5+KWNelahgrXlQyDrKIDi3Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T00:04:01Z"
    mac: ENC[AES256_GCM,data:R+GCMHlHhukBT1dCNevauR4hqOEMOxvQa83B3KBOeYGfS99vNjiXXSTq42PaMDSENaQslCGd8KyZeBymvpjSdqVHhqYLFiGIfiXf9+L22S4dcYbNlBKrJpGSe81gHSslIq33tNTasfTwJa/0TS/ywMEWPJOvbQMLDuwodqiIPHM=,iv:1SukBVRaWzUdg0/A69UV2W/NE7DvzkOl404jqP/8Fh4=,tag:80cYwsUfHJFTxUpBfIhnKQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
