apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualserver
  namespace: actualserver
spec:
  interval: 15m
  chart:
    spec:
      chart: actualserver
      version: 11.1.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
  ingress:
    main:
      enabled: true
      integrations:
        traefik:
          enabled: true
        middlewares:
          - name: auth
      tls:
        - hosts:
          - as.${DOMAIN_0}
          clusterIssuer: domain-0-wildcard
      hosts:
        - host: as.${DOMAIN_0}
          paths:
          - path: /
            pathType: Prefix
    persistence:
      server-files:
        enabled: true
        mountPath: /data/server-files
        volsync:
          - credentials: backblaze
            name: svr
            src:
              enabled: true
            type: restic
      user-files:
        enabled: true
        mountPath: /data/user-files
        volsync:
          - credentials: backblaze
            name: uer
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10293
            protocol: http
            targetPort: 5006
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  path: /
                  type: http
                readiness:
                  path: /
                  type: http
                startup:
                  path: /
                  type: http
        replicas: 1
        type: Deployment
