apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefox
  namespace: firefox
spec:
  interval: 15m
  chart:
    spec:
      chart: firefox
      version: 14.0.14
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    addons:
      vpn:
        env:
          FIREWALL_VPN_INPUT_PORTS:
            name: FIREWALL_VPN_INPUT_PORTS
            value: ${FIREWALL_VPN_INPUT_PORTS_1}
          HTTPPROXY:
            name: HTTPPROXY
            value: "on"
          HTTPPROXY_LOG:
            name: HTTPPROXY_LOG
            value: "on"
          VPN_ENDPOINT_IP:
            name: VPN_ENDPOINT_IP
            value: ${VPN_ENDPOINT_IP_1}
          VPN_ENDPOINT_PORT:
            name: VPN_ENDPOINT_PORT
            value: ${VPN_ENDPOINT_PORT_1}
          VPN_SERVICE_PROVIDER:
            name: VPN_SERVICE_PROVIDER
            value: custom
          VPN_TYPE:
            name: VPN_TYPE
            value: wireguard
          WIREGUARD_ADDRESSES:
            name: WIREGUARD_ADDRESSES
            value: ${WIREGUARD_ADDRESSES_1}
          WIREGUARD_PRIVATE_KEY:
            name: WIREGUARD_PRIVATE_KEY
            value: ${WIREGUARD_PRIVATE_KEY_1}
          WIREGUARD_PUBLIC_KEY:
            name: WIREGUARD_PUBLIC_KEY
            value: ${WIREGUARD_PUBLIC_KEY_1}
        excludedNetworks_IPv4:
          - ${EXCLUDED_IPV4_0}
        killSwitch: true
        type: gluetun
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - firefox.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: firefox.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      downloads:
        enabled: true
        type: nfs
        mountPath: /config/Downloads
        path: ${DATASET_MEDIA}/share
        server: ${NFS_SERVER_0}
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10131
            protocol: http
        type: ClusterIP
      proxy:
        advancedsvcset: false
        enabled: true
        name: proxy
        ports:
          proxy:
            enabled: true
            name: proxy
            port: 8888
            protocol: http
            targetPort: 8888
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                CUSTOM_PORT: '{{ .Values.service.main.ports.main.port }}'
                FM_HOME: /config
                TITLE: VPN
              probes:
                liveness:
                  type: http
                readiness:
                  type: http
                startup:
                  type: http
        replicas: 1
        type: Deployment
