apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dell-idrac-fan-controller
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/dell-idrac-fan-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

