---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qb2
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.1.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  postRenderers:
  - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: qb2-qbittorrent
          patch: |
            - op: add
              path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
              value: 1
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}
        
    qbitportforward:
      enabled: false
      QBT_USERNAME: ${QBT_USERNAME}
      QBT_PASSWORD: ${QBT_PASSWORD}

    service: 
      torrent:
        ports:
          torrent:
            port: "${TORRENT_PORT_QB2}"
      # gluetun:
      #   enabled: true
      #   type: LoadBalancer
      #   loadBalancerIP: ${LOAD_BALANCER_QB2}
      #   ports:
      #     gluetun:
      #       enabled: true
      #       port: ${SERVICE_PORT_PROXY}
      #       protocol: http
      #       targetPort: ${SERVICE_PORT_PROXY}
      # socks:
      #   enabled: true
      #   type: LoadBalancer
      #   loadBalancerIP: ${LOAD_BALANCER_QB2}
      #   ports:
      #     socks:
      #       enabled: true
      #       port: ${SERVICE_PORT_SOCKS}
      #       protocol: tcp
      #       targetPort: ${SERVICE_PORT_SOCKS}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
              - name: theme-qb2
                namespace: traefik
        tls:
          - hosts:
            - qb2.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: qb2.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      media:
        enabled: true
        type: nfs
        mountPath: /media
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}

    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - ${EXCLUDED_IPV4_0}
        env:
          # VPN
          VPN_TYPE: wireguard
          VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER_0}
          WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY_QB2}
          WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY_QB2}
          WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES_0}
          VPN_ENDPOINT_IP: ${VPN_ENDPOINT_IP_QB2}
          VPN_ENDPOINT_PORT: ${VPN_ENDPOINT_PORT_0}
          FIREWALL_INPUT_PORTS: 10095,8888
          # PROXY
          HTTPPROXY: on
          HTTPPROXY_LOG: on
          SHADOWSOCKS: on
          SHADOWSOCKS_LOG: on