apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: duplicacy
  namespace: duplicacy
spec:
  interval: 15m
  chart:
    spec:
      chart: duplicacy
      version: 8.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - duplicacy.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: duplicacy.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      cache:
        volsync:
          - name: cch
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      logs:
        volsync:
          - name: lgs
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      backups:
        enabled: true
        type: nfs
        mountPath: /backups
        server: ${NFS_SERVER_0}
        path: ${DATASET_BACKUPS}/duplicacy