apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: duplicacy
  namespace: duplicacy
spec:
  interval: 15m
  chart:
    spec:
      chart: duplicacy
      version: 7.0.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - duplicacy.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: duplicacy.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      cache:
        enabled: true
        mountPath: /cache
        volsync:
          - credentials: backblaze
            name: cch
            src:
              enabled: true
            type: restic
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      logs:
        enabled: true
        mountPath: /logs
        volsync:
          - credentials: backblaze
            name: lgs
            src:
              enabled: true
            type: restic
      backups:
        enabled: true
        type: nfs
        mountPath: /backups
        path: ${DATASET_BACKUPS}/duplicacy
        server: ${NFS_SERVER_0}
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 3875
            protocol: http
            targetPort: 3875
        type: LoadBalancer
    workload:
      main:
        replicas: 1
        type: Deployment
