---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  interval: 15m
  chart:
    spec:
      chart: sabnzbd
      version: 20.1.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  postRenderers:
  - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: sabnzbd
          patch: |
            - op: add
              path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
              value: 1
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    service: 
      proxy:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_NZB}
        ports:
          proxy:
            enabled: true
            protocol: http
            targetPort: 8888
            port: 8888
      socks:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_NZB}
        ports:
          socks:
            enabled: true
            protocol: tcp
            targetPort: 8388
            port: 8388

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
              - name: theme-sabnzbd
                namespace: traefik
        tls:
          - hosts:
            - nzb.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: nzb.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      media:
        enabled: true
        type: nfs
        mountPath: /media
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SABNZBD__HOST_WHITELIST_ENTRIES: nzb.${DOMAIN_0}

    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - 10.0.0.0/8
        env:
          VPN_TYPE: wireguard
          VPN_SERVICE_PROVIDER: custom
          WIREGUARD_ENDPOINT_IP: 172.98.82.146
          WIREGUARD_ENDPOINT_PORT: 51820
          WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY_NZB}
          WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY_NZB}
          WIREGUARD_ADDRESSES: 10.2.0.2/32
          FIREWALL_INPUT_PORTS: 8000,8888,8388,10097
          DNS_KEEP_NAMESERVER: off
          HTTPPROXY: on
          HTTPPROXY_LOG: on
          SHADOWSOCKS: on
          SHADOWSOCKS_LOG: on