---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  interval: 15m
  chart:
    spec:
      chart: sabnzbd
      version: 21.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: sabnzbd
            patch: |
              - op: add
                path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
                value: 1
              - op: add
                path: /spec/template/spec/containers/2/resources/limits/truecharts.org~1tun
                value: 1
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    service:
      main:
        ports:
          overseerr:
            enabled: true
            type: ClusterIP
            targetSelector: overseerr
            protocol: http
            port: ${SABALT_PORT}
      proxy:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_NZB}
        ports:
          http:
            enabled: true
            protocol: http
            port: ${PROXY_PORT}
          socks:
            enabled: true
            protocol: tcp
            port: ${SOCKS_PORT}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
              - name: theme-sabnzbd
                namespace: traefik
        tls:
          - hosts:
            - sabnzbd.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: sabnzbd.${DOMAIN_0}
      overseerr:
        enabled: true
        targetSelector:
          main: overseerr
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
              - name: theme-overseerr
                namespace: traefik
        tls:
          - hosts:
            - sabnzbd.os.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: sabnzbd.os.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 5 * * *
      config-alt:
        enabled: true
        type: pvc
        targetSelector:
          main:
            overseerr:
              mountPath: /config
        volsync:
          - name: cfg
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 5 * * *
      media:
        enabled: true
        type: nfs
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}/temp/downloads
        targetSelector:
          main:
            main:
              mountPath: /media
      overseerr:
        enabled: true
        type: nfs
        server: ${NFS_SERVER_0}
        path: ${DATASET_OVERSEERR}/overseerr/sabnzbd
        targetSelector:
          main:
            overseerr:
              mountPath: /media

    workload:
      main:
        podSpec:
          containers:
            main:
              securityContext:
                privileged: true
                capabilities:
                  add:
                    - NET_ADMIN
              env:
                SABNZBD__HOST_WHITELIST_ENTRIES: sabnzbd.${DOMAIN_0}
            overseerr:
              enabled: true
              primary: false
              securityContext:
                privileged: true
                capabilities:
                  add:
                    - NET_ADMIN
              imageSelector: image
              env:
                SABNZBD__HOST_WHITELIST_ENTRIES: sabnzbd.os.${DOMAIN_0}
                SABNZBD__PORT: "{{ $.Values.service.main.ports.overseerr.targetPort | default .Values.service.main.ports.overseerr.port }}"
              probes:
                liveness:
                  enabled: true
                  type: "{{ .Values.service.main.ports.overseerr.protocol }}"
                  port: "{{ $.Values.service.main.ports.overseerr.targetPort | default .Values.service.main.ports.overseerr.port }}"
                readiness:
                  enabled: true
                  type: "{{ .Values.service.main.ports.overseerr.protocol }}"
                  port: "{{ $.Values.service.main.ports.overseerr.targetPort | default .Values.service.main.ports.overseerr.port }}"
                startup:
                  enabled: true
                  type: "{{ .Values.service.main.ports.overseerr.protocol }}"
                  port: "{{ $.Values.service.main.ports.overseerr.targetPort | default .Values.service.main.ports.overseerr.port }}"

    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - ${EXCLUDED_IPV4_0}
        env:
          VPN_TYPE: wireguard
          VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER_0}
          WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP_NZB}
          WIREGUARD_ENDPOINT_PORT: ${WIREGUARD_ENDPOINT_PORT_0}
          WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY_NZB}
          WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY_NZB}
          WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES_1}
          FIREWALL_INPUT_PORTS: ${SERVER_PORT},${PROXY_PORT},${SOCKS_PORT},${SABNZBD_PORT},${SABALT_PORT}
          DNS_KEEP_NAMESERVER: off
          HTTPPROXY: on
          HTTPPROXY_LOG: on
          SHADOWSOCKS: on
          SHADOWSOCKS_LOG: on