apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flatnotes
  namespace: flatnotes
spec:
  interval: 15m
  chart:
    spec:
      chart: custom-app
      version: 13.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - notes.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: notes.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 1000
        runAsUser: 1000
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 8080
            protocol: http
            targetPort: 8080
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                FLATNOTES_AUTH_TYPE:
                  name: FLATNOTES_AUTH_TYPE
                  value: none
        replicas: 1
        type: Deployment
