apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flatnotes
  namespace: flatnotes
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    image:
      repository: dullage/flatnotes
      pullPolicy: IfNotPresent
      tag: latest

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsUser: 1000
        runAsGroup: 1000

    service:
      main:
        ports:
          main:
            port: 8080

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - docs.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: docs.${DOMAIN_0}

    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /data
        targetSelectAll: true
        volsync:
          - name: dat
            type: restic
            cleanupTempPVC: true
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                FLATNOTES_AUTH_TYPE: none