---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: overseerr
spec:
  interval: 15m
  chart:
    spec:
      chart: overseerr
      version: 14.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}
    
    ingress:
      main:
        enabled: true
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
          traefik:
            enabled: true
        hosts:
          - host: ${DOMAIN_1}
    
    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true