---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qb4
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.5.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  postRenderers:
  - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: qb4-qbittorrent
          patch: |
            - op: add
              path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
              value: 1
        - target:
            version: v1
            kind: Deployment
            name: qb4-qbittorrent
          patch: |
            - op: add
              path: /spec/template/spec/containers/-
              value:
                name: socks5
                image: serjs/go-socks5-proxy:latest
                ports:
                  - containerPort: ${SOCKS5_PORT}
                    name: socks5
                    protocol: TCP
                env:
                  - name: DEPENDS_ON
                    value: gluetun
                args:
                  - -v
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    qbitportforward:
      enabled: false
      QBT_USERNAME: ${QBT_USERNAME}
      QBT_PASSWORD: ${QBT_PASSWORD}

    service:
      proxy:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_QB4}
        ports:
          proxy:
            enabled: true
            protocol: http
            targetPort: ${PROXY_PORT}
            port: ${PROXY_PORT}
      socks:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_QB4}
        ports:
          socks:
            enabled: true
            protocol: tcp
            targetPort: ${SOCKS_PORT}
            port: ${SOCKS_PORT}
      socks5:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_QB4}
        ports:
          socks5:
            enabled: true
            protocol: tcp
            targetPort: ${SOCKS5_PORT}
            port: ${SOCKS5_PORT}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
              - name: theme-qb4
                namespace: traefik
        tls:
          - hosts:
            - qb4.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: qb4.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 5 * * *
      media:
        enabled: true
        type: nfs
        mountPath: /media
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}

    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - ${EXCLUDED_IPV4_0}
        env:
          VPN_TYPE: wireguard
          VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER_0}
          VPN_PORT_FORWARDING: on
          VPN_PORT_FORWARDING_PROVIDER: ${VPN_SERVICE_PROVIDER_1}
          WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP_QB4}
          WIREGUARD_ENDPOINT_PORT: ${WIREGUARD_ENDPOINT_PORT_0}
          WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY_QB4}
          WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY_QB4}
          WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES_1}
          FIREWALL_INPUT_PORTS: ${SERVER_PORT},${PROXY_PORT},${SOCKS_PORT},${SOCKS5_PORT},${QBT_PORT}
          DNS_KEEP_NAMESERVER: off
          HTTPPROXY: on
          HTTPPROXY_LOG: on
          SHADOWSOCKS: on
          SHADOWSOCKS_LOG: on