---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 9.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - root.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: root.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      public:
        enabled: true
        mountPath: /app/public/images
        volsync:
          - name: pub
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
    
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          integrations:
            traefik:
              enabled: true
              middlewares:
                - name: auth
                  namespace: traefik
          tls:
            - hosts:
              - root.cs.${DOMAIN_0}
              clusterIssuer: domain-0-cs-wildcard
          hosts:
            - host: root.cs.${DOMAIN_0}