apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: makemkv
  namespace: makemkv
spec:
  interval: 15m
  chart:
    spec:
      chart: makemkv
      version: 11.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    configmap:
      makemkv:
        data:
          AUTO_DISC_RIPPER: '{{ ternary "1" "0" .Values.makemkv.AUTO_DISC_RIPPER }}'
          AUTO_DISC_RIPPER_BD_MODE: '{{ .Values.makemkv.AUTO_DISC_RIPPER_BD_MODE }}'
          AUTO_DISC_RIPPER_EJECT: '{{ ternary "1" "0" .Values.makemkv.AUTO_DISC_RIPPER_EJECT }}'
          AUTO_DISC_RIPPER_FORCE_UNIQUE_OUTPUT_DIR: '{{ ternary "1" "0" .Values.makemkv.AUTO_DISC_RIPPER_FORCE_UNIQUE_OUTPUT_DIR }}'
          AUTO_DISC_RIPPER_INTERVAL: '{{ .Values.makemkv.AUTO_DISC_RIPPER_INTERVAL }}'
          AUTO_DISC_RIPPER_MAKEMKV_PROFILE: '{{ .Values.makemkv.AUTO_DISC_RIPPER_MAKEMKV_PROFILE }}'
          AUTO_DISC_RIPPER_NO_GUI_PROGRESS: '{{ ternary "1" "0" .Values.makemkv.AUTO_DISC_RIPPER_NO_GUI_PROGRESS }}'
          AUTO_DISC_RIPPER_PARALLEL_RIP: '{{ ternary "1" "0" .Values.makemkv.AUTO_DISC_RIPPER_PARALLEL_RIP }}'
          DARK_MODE: '{{ ternary "1" "0" .Values.makemkv.DARK_MODE }}'
          DISPLAY_HEIGHT: '{{ .Values.makemkv.DISPLAY_HEIGHT }}'
          DISPLAY_WIDTH: '{{ .Values.makemkv.DISPLAY_WIDTH }}'
          ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.makemkv.ENABLE_CJK_FONT }}'
          KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.makemkv.KEEP_APP_RUNNING }}'
          MAKEMKV_KEY: '{{ .Values.makemkv.MAKEMKV_KEY }}'
          SECURE_CONNECTION: '{{ ternary "1" "0" .Values.makemkv.SECURE_CONNECTION }}'
        enabled: true
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - makemkv.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: makemkv.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
    makemkv:
      AUTO_DISC_RIPPER: true
      AUTO_DISC_RIPPER_BD_MODE: mkv
      AUTO_DISC_RIPPER_EJECT: true
      AUTO_DISC_RIPPER_FORCE_UNIQUE_OUTPUT_DIR: true
      AUTO_DISC_RIPPER_INTERVAL: 5
      AUTO_DISC_RIPPER_MAKEMKV_PROFILE: ""
      AUTO_DISC_RIPPER_NO_GUI_PROGRESS: false
      AUTO_DISC_RIPPER_PARALLEL_RIP: false
      DARK_MODE: true
      DISPLAY_HEIGHT: 768
      DISPLAY_WIDTH: 1280
      ENABLE_CJK_FONT: false
      KEEP_APP_RUNNING: true
      MAKEMKV_KEY: ${MAKEMKV_KEY}
      SECURE_CONNECTION: false
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      storage:
        enabled: true
        mountPath: /storage
        volsync:
          - credentials: backblaze
            name: dat
            src:
              enabled: true
            type: restic
      output:
        enabled: true
        type: nfs
        mountPath: /output
        path: ${DATASET_MEDIA}/temp/makemkv
        server: ${NFS_SERVER_0}
      temp:
        enabled: true
        type: nfs
        mountPath: /media/temp
        path: ${DATASET_MEDIA}/temp
        server: ${NFS_SERVER_0}
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10180
            targetPort: 5800
        type: ClusterIP
      vnc:
        enabled: true
        ports:
          vnc:
            enabled: true
            port: 10181
            targetPort: 5900
        type: LoadBalancer
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
              envFrom:
                - configMapRef:
                  name: makemkv
              probes:
                liveness:
                  type: tcp
                readiness:
                  type: tcp
                startup:
                  type: tcp
              securityContext:
                capabilities:
                  add:
                    - NET_BIND_SERVICE
                    - KILL
        replicas: 1
        type: Deployment
