apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbitmanage
  namespace: qbitmanage
spec:
  interval: 15m
  chart:
    spec:
      chart: qbitmanage
      version: 9.0.11
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    addons:
      codeserver:
        enabled: true
        service:
          loadBalancerIP: ""
          ports:
            codeserver:
              port: 36777
          type: LoadBalancer
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      data:
        enabled: true
        hostPath: ${DATASET_MEDIA}
        mountPath: /data
        type: hostPath
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                QBT_CAT_UPDATE: false
                QBT_CONFIG:
                  name: QBT_CONFIG
                  value: config_*.yml
                QBT_CROSS_SEED: false
                QBT_DIVIDER: =
                QBT_DRY_RUN: false
                QBT_LOG_LEVEL: INFO
                QBT_RECHECK: false
                QBT_REM_ORPHANED: false
                QBT_REM_UNREGISTERED: false
                QBT_RUN: false
                QBT_SCHEDULE: 1440
                QBT_SHARE_LIMITS: false
                QBT_SKIP_CLEANUP: false
                QBT_SKIP_QB_VERSION_CHECK: false
                QBT_TAG_NOHARDLINKS: false
                QBT_TAG_TRACKER_ERROR: false
                QBT_TAG_UPDATE: false
                QBT_WIDTH: 100
        replicas: 1
        type: Deployment
