---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autobrr
  namespace: autobrr
spec:
  interval: 15m
  chart:
    spec:
      chart: autobrr
      version: 10.10.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  postRenderers:
  - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: autobrr
          patch: |
            - op: add
              path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
              value: 1
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}
    
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - autobrr.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: autobrr.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      watchdir:
        enabled: true
        type: nfs
        mountPath: /watchdir
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}/temp/joal

    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - ${EXCLUDED_IPV4_0}
        env:
          VPN_TYPE: wireguard
          VPN_SERVICE_PROVIDER: custom
          WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY_0}
          WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY_0}
          WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES_0}
          DNS_ADDRESS: ${DNS_ADDRESS_0}
          VPN_ENDPOINT_IP: ${VPN_ENDPOINT_IP_0}
          VPN_ENDPOINT_PORT: ${VPN_ENDPOINT_PORT_0}