apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-unifi
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/external-dns-unifi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

