apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: metube
spec:
  interval: 15m
  chart:
    spec:
      chart: metube
      version: 13.1.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - metube.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: metube.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      downloads:
        enabled: true
        type: nfs
        mountPath: /downloads
        path: ${DATASET_MEDIA}/temp/downloads/metube
        server: ${NFS_SERVER_0}
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10216
            targetPort: 8081
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DOWNLOAD_DIR: /downloads
                OUTPUT_TEMPLATE: '%(title)s.%(ext)s'
                STATE_DIR: /config
                YTDL_OPTIONS: '{}'
        replicas: 1
        type: Deployment
