---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: lldap
spec:
  interval: 15m
  chart:
    spec:
      chart: lldap
      version: 7.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    cnpg:
      main:
        mode: recovery
        backups:
          enabled: true
          credentials: backblaze
        recovery:
          method: object_store
          credentials: backblaze

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - lldap.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: lldap.${DOMAIN_0}

    persistence:
      data:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                LLDAP_HTTP_URL: https://lldap.${DOMAIN_0}
                LLDAP_LDAP_BASE_DN: dc=${USER_10},dc=${DOMAIN_TLD_0}
                LDAP_USER_DN: ${LDAP_USER_DN}
                LLDAP_LDAP_USER_EMAIL: ${LDAP_USER_EMAIL}
                LLDAP_LDAP_USER_PASS: ${LDAP_USER_PASS}