---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 17.51.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}
    
    cnpg:
      main:
        mode: recovery
        password: ${CNPG_PASSWORD_IMMICH}
        cluster:
          singleNode: true
        backups:
          enabled: true
          revision: "3"
          credentials: backblaze
        recovery:
          credentials: backblaze
  
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
            - photos.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: photos.${DOMAIN_0}
    
    persistence:
      profile:
        volsync:
          - name: prf
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      thumbs:
        volsync:
          - name: thn
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      backups:
        type: nfs
        server: ${NFS_SERVER_0}
        path: ${DATASET_BACKUPS}/immich/backups
      library:
        type: nfs
        server: ${NFS_SERVER_0}
        path: ${DATASET_BACKUPS}/immich/library
      uploads:
        type: nfs
        server: ${NFS_SERVER_0}
        path: ${DATASET_BACKUPS}/immich/upload
      video:
        type: nfs
        server: ${NFS_SERVER_0}
        path: ${DATASET_BACKUPS}/immich/encoded-video