apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: companion
  namespace: companion
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.4.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    image:
      repository: ghcr.io/bitfocus/companion/companion
      pullPolicy: IfNotPresent
      tag: v3.4.4

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    service:
      main:
        type: LoadBalancer
        # annotations:
        #   metallb.io/allow-shared-ip: main
        loadBalancerIP: ${LOAD_BALANCER_CPN}
        # externalTrafficPolicy: Local
        ports:
          main:
            port: 8000
            targetPort: 8000
          tcp:
            enabled: true
            name: tcp
            port: 51233
            protocol: tcp
            targetPort: 51234
          udp:
            enabled: true
            name: udp
            port: 51235
            protocol: udp
            targetPort: 51235
          satellite:
            enabled: true
            name: satellite
            port: 16622
            protocol: tcp
            targetPort: 16622

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - companion.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: companion.${DOMAIN_0}

    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /companion
        targetSelectAll: true
        volsync:
          - name: cfg
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *