apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shlink-web-client
  namespace: shlink-web-client
spec:
  interval: 15m
  chart:
    spec:
      chart: shlink-web-client
      version: 11.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - shlink.${DOMAIN_2}
            clusterIssuer: domain-2-wildcard
        hosts:
          - host: shlink.${DOMAIN_2}
            paths:
            - path: /
              pathType: Prefix
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10154
            protocol: http
            targetPort: 80
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SHLINK_SERVER_API_KEY: a1d07330-f254-4933-8600-0f9d89124d54
                SHLINK_SERVER_NAME: ""
                SHLINK_SERVER_URL: https://shlink.${DOMAIN_0}
        replicas: 1
        type: Deployment
