apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thelounge
  namespace: thelounge
spec:
  interval: 15m
  chart:
    spec:
      chart: thelounge
      version: 14.0.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    addons:
      vpn:
        env:
          VPN_ENDPOINT_IP:
            name: VPN_ENDPOINT_IP
            value: ${VPN_ENDPOINT_IP_8}
          VPN_ENDPOINT_PORT:
            name: VPN_ENDPOINT_PORT
            value: ${VPN_ENDPOINT_PORT_8}
          VPN_SERVICE_PROVIDER:
            name: VPN_SERVICE_PROVIDER
            value: ${VPN_SERVICE_PROVIDER_0}
          VPN_TYPE:
            name: VPN_TYPE
            value: wireguard
          WIREGUARD_ADDRESSES:
            name: WIREGUARD_ADDRESSES
            value: ${WIREGUARD_ADDRESSES_8}
          WIREGUARD_PRIVATE_KEY:
            name: WIREGUARD_PRIVATE_KEY
            value: ${WIREGUARD_PRIVATE_KEY_8}
          WIREGUARD_PUBLIC_KEY:
            name: WIREGUARD_PUBLIC_KEY
            value: ${WIREGUARD_PUBLIC_KEY_8}
        excludedNetworks_IPv4:
          - ${EXCLUDED_IPV4_0}
        killSwitch: true
        type: gluetun
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - irc.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: irc.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10061
            targetPort: 9000
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                THELOUNGE_HOME: /config
        replicas: 1
        type: Deployment
