---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qb1
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 20.0.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  postRenderers:
  - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: qb1
          patch: |
            - op: add
              path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
              value: 1
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: true
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    qbitportforward:
      enabled: true
      QBT_USERNAME: ${QBT_USERNAME}
      QBT_PASSWORD: ${QBT_PASSWORD}

    service: 
      torrent:
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_QB1}
        ports:
          torrent:
            port: ${FIREWALL_VPN_INPUT_PORTS_1}
      proxy:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_QB1}
        ports:
          proxy:
            enabled: true
            port: ${HTTPPROXY_LISTENING_ADDRESS}
            protocol: http
            targetPort: ${HTTPPROXY_LISTENING_ADDRESS}
      socks:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LOAD_BALANCER_QB1}
        ports:
          socks:
            enabled: true
            port: ${SHADOWSOCKS_LISTENING_ADDRESS}
            protocol: tcp
            targetPort: ${SHADOWSOCKS_LISTENING_ADDRESS}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
              - name: theme-qb1
                namespace: traefik
        tls:
          - hosts:
            - qb1.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: qb1.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      media:
        enabled: true
        type: nfs
        mountPath: /media
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}

    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - ${EXCLUDED_IPV4_0}
        env:
          # VPN
          VPN_TYPE: wireguard
          VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER_0}
          WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY_1}
          WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY_1}
          WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES_1}
          VPN_ENDPOINT_IP: ${VPN_ENDPOINT_IP_1}
          VPN_ENDPOINT_PORT: ${VPN_ENDPOINT_PORT_1}
          FIREWALL_VPN_INPUT_PORTS: ${FIREWALL_VPN_INPUT_PORTS_1}
          # PROXY
          HTTPPROXY: on
          HTTPPROXY_LOG: on
          SHADOWSOCKS: on
          SHADOWSOCKS_LOG: on