apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: makemkv
  namespace: makemkv
spec:
  interval: 15m
  chart:
    spec:
      chart: makemkv
      version: 11.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - makemkv.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: makemkv.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      storage:
        volsync:
          - name: dat
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      output:
        enabled: true
        type: nfs
        mountPath: /output
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}/temp/makemkv
      temp:
        enabled: true
        type: nfs
        mountPath: /media/temp
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}/temp

    makemkv:
      KEEP_APP_RUNNING: true
      DARK_MODE: true
      MAKEMKV_KEY: ${MAKEMKV_KEY}
      AUTO_DISC_RIPPER: true
      AUTO_DISC_RIPPER_EJECT: true
      AUTO_DISC_RIPPER_FORCE_UNIQUE_OUTPUT_DIR: true
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080