apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: playwright
  namespace: playwright
spec:
  interval: 15m
  chart:
    spec:
      chart: custom-app
      version: 13.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    securityContext:
      container:
        UMASK: "0022"
        privileged: true
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 3000
            protocol: http
            targetPort: 3000
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MAX_CONCURRENT_CHROME_PROCESSES:
                  name: MAX_CONCURRENT_CHROME_PROCESSES
                  value: "10"
                SCREEN_DEPTH:
                  name: SCREEN_DEPTH
                  value: "16"
                SCREEN_HEIGHT:
                  name: SCREEN_HEIGHT
                  value: "1024"
                SCREEN_WIDTH:
                  name: SCREEN_WIDTH
                  value: "1920"
              probes:
                liveness:
                  enabled: true
                  path: /
                  type: tcp
                readiness:
                  enabled: true
                  path: /
                  type: tcp
                startup:
                  enabled: true
                  path: /
                  type: tcp
        replicas: 1
        type: Deployment
