apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: debian-bullseye
  namespace: debian-bullseye
spec:
  interval: 15m
  chart:
    spec:
      chart: debian-bullseye
      version: 7.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - debian.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: debian.${DOMAIN_0}

    persistence:
      homedirectory:
        enabled: true
        type: emptyDir
        mountPath: /debian

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                CUSTOM_RES_H: "1920"
                CUSTOM_RES_W: "1080"
                DATA_PERM: "770"
                ROOT_PWD: "1234"
                USER_LOCALES: fr_CA.UTF-8 UTF-8