---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    defaultCertificate: "domain-0-wildcard"

    service:
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik 
              - name: traefik-dashboard
                namespace: traefik
            fixedMiddlewares:
            - name: chain-basic
              namespace: traefik
        tls:
          - hosts:
            - traefik.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: traefik.${DOMAIN_0}

    middlewares:
      ipWhiteList:
        - name: internal-only
          sourceRange:
            - 10.0.0.0/8
            - 172.1.0.0/12
      # DASHBOARD
      redirectRegex:
        - name: traefik-dashboard
          regex: https://traefik\.${DOMAIN_0}/?$
          replacement: https://traefik.${DOMAIN_0}/dashboard/#/
          permanent: true
        - name: rtmp-hls
          regex: https://rtmp\.${DOMAIN_0}/?$
          replacement: https://rtmp.${DOMAIN_0}/stats.html
          permanent: true
      # AUTHELIA
      forwardAuth:
        - name: auth
          address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.${DOMAIN_0}/
          authResponseHeaders: 
            - Remote-User
            - Remote-Group
            - Remote-Name
            - Remote-Email
          trustForwardHeader: true
      # THEME-PARK
      themePark:
        - name: theme-qb1
          appName: "qbittorrent"
          themeName : "nord"
          baseUrl: https://theme-park.dev
        - name: theme-qb2
          appName: "qbittorrent"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: theme-qb3
          appName: "qbittorrent"
          themeName : "space-gray"
          baseUrl: https://theme-park.dev
        - name: theme-qb4
          appName: "qbittorrent"
          themeName : "maroon"
          baseUrl: https://theme-park.dev
        - name: theme-sabnzbd
          appName: "sabnzbd"
          themeName : "nord"
          baseUrl: https://theme-park.dev
        - name: theme-overseerr
          appName: "sabnzbd"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: theme-sonarr
          appName: "sonarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: theme-radarr
          appName: "radarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: theme-lidarr
          appName: "lidarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: theme-readarr
          appName: "readarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: theme-prowlarr
          appName: "prowlarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: theme-bazarr
          appName: "bazarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev