---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.0.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false

    defaultCertificate: "domain-0-wildcard"

    service:
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - traefik.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: traefik.${DOMAIN_0}

    middlewares:
      ipWhiteList:
        - name: internal-only
          sourceRange:
            - 10.0.0.0/8
            - 172.1.0.0/12
      # DASHBOARD
      redirectRegex:
        - name: traefik-dash
          regex: https://traefik\.${DOMAIN_0}/?$
          replacement: https://traefik.${DOMAIN_0}/dashboard/#/
          permanent: true
      # AUTHELIA
      forwardAuth:
        - name: auth
          address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.${DOMAIN_0}/
          authResponseHeaders: 
            - Remote-User
            - Remote-Group
            - Remote-Name
            - Remote-Email
          trustForwardHeader: true
      # THEME-PARK
      themePark:
        - name: qb1-theme
          appName: "qbittorrent"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: qb2-theme
          appName: "qbittorrent"
          themeName : "aquamarine"
          baseUrl: https://theme-park.dev
        - name: qb3-theme
          appName: "qbittorrent"
          themeName : "dracula"
          baseUrl: https://theme-park.dev
        - name: qb4-theme
          appName: "qbittorrent"
          themeName : "maroon"
          baseUrl: https://theme-park.dev
        - name: sabnzbd-theme
          appName: "sabnzbd"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: sonarr-theme
          appName: "sonarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: radarr-theme
          appName: "radarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: lidarr-theme
          appName: "lidarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: readarr-theme
          appName: "readarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: prowlarr-theme
          appName: "prowlarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev
        - name: bazarr-theme
          appName: "bazarr"
          themeName : "overseerr"
          baseUrl: https://theme-park.dev