---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clusterissuer
  namespace: clusterissuer
spec:
  interval: 15m
  chart:
    spec:
      chart: clusterissuer
      version: 9.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    clusterIssuer:
      selfSigned:
        enabled: true
        name: "selfsigned"
      ACME:
        # DOMAIN_0

        - name: domain-0-le-staging
          email: "${DOMAIN_0_EMAIL}"
          server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_0_CLOUDFLARE_TOKEN}"

        - name: domain-0-le-prod
          email: "${DOMAIN_0_EMAIL}"
          server: 'https://acme-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_0_CLOUDFLARE_TOKEN}"

        # DOMAIN_1
        - name: domain-1-le-staging
          email: "${DOMAIN_1_EMAIL}"
          server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_1_CLOUDFLARE_TOKEN}"

        - name: domain-1-le-prod
          email: "${DOMAIN_1_EMAIL}"
          server: 'https://acme-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_1_CLOUDFLARE_TOKEN}"

        # DOMAIN_2
        - name: domain-2-le-staging
          email: "${DOMAIN_2_EMAIL}"
          server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_2_CLOUDFLARE_TOKEN}"
          
        - name: domain-2-le-prod
          email: "${DOMAIN_2_EMAIL}"
          server: 'https://acme-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_2_CLOUDFLARE_TOKEN}"

    clusterCertificates:
      replicationNamespaces: '.*'
      certificates:

        # DOMAIN 0 WILDCARD
        - name: domain-0-wildcard
          enabled: true
          certificateIssuer: domain-0-le-prod
          hosts:
            - '*.${DOMAIN_0}'
            - '*.cs.${DOMAIN_0}'
            - '*.os.${DOMAIN_0}'

        # DOMAIN 1 WILDCARD
        - name: domain-1-wildcard
          enabled: true
          certificateIssuer: domain-1-le-prod
          hosts:
            - '${DOMAIN_1}'
            - '*.${DOMAIN_1}'

        # DOMAIN 2 WILDCARD
        - name: domain-2-wildcard
          enabled: true
          certificateIssuer: domain-2-le-prod
          hosts:
            - '${DOMAIN_2}'
            - '*.${DOMAIN_2}'