---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slskd
  namespace: slskd
spec:
  interval: 15m
  chart:
    spec:
      chart: slskd
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - slskd.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: slskd.${DOMAIN_0}

    persistence:
      data:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
      share:
        type: nfs
        mountPath: /share
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}/temp/downloads/music
      incomplete:
        type: nfs
        mountPath: /downloads/incomplete
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}/temp/downloads/soulseek/.temp
      complete:
        type: nfs
        mountPath: /downloads/complete
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}/temp/downloads/soulseek

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SLSKD_NO_AUTH: true