apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stash
  namespace: stash
spec:
  interval: 15m
  chart:
    spec:
      chart: stash
      version: 17.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - stash.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: stash.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      data:
        volsync:
          - name: dat
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      metadata:
        volsync:
          - name: md
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      generated:
        volsync:
          - name: str
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      cache:
        volsync:
          - name: cch
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      blobs:
        volsync:
          - name: blb
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      media:
        enabled: true
        type: nfs
        mountPath: /media
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}${NFS_PATH_STASH}