apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flare-bypasser
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/flare-bypasser/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

