---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection-io
  namespace: changedetection
spec:
  interval: 15m
  chart:
    spec:
      chart: changedetection-io
      version: 4.9.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - cdio.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: cdio.${DOMAIN_0}

    persistence:
      datastore:
        volsync:
          - name: cfg
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                BASE_URL: https://cdio.${DOMAIN_0}
                PLAYWRIGHT_DRIVER_URL: ws://playwright-app-template.changedetection.svc.cluster.local:3000

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: playwright
  namespace: changedetection
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    image:
      repository: dgtlmoon/sockpuppetbrowser
      pullPolicy: IfNotPresent
      tag: latest

    service:
      main:
        ports:
          main:
            protocol: tcp
            port: 3000
            targetPort: 3000

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MAX_CONCURRENT_CHROME_PROCESSES: 10
                SCREEN_DEPTH: 16
                SCREEN_HEIGHT: 1024
                SCREEN_WIDTH: 1920