apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  interval: 15m
  chart:
    spec:
      chart: mealie
      version: 22.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    cnpg:
      main:
        backups:
          credentials: backblaze
          enabled: true
        cluster:
          instances: 1
          singleNode: true
        database: mealie
        enabled: true
        monitoring:
          disableDefaultQueries: false
          enablePodMonitor: true
        password: ${CNPG_PASSWORD_MEALIE}
        pgVersion: 16
        user: mealie
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - mealie.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: mealie.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    mealie:
      api:
        general:
          allow_signup: false
          base_url: https://mealie.${DOMAIN_0}
          default_group: Home
          token_time: 48
        ldap:
          admin_filter: ""
          auth_enabled: false
          base_dn: ""
          enable_starttls: false
          id_attribute: uid
          mail_attribute: mail
          name_attribute: name
          query_bind: ""
          query_password: ""
          server_url: ""
          tls_cacertfile: ""
          tls_insecure: false
          user_filter: ""
        oidc:
          admin_group: ""
          auth_enabled: true
          auto_redirect: false
          client_id: mealie
          configuration_url: https://auth.${DOMAIN_0}/.well-known/openid-configuration
          provider_name: Authelia
          remember_me: true
          signup_enabled: true
          user_group: ""
        security:
          max_login_attempts: 5
          user_lockout_time: 24
        smtp:
          auth_strategy: TLS
          from_email: ${SMTP_EMAIL_MEALIE}
          from_name: Mealie
          host: ${SMTP_HOST_0}
          password: ${SMTP_PASSWORD_MEALIE}
          port: 587
          user: ${SMTP_USERNAME_0}
        webworkers:
          max_workers: 1
          web_concurrency: 1
          workers_per_core: 1
      frontend:
        theme:
          dark_accent: '#6272a4'
          dark_error: '#ff5555'
          dark_info: '#bd93f9'
          dark_primary: '#44475a'
          dark_secondary: '#6272a4'
          dark_success: '#ff79c6'
          dark_warning: '#50fa7b'
          light_accent: '#6272a4'
          light_error: '#ff5555'
          light_info: '#bd93f9'
          light_primary: '#44475a'
          light_secondary: '#6272a4'
          light_success: '#ff79c6'
          light_warning: '#50fa7b'
    persistence:
      data:
        enabled: true
        targetSelector:
          main:
            main:
              mountPath: /app/data
        volsync:
          - credentials: backblaze
            name: dat
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10018
            protocol: http
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              envFrom:
                - secretRef:
                  name: frontend
                - secretRef:
                  name: api
              probes:
                liveness:
                  command:
                    - python
                    - /app/mealie/scripts/healthcheck.py
                  enabled: true
                  type: exec
                readiness:
                  command:
                    - python
                    - /app/mealie/scripts/healthcheck.py
                  enabled: true
                  type: exec
                startup:
                  command:
                    - python
                    - /app/mealie/scripts/healthcheck.py
                  enabled: true
                  type: exec
        replicas: 1
        type: Deployment
