---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  interval: 15m
  chart:
    spec:
      chart: mealie
      version: 24.7.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false
    
    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    cnpg:
      main:
        mode: recovery
        password: ${CNPG_PASSWORD_MEALIE}
        cluster:
          singleNode: true
        backups:
          enabled: true
          revision: "5"
          credentials: backblaze
        recovery:
          revision: "4"
          credentials: backblaze

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
            - mealie.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: mealie.${DOMAIN_0}

    persistence:
      data:
        volsync:
          - name: dat
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                OIDC_AUTH_ENABLED: true
                OIDC_SIGNUP_ENABLED: false
                OIDC_CONFIGURATION_URL: https://auth.${DOMAIN_0}/.well-known/openid-configuration
                OIDC_CLIENT_ID: ${OIDC_CLIENT_ID_MEALIE}
                OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET_MEALIE}
                OIDC_AUTO_REDIRECT: true
                OIDC_PROVIDER_NAME: Freeman • Auth
                OIDC_ADMIN_GROUP: admin
                OIDC_USER_GROUP: user
                OPENAI_API_KEY: ${MEALIE_OPENAI_API_KEY}

    mealie:
      api:
        general:
          allow_signup: false
          base_url: https://mealie.${DOMAIN_0}

        smtp:
          user: ${SMTP_USERNAME_0}
          password: ${SMTP_PASSWORD_MEALIE}
          host: ${SMTP_HOST_0}
          port: 587
          from_name: Mealie
          from_email: ${SMTP_FROM_MEALIE}
          auth_strategy: TLS

      frontend:
        theme:
          light_accent: '#8839ef' #
          light_error: '#d20f39'
          light_info: '#8839ef'
          light_primary: '#6c6f85' #
          light_secondary: '#6c6f85' #
          light_success: '#40a02b'
          light_warning: '#df8e1d'
          dark_accent: '#ca9ee6' #
          dark_error: '#e78284'
          dark_info: '#ca9ee6'
          dark_primary: '#303446' #
          dark_secondary: '#a5adce' #
          dark_success: '#a6d189'
          dark_warning: '#e5c890'