apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shlink-web-client
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/shlink/shlink-web-client/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

