apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gostream
  namespace: gostream
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    image:
      repository: webdevops/php-apache
      pullPolicy: IfNotPresent
      tag: "8.4"

    securityContext:
      container:
        readOnlyRootFilesystem: false
        privileged: true

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    service:
      main:
        ports:
          main:
            port: 80

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - gostream.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: gostream.${DOMAIN_0}

    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /app
        targetSelectAll: true
        volsync:
          - name: app
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      apache:
        enabled: true
        type: emptyDir
        mountPath: /var/run/apache2