apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gostream
  namespace: gostream
spec:
  interval: 15m
  chart:
    spec:
      chart: custom-app
      version: 13.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - gostream.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: gostream.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    securityContext:
      container:
        UMASK: "0022"
        privileged: true
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 10885
            protocol: http
            targetPort: 80
        type: LoadBalancer
    workload:
        replicas: 1
        type: Deployment
