apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jdownloader2
  namespace: jdownloader
spec:
  interval: 15m
  chart:
    spec:
      chart: jdownloader2
      version: 19.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - jd.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: jd.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: cfg
            type: restic
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 5 * * *
      output:
        enabled: true
        type: nfs
        mountPath: /output
        server: ${NFS_SERVER_0}
        path: ${DATASET_MEDIA}/temp/downloads/jdownloader

    service:
      myjd:
        type: LoadBalancer
              
    jdownloader:
      KEEP_APP_RUNNING: true
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080