apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qb3
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/media/qbittorrent/qb3/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

