apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: splitpro
  namespace: splitpro
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Montreal
    global:
      stopAll: false

    image:
      repository: ghcr.io/oss-apps/splitpro
      pullPolicy: IfNotPresent
      tag: v1.3.2

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0

    credentials:
      backblaze:
        type: s3
        url: ${BUCKET_URL}
        bucket: ${BUCKET_NAME}
        accessKey: ${BUCKET_ACCESSKEY}
        secretKey: ${BUCKET_SECRETKEY}
        encrKey: ${BUCKET_ENCRKEY}

    cnpg:
      main:
        enabled: true
        cluster:
          singleNode: true
        mode: recovery
        database: splitpro
        user: splitpro
        password: ${CNPG_PASSWORD_SPLITPRO}
        backups:
          enabled: true
          revision: "1"
          credentials: backblaze
        recovery:
          credentials: backblaze

    service:
      main:
        ports:
          main:
            port: 3000

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
        tls:
          - hosts:
            - split.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: split.${DOMAIN_0}

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DATABASE_URL: postgresql://splitpro:${CNPG_PASSWORD_SPLITPRO}@splitpro-app-template-cnpg-main-rw:5432/splitpro
                NEXTAUTH_URL: https://split.${DOMAIN_0}
                NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
                ENABLE_SENDING_INVITES: true
                FROM_EMAIL: auth@${DOMAIN_0}
                EMAIL_SERVER_HOST: ${SMTP_HOST_0}
                EMAIL_SERVER_PORT: 587
                EMAIL_SERVER_USER: ${SMTP_USERNAME_0}
                EMAIL_SERVER_PASSWORD: ${SMTP_PASSWORD_SPLITPRO}