apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: watcharr
  namespace: watcharr
spec:
  interval: 15m
  chart:
    spec:
      chart: watcharr
      version: 5.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - watch.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: watch.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      data:
        enabled: true
        mountPath: /data
        volsync:
          - credentials: backblaze
            name: dat
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10684
            protocol: http
            targetPort: 3080
        type: ClusterIP
    watcharr:
      debug: false
      jellyfin_host: ""
      mode: prod
      signup_enabled: false
      tmdb_key: ${TMDB_KEY}
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DEBUG: '{{ .Values.watcharr.debug }}'
                JELLYFIN_HOST: '{{ .Values.watcharr.jellyfin_host }}'
                JWT_SECRET:
                  secretKeyRef:
                    key: JWT_SECRET
                    name: watcharr-secrets
                MODE: '{{ .Values.watcharr.mode }}'
                SIGNUP_ENABLED: '{{ .Values.watcharr.signup_enabled }}'
                TMDB_KEY: '{{ .Values.watcharr.tmdb_key }}'
        replicas: 1
        type: Deployment
