apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: projectsend
  namespace: projectsend
spec:
  interval: 15m
  chart:
    spec:
      chart: projectsend
      version: 13.1.13
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - send.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: send.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    mariadb:
      enabled: true
      mariadbDatabase: projectsend
      mariadbUsername: projectsend
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
      data:
        enabled: true
        type: nfs
        mountPath: /data
        path: ${DATASET_MEDIA}/temp/projectsend
        server: ${NFS_SERVER_0}
      projectsend-config:
        enabled: true
        mountPath: /config/projectsend/sys.config.php
        objectName: projectsend-config
        readOnly: true
        subPath: sys.config.php
        type: configmap
      varrun:
        enabled: true
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10127
            targetPort: 80
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MAX_UPLOAD: 102400
                PHP_MAX_FILE_UPLOAD: 200
                PHP_MEMORY_LIMIT: 512M
        replicas: 1
        type: Deployment
