---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-restart
  namespace: plex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-plex
  namespace: plex
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["plex"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-plex-binding
  namespace: plex
subjects:
  - kind: ServiceAccount
    name: plex-restart
    namespace: plex
roleRef:
  kind: Role
  name: restart-plex
  apiGroup: rbac.authorization.k8s.io