apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapdrop
  namespace: snapdrop
spec:
  interval: 15m
  chart:
    spec:
      chart: snapdrop
      version: 10.0.13
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - drop.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: drop.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10215
            targetPort: 80
        type: ClusterIP
    workload:
      main:
        replicas: 1
        type: Deployment
