apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multi-scrobbler
  namespace: multi-scrobbler
spec:
  interval: 15m
  chart:
    spec:
      chart: multi-scrobbler
      version: 7.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      backblaze:
        accessKey: ${BUCKET_ACCESSKEY}
        bucket: ${BUCKET_NAME}
        encrKey: ${BUCKET_ENCRKEY}
        name: backblaze
        path: ""
        secretKey: ${BUCKET_SECRETKEY}
        type: s3
        url: ${BUCKET_URL}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          middlewares:
            - name: auth
        tls:
          - hosts:
            - scrobbler.${DOMAIN_1}
            clusterIssuer: domain-1-wildcard
        hosts:
          - host: scrobbler.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backblaze
            name: cfg
            src:
              enabled: true
            type: restic
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 9078
            targetPort: 9078
        type: LoadBalancer
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MALOJA_API_KEY:
                  name: MALOJA_API_KEY
                  value: ${MALOJA_API_KEY}
                MALOJA_URL:
                  name: MALOJA_URL
                  value: maloja.ix-maloja.svc.cluster.local:42010
                PLEX_USER:
                  name: PLEX_USER
                  value: ${PLEX_USER}
                SPOTIFY_CLIENT_ID:
                  name: SPOTIFY_CLIENT_ID
                  value: ${SPOTIFY_CLIENT_ID}
                SPOTIFY_CLIENT_SECRET:
                  name: SPOTIFY_CLIENT_SECRET
                  value: ${SPOTIFY_CLIENT_SECRET}
                SPOTIFY_REDIRECT_URI:
                  name: SPOTIFY_REDIRECT_URI
                  value: https://scrobbler.${DOMAIN_0}/callback
        replicas: 1
        type: Deployment
