apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shlink
  namespace: shlink
spec:
  interval: 15m
  chart:
    spec:
      chart: shlink
      version: 15.1.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    cnpg:
      main:
        backups:
          enabled: false
          revision: ""
        cluster:
          instances: 1
          singleNode: true
        database: shlink
        enabled: true
        monitoring:
          disableDefaultQueries: false
          enablePodMonitor: true
        password: ${CNPG_PASSWORD_SHLINK}
        pgVersion: 16
        user: shlink
    ingress:
      main:
        enabled: true
        integrations:
          certManager:
            certificateIssuer: domain-1-le-prod
            enabled: true
          traefik:
            enabled: true
        hosts:
          - host: ${DOMAIN_2}
            paths:
            - path: /
              pathType: Prefix
          - host: shlink.${DOMAIN_0}
            paths:
            - path: /rest/
              pathType: Prefix
    redis:
      enabled: true
      redisUsername: default
    securityContext:
      container:
        UMASK: "0022"
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          main:
            port: 10153
        type: ClusterIP
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                ANONYMIZE_REMOTE_ADDR: true
                DB_DRIVER: postgres
                DB_HOST:
                  secretKeyRef:
                    key: host
                    name: cnpg-main-urls
                DB_NAME: '{{ .Values.cnpg.main.database }}'
                DB_PASSWORD:
                  secretKeyRef:
                    key: password
                    name: cnpg-main-user
                DB_USER: '{{ .Values.cnpg.main.user }}'
                DEFAULT_DOMAIN: ${DOMAIN_2}
                ENABLE_PERIODIC_VISIT_LOCATE: true
                GEOLITE_LICENSE_KEY: ${GEOLITE_LICENSE_KEY}
                IS_HTTPS_ENABLED: true
                PORT: '{{ .Values.service.main.ports.main.port }}'
                REDIS_SERVERS:
                  secretKeyRef:
                    expandObjectName: false
                    key: url
                    name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
              probes:
                liveness:
                  path: /rest/health
                readiness:
                  path: /rest/health
                startup:
                  path: /rest/health
        replicas: 1
        type: Deployment
